### ISSUE TITLE
Upgrading existing v5 instances to v6 causing errors while creating new job timer

### ISSUE THREAD

**Issue by piyush-kumher** [flowable/flowable-engine#1034]
I have migrated from activiti (5.18.0) to flowable (6.1.2).
I have added the flowable 5 migration jars and migrated the old process instances using SetProcessDefinitionVersionCmd to the latest process definition. 
It fails when a usertask has some boundary timer associated with it.

Error: 
Programmatic error: no parent scope execution found for boundary event

org.flowable.engine.common.api.FlowableException: Programmatic error: no parent scope execution found for boundary event
at org.flowable.engine.impl.bpmn.behavior.BoundaryEventActivityBehavior.executeNonInterruptingBehavior(BoundaryEventActivityBehavior.java:129)
at org.flowable.engine.impl.bpmn.behavior.BoundaryEventActivityBehavior.trigger(BoundaryEventActivityBehavior.java:58)
at org.flowable.engine.impl.agenda.TriggerExecutionOperation.run(TriggerExecutionOperation.java:53)
at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:86)
at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:70)
at org.flowable.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:54)
at org.flowable.engine.impl.interceptor.BpmnOverrideContextInterceptor.execute(BpmnOverrideContextInterceptor.java:25)
at org.flowable.engine.common.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:50)
at org.flowable.engine.common.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:68)
at org.flowable.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47)
at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
at org.flowable.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)
at org.flowable.engine.common.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:29)
at org.flowable.engine.common.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56)
at org.flowable.engine.common.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51)
at org.flowable.engine.impl.asyncexecutor.ExecuteAsyncRunnable.executeJob(ExecuteAsyncRunnable.java:121)
at org.flowable.engine.impl.asyncexecutor.ExecuteAsyncRunnable.run(ExecuteAsyncRunnable.java:91)

Please help me in resolving this issue. Many people have reported this issue on different platform and i could not find any answer to the issue.

**Comment by tijsrademakers** [comment]
Hi, is the latest process definition running on the V6 engine, in other words, it doesn't have the v5 engine version? You can't just migrate a v5 process instance to a v6 process definition. This is why we have the v5 engine JARs to begin with. The idea is that v5 process instances keep running on the embedded v5 engine and new process instances will be started on the v6 engine. Eventually, when no v5 process instances are running anymore, you can remove the v5 engine JARs and all process instances will be running on the v6 engine.
