### ISSUE TITLE
NullPointerException at org.flowable.job.service.impl.util.CommandContextUtil.getJobByteArrayEntityManager(CommandContextUtil.java:112)

### ISSUE THREAD

**Issue by buksvdl** [flowable/flowable-engine#1081]
Spring Boot 2.0.1.RELEASE, Flowable 6.3.0

public List<Job> createDeadLetterJobQuery() throws JsonProcessingException {
        DeadLetterJobQuery deadLetterJobQuery =
            managementService.createDeadLetterJobQuery();
                //.processDefinitionId("IN2003010");
        List<Job> list = deadLetterJobQuery.list();
        DeadLetterJobEntityImpl deadLetterJobEntity =
            (DeadLetterJobEntityImpl)list.get(0);
        String jsonString = jacksonObjectMapper.writeValueAsString(deadLetterJobEntity);
        return list;
    }

com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: org.flowable.job.service.impl.persistence.entity.DeadLetterJobEntityImpl["originalPersistentState"]->java.util.HashMap["exceptionByteArrayRef"]->org.flowable.job.service.impl.persistence.entity.JobByteArrayRef["entity"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391)
.
.
.
.
Caused by: java.lang.NullPointerException
	at org.flowable.job.service.impl.util.CommandContextUtil.getJobByteArrayEntityManager(CommandContextUtil.java:112)
	at org.flowable.job.service.impl.util.CommandContextUtil.getJobByteArrayEntityManager(CommandContextUtil.java:108)
	at org.flowable.job.service.impl.persistence.entity.JobByteArrayRef.ensureInitialized(JobByteArrayRef.java:128)
	at org.flowable.job.service.impl.persistence.entity.JobByteArrayRef.getEntity(JobByteArrayRef.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:687)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)

**Comment by tijsrademakers** [comment]
When writing the DeadLetterJobEntityImpl as a JSON string, it will also try to fetch the  exceptionByteArrayRef value which tries to retrieve the bytes value from another entity. This can only be done inside a CommandContext / running Flowable transaction. Instead you could map the job property values you want to have in the json string manually or you can wrap the call in a transaction, for example using managementService.executeCommand
