### ISSUE TITLE
setTaskIdGenerator(new DbIdGenerator()) with H2 causes NPE

### ISSUE THREAD

**Issue by jyyna** [flowable/flowable-engine#1169]
HI, I was trying to set id generator for engine configuration as suggested in Upgrade notes in [6.3.1 blog post](https://blog.flowable.org/2018/05/22/flowable-6-3-1-release/), but code mentioned there doesn't set the generator for task ids. When I tried to set it like this:

```java
@Bean
    public EngineConfigurationConfigurer<SpringProcessEngineConfiguration> processEngineDbIdGeneratorConfigurer() { 
        return engineConfiguration -> engineConfiguration
                .setTaskIdGenerator(new DbIdGenerator());
    }
```
and with H2 being used as db it throws NPE:
```
2018-07-04T08:04:36.763Z ERROR org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet] [traceId:,parentId:,spanId:] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException: null
	at org.flowable.engine.impl.db.DbIdGenerator.getNewBlock(DbIdGenerator.java:44) ~[flowable-engine-6.3.1.jar:6.3.1]
	at org.flowable.engine.impl.db.DbIdGenerator.getNextId(DbIdGenerator.java:37) ~[flowable-engine-6.3.1.jar:6.3.1]
	at org.flowable.task.service.impl.persistence.entity.TaskEntityManagerImpl.insert(TaskEntityManagerImpl.java:207) ~[flowable-task-service-6.3.1.jar:6.3.1]
	at org.flowable.task.service.impl.persistence.entity.TaskEntityManagerImpl.insert(TaskEntityManagerImpl.java:38) ~[flowable-task-service-6.3.1.jar:6.3.1]
	at org.flowable.task.service.impl.TaskServiceImpl.insertTask(TaskServiceImpl.java:98) ~[flowable-task-service-6.3.1.jar:6.3.1]
	at org.flowable.engine.impl.util.TaskHelper.insertTask(TaskHelper.java:174) ~[flowable-engine-6.3.1.jar:6.3.1]
	at org.flowable.engine.impl.util.TaskHelper.insertTask(TaskHelper.java:149) ~[flowable-engine-6.3.1.jar:6.3.1]
	at org.flowable.engine.impl.bpmn.behavior.UserTaskActivityBehavior.execute(UserTaskActivityBehavior.java:220) ~[flowable-engine-6.3.1.jar:6.3.1]
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.executeActivityBehavior(ContinueProcessOperation.java:258) ~[flowable-engine-6.3.1.jar:6.3.1]
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.executeSynchronous(ContinueProcessOperation.java:155) ~[flowable-engine-6.3.1.jar:6.3.1]
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.continueThroughFlowNode(ContinueProcessOperation.java:112) ~[flowable-engine-6.3.1.jar:6.3.1]
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.continueThroughSequenceFlow(ContinueProcessOperation.java:305) ~[flowable-engine-6.3.1.jar:6.3.1]
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.run(ContinueProcessOperation.java:78) ~[flowable-engine-6.3.1.jar:6.3.1]
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:88) ~[flowable-engine-6.3.1.jar:6.3.1]
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:72) ~[flowable-engine-6.3.1.jar:6.3.1]
	at org.flowable.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:56) ~[flowable-engine-6.3.1.jar:6.3.1]
	at org.flowable.engine.impl.interceptor.BpmnOverrideContextInterceptor.execute(BpmnOverrideContextInterceptor.java:25) ~[flowable-engine-6.3.1.jar:6.3.1]
	at org.flowable.common.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:53) ~[flowable-engine-common-6.3.1.jar:6.3.1]
	at org.flowable.common.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:71) ~[flowable-engine-common-6.3.1.jar:6.3.1]
	at org.flowable.idm.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:49) ~[flowable-idm-spring-6.3.1.jar:6.3.1]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.0.6.RELEASE.jar:5.0.6.RELEASE]
	at org.flowable.idm.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:46) ~[flowable-idm-spring-6.3.1.jar:6.3.1]
	at org.flowable.common.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30) ~[flowable-engine-common-6.3.1.jar:6.3.1]
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56) ~[flowable-engine-common-6.3.1.jar:6.3.1]
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51) ~[flowable-engine-common-6.3.1.jar:6.3.1]
	at org.flowable.engine.impl.RuntimeServiceImpl.startProcessInstanceByKey(RuntimeServiceImpl.java:105) ~[flowable-engine-6.3.1.jar:6.3.1]
...
```

**Comment by martin-grofcik** [comment]
Hi,
The problem which could cause the issue is that 
`new DbIdGenerator()`
does not set command executor. When taskIdGenerator is set, the assumption is that idGenerator is already properly configured. When we are setting  
`engineConfiguration.setIdGenerator(new DbIdGenerator())`
the commandExecutor is set during the initialization 
`org.flowable.engine.impl.cfg.ProcessEngineConfigurationImpl#initIdGenerator`
Which is not the case of taskIdGenerator.
I would say that blog post is correct. You can use DbIdGenerator for the engine for tasks too.

Regards
Martin

**Comment by martin-grofcik** [comment]
Hi,

I've checked te taskIdGenerator configuration in `org.flowable.test.spring.boot.process.ProcessEngineAutoConfigurationTest#processEngineWithCustomIdGenerator
`
TaskIdGenerator is DbIdGenerator. Could you create a jUnit test for your case please?

Martin

**Comment by jyyna** [comment]
I did try it in flowable-spring-boot-samples/flowable-spring-boot-sample-content and of course it works. I will try to find out why in my case, after setting `engineConfiguration.setIdGenerator(new DbIdGenerator())`, it starts to generate "db like" processIds, but still produces uuids for task ids.

**Comment by jyyna** [comment]
well, apparently it works when using dependency:
```
<dependency>
	<groupId>org.flowable</groupId>
	<artifactId>flowable-spring-boot-starter-process</artifactId>
	<version>6.3.1</version>
</dependency>
```

but not with 
```
<dependency>
	<groupId>org.flowable</groupId>
	<artifactId>flowable-spring-boot-starter-rest</artifactId>
	<version>6.3.1</version>
</dependency>
```

**Comment by jyyna** [comment]
so in this [repository](https://github.com/jyyna/flowable-taskid-problem) there is minimal code to show the problem. When using `flowable-spring-boot-starter-rest` dependency, test fails. When you change the dependency to `flowable-spring-boot-starter-process` it starts to work. Testing for the UUID is done in the simplest way: does the ID contain -?

**Comment by filiphr** [comment]
Thanks for the reproducal @jyyna. We will have a look into it and try to figure out why that is happening.

**Comment by martin-grofcik** [comment]
Hi Martin,
you are right. Fixed in the pull request:
https://github.com/flowable/flowable-engine/pull/1175

Martin
