### ISSUE TITLE
Custom identity management error

### ISSUE THREAD

**Issue by lruijun** [flowable/flowable-engine#1182]
I override the IdmIdentityServiceImpl class  directly and use the implemented class for the idmIdentityService property in the ProcessEngineConfiguration. (same like https://www.flowable.org/docs/userguide/index.html#advanced.custom.session.manager    18.8)
but it didn't work in Flowable 6.3.1
<img width="647" alt="flowable_err1" src="https://user-images.githubusercontent.com/5811905/42723712-cc80bbcc-8795-11e8-998b-94a8e39741fe.png">

`Caused by: org.springframework.beans.NotWritablePropertyException: Invalid property 'idmIdentityService' of bean class [org.flowable.spring.SpringProcessEngineConfiguration]: Bean property 'idmIdentityService' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
	at org.springframework.beans.BeanWrapperImpl.setPropertyValue(BeanWrapperImpl.java:1076)
	at org.springframework.beans.BeanWrapperImpl.setPropertyValue(BeanWrapperImpl.java:927)
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:95)
	at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:75)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1508)`

**Comment by tijsrademakers** [comment]
Hi,

In the documentation the flowable-ldap project is referenced and the flowable-ldap-configurator module. You can have a look here how the IdmIdentityService implementation can be set https://github.com/flowable/flowable-engine/blob/master/modules/flowable-ldap-configurator/src/main/java/org/flowable/ldap/LDAPConfigurator.java

The IDM part has been separated into an idm engine and therefore the IdmIdentityService implementation needs to be set on the IdmEngineConfiguration, not on the process engine configuration anymore. The documentation needs to be updated to show this.
