### ISSUE TITLE
flowable-rest and flowable-task not working not working with MariaDB

### ISSUE THREAD

**Issue by leandrocosta** [flowable/flowable-engine#1230]
It seems liquibase doesn't know MariaDB supports timestamp with fractional precision:

<pre>
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set org/flowable/content/db/liquibase/flowable-content-db-changelog.xml::1::activiti:
     Reason: liquibase.exception.DatabaseIncapableOfOperation: Using a TIMESTAMP data type with a fractional precision of 6 is not supported on mariadb: A timestamp datatype with 6 fractional digits was requested, but MySQL only supports 0 digits.
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:78)
	at liquibase.Liquibase.update(Liquibase.java:202)
	at liquibase.Liquibase.update(Liquibase.java:179)
	at liquibase.Liquibase.update(Liquibase.java:175)
	at liquibase.Liquibase.update(Liquibase.java:168)
	at org.flowable.content.engine.impl.db.ContentDbSchemaManager.initSchema(ContentDbSchemaManager.java:100)
	... 128 more
Caused by: liquibase.exception.DatabaseIncapableOfOperation: Using a TIMESTAMP data type with a fractional precision of 6 is not supported on mariadb: A timestamp datatype with 6 fractional digits was requested, but MySQL only supports 0 digits.
	at liquibase.datatype.core.TimestampType.toDatabaseDataType(TimestampType.java:47)
	at liquibase.sqlgenerator.core.CreateTableGenerator.generateSql(CreateTableGenerator.java:55)
	at liquibase.sqlgenerator.core.CreateTableGenerator.generateSql(CreateTableGenerator.java:23)
	at liquibase.sqlgenerator.SqlGeneratorChain.generateSql(SqlGeneratorChain.java:30)
	at liquibase.sqlgenerator.SqlGeneratorFactory.generateSql(SqlGeneratorFactory.java:223)
	at liquibase.executor.AbstractExecutor.applyVisitors(AbstractExecutor.java:25)
	at liquibase.executor.jvm.JdbcExecutor.access$500(JdbcExecutor.java:38)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:338)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:57)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1229)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1211)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:600)
	... 135 more
</pre>

**Comment by leandrocosta** [comment]
liquibase ignores the fact that MariaDB introduced fractional support to timestamp before MySQL. This is not a problem with flowable-engine.

**Comment by filiphr** [comment]
Maybe it's worth opening an issue in the Liquibase project and so they can also have a look at it

**Comment by leandrocosta** [comment]
I opened a pull request.

**Comment by yingl** [comment]
Hello, have you guys fixed this issue? I'm worrying the default H2 database can only supported limited data.

**Comment by tijsrademakers** [comment]
We support a lot of different database in addition to H2, like MySQL, Postgres, Oracle, DB2 and MSSQL. We don't have specific support for MariaDB yet, but if there's a lot of request from the community we can work on this.

**Comment by berndgoetz** [comment]
MariaDB support would be nice, as we're running on Cloud Foundry provided by Swisscom, called AppCloud. See https://developer.swisscom.com/. They "only" have MariaDB. 
On the other hand, we're not going to use MariaDB in production later, so never mind, or only if it means little effort to do so.

But another question then is how to configure an "external" database (i.e. one that is not a service on CF). E.g. I could get an Oracle database that I could use but I need to be able to configure it accordingly when deploying the apps to CF. I guess some environment variables might make that work. Btw, I was following your blog entry at https://blog.flowable.org/2018/06/11/running-flowable-on-cloud-foundry/.

**Comment by berndgoetz** [comment]
Update: I just threw MariaDB at Flowable and it seems to work so far.

**Comment by berndgoetz** [comment]
And it also works with Oracle. I've documented it at https://blog.flowable.org/2018/06/11/running-flowable-on-cloud-foundry/.
