### ISSUE TITLE
VariableInstance.getValue() fails with the NPE for variables of "serialized" type

### ISSUE THREAD

**Issue by gorbunkov** [flowable/flowable-engine#1297]
I needed to get a list of process variables in a way that there are both variable value and its type name in the result, so the RuntimeService.getVariableInstances(String executionId) method seemed to be the right choice.
If I have a List in the process variable, then a NullPointerException occurs when I invoke the VariableInstance.getValue().

Flowable version: 6.3.1
A unit test that reproduces the error:
```java
package com.company;
import org.flowable.engine.runtime.ProcessInstance;
import org.flowable.engine.test.Deployment;
import org.flowable.engine.test.FlowableRule;
import org.flowable.variable.api.persistence.entity.VariableInstance;
import org.junit.Rule;
import org.junit.Test;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import static org.junit.Assert.assertEquals;

public class MyUnitTest {

    @Rule
    public FlowableRule flowableRule = new FlowableRule();

    @Test
    @Deployment(resources = {"my-process.bpmn20.xml"})
    public void test() {
        Map<String, Object> processVariables = new HashMap<>();
        processVariables.put("myList", Arrays.asList("one", "two"));
        ProcessInstance processInstance = flowableRule.getRuntimeService()
                .startProcessInstanceByKey("my-process", processVariables);

        VariableInstance myListVariableInstance = flowableRule.getRuntimeService()
                .getVariableInstances(processInstance.getId())
                .get("myList");

        //the test fails on next line with the NPE
        List<String> list = (List<String>) myListVariableInstance.getValue();
        assertEquals(2, list.size());
    }
}

```

The stacktrace:
```
java.lang.NullPointerException
	at org.flowable.variable.service.impl.util.CommandContextUtil.getByteArrayEntityManager(CommandContextUtil.java:63)
	at org.flowable.variable.service.impl.util.CommandContextUtil.getByteArrayEntityManager(CommandContextUtil.java:59)
	at org.flowable.variable.service.impl.persistence.entity.VariableByteArrayRef.ensureInitialized(VariableByteArrayRef.java:99)
	at org.flowable.variable.service.impl.persistence.entity.VariableByteArrayRef.getBytes(VariableByteArrayRef.java:52)
	at org.flowable.variable.service.impl.persistence.entity.VariableInstanceEntityImpl.getBytes(VariableInstanceEntityImpl.java:108)
	at org.flowable.variable.service.impl.types.ByteArrayType.getValue(ByteArrayType.java:37)
	at org.flowable.variable.service.impl.types.SerializableType.getValue(SerializableType.java:62)
	at org.flowable.variable.service.impl.persistence.entity.VariableInstanceEntityImpl.getValue(VariableInstanceEntityImpl.java:133)
	at com.company.MyUnitTest.test(MyUnitTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.flowable.engine.test.FlowableRule$1.evaluate(FlowableRule.java:116)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by filiphr** [comment]
The `VariableInstance` value in this case is lazy loaded, which means that it will use the byte array entity manager to fetch the value.

What you can do for the time being is to use the `ManagementService#executeCommand` and invoke the getter from within the command

**Comment by gorbunkov** [comment]
Thank you for the answer, @filiphr , but can you please clarify, which command should I invoke?

**Comment by filiphr** [comment]
@gorbunkov you should create your own command. You can just do `managementService#executeCommand(commandContext -> myListVariableInstance.getValue())`;

**Comment by gorbunkov** [comment]
@filiphr this worked. Thank you!

**Comment by filiphr** [comment]
I think that this issue has now been resolved with https://github.com/flowable/flowable-engine/commit/789090c43015455906e21c204304d681a5b27e1c. Especially the fix for the [ByteArrayRef](https://github.com/flowable/flowable-engine/commit/789090c43015455906e21c204304d681a5b27e1c#diff-332780b395bff94f14057567cf9706cc1fada17d396fbcaaa7bf33e1c5ff4ae2R139-R146).
