### ISSUE TITLE
No mapping found for HTTP request with URI [/flowable-task/cmmn-api/management/jobs/

### ISSUE THREAD

**Issue by cdeneux** [flowable/flowable-engine#1300]
Using Flowable Admin (deployed using Docker Compose), in CMMN part:
1. list executable jobs through the tab `Jobs`, filter `Executable jobs`
2. select a job
3. execute the job using button `Execute job`

The following error occurs:
```
No mapping found for HTTP request with URI [/flowable-task/cmmn-api/management/jobs/<job-id>] in DispatcherServlet with name 'Flowable CMMN Rest API'

org.flowable.ui.admin.service.engine.exception.FlowableServiceException: An error occurred while calling Flowable: HTTP/1.1 404 
 	at org.flowable.ui.admin.service.engine.FlowableClientService.executeRequestNoResponseBody(FlowableClientService.java:462) ~[flowable-ui-admin-logic-6.3.1.jar!/:6.3.1]
 	at org.flowable.ui.admin.service.engine.CmmnJobService.executeJob(CmmnJobService.java:88) ~[flowable-ui-admin-logic-6.3.1.jar!/:6.3.1]
 	at org.flowable.ui.admin.rest.client.CmmnJobClientResource.executeCmmnJob(CmmnJobClientResource.java:89) [flowable-ui-admin-rest-6.3.1.jar!/:6.3.1]
 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_102]
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209) [spring-web-5.0.6.RELEASE.jar!/:5.0.6.RELEASE]
```

It seems to me that the REST API used to execute an executable job is not the right one. I think it should be `/flowable-task/cmmn-api/cmmn-management/jobs/<job-id>`

No error occurs executing a timer job in the same way but using the filter `Timer jobs`.

**Comment by tijsrademakers** [comment]
Fixed, thanks for reporting

**Comment by cdeneux** [comment]
Thanks @tijsrademakers for fixing it
