### ISSUE TITLE
HistoricIdentityLinkEntity createTime not set

### ISSUE THREAD

**Issue by FranPregernik** [flowable/flowable-engine#1309]
Hi,

we are using flowable 6.3.1 in oracle and have partitioned the table ACT_HI_IDENTITYLINK on the create_time_ column. This column can't be null and we set the default value to oracle's systimestamp.

However, I have noticed we get a ORA-14300 error below: 
```
org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: java.sql.SQLException: ORA-14300: partitioning key maps to a partition outside maximum permitted number of partitions

### The error may involve org.flowable.identitylink.service.impl.persistence.entity.HistoricIdentityLinkEntityImpl.bulkInsertHistoricIdentityLink-Inline
### The error occurred while setting parameters
### SQL: INSERT ALL                   INTO ACT_HI_IDENTITYLINK (ID_, TYPE_, USER_ID_, GROUP_ID_, TASK_ID_, PROC_INST_ID_, SCOPE_ID_, SCOPE_TYPE_, SCOPE_DEFINITION_ID_, CREATE_TIME_) VALUES            (?,            ?,            ?,            ?,            ?,     
       ?,            ?,            ?,            ?,            ?)                  INTO ACT_HI_IDENTITYLINK (ID_, TYPE_, USER_ID_, GROUP_ID_, TASK_ID_, PROC_INST_ID_, SCOPE_ID_, SCOPE_TYPE_, SCOPE_DEFINITION_ID_, CREATE_TIME_) VALUES            (?,            ?,  
          ?,            ?,            ?,            ?,            ?,            ?,            ?,            ?)                  INTO ACT_HI_IDENTITYLINK (ID_, TYPE_, USER_ID_, GROUP_ID_, TASK_ID_, PROC_INST_ID_, SCOPE_ID_, SCOPE_TYPE_, SCOPE_DEFINITION_ID_, CREATE
_TIME_) VALUES            (?,            ?,            ?,            ?,            ?,            ?,            ?,            ?,            ?,            ?)             SELECT * FROM dual
### Cause: java.sql.SQLException: ORA-14300: partitioning key maps to a partition outside maximum permitted number of partitions

        at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:200)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185)
        at org.flowable.common.engine.impl.db.DbSqlSession.flushBulkInsert(DbSqlSession.java:470)
        at org.flowable.common.engine.impl.db.DbSqlSession.flushInsertEntities(DbSqlSession.java:426)
        at org.flowable.common.engine.impl.db.DbSqlSession.flushInserts(DbSqlSession.java:403)
        at org.flowable.common.engine.impl.db.DbSqlSession.flush(DbSqlSession.java:288)
...
```

I tracked down the point where the HistoricIdentityLinkEntity is created and one of the places is in:
https://github.com/flowable/flowable-engine/blob/flowable-6.3.1/modules/flowable-engine/src/main/java/org/flowable/engine/impl/history/DefaultHistoryManager.java#L419. In this method the createTime field is not set at all. 

Contrast this to this point where another historic entity is created:
https://github.com/flowable/flowable-engine/blob/flowable-6.3.1/modules/flowable-engine/src/main/java/org/flowable/engine/impl/history/AbstractHistoryManager.java#L325

I think createTime should be filled always.

Does anyone know a kludge around this? I see the ProcessEngineConfigurationImpl.initIdentityLinkServiceConfiguration is creating the HistoricIdentityLinkService that is used in DefaultHistoryManager.recordIdentityLinkCreated.

I will try to add a decorator around the HistoricIdentityLinkService.createHistoricIdentityLink method to fill the createTime. Anyone have a better idea?

**Comment by FranPregernik** [comment]
My kludge - custom EngineConfigurator

```java
    /**
     * Fixes https://github.com/flowable/flowable-engine/issues/1309
     */
    private static class FixFlowableEngineIssue1309EngineConfigurator implements EngineConfigurator {

        @Override
        public void beforeInit(AbstractEngineConfiguration engineConfiguration) {
            // noop
        }

        @Override
        public void configure(AbstractEngineConfiguration engineConfiguration) {
            final ProcessEngineConfigurationImpl processEngineConfiguration = (ProcessEngineConfigurationImpl) engineConfiguration;
            final IdentityLinkServiceConfiguration identityLinkServiceConfiguration = (IdentityLinkServiceConfiguration) processEngineConfiguration.getServiceConfigurations().get(EngineConfigurationConstants.KEY_IDENTITY_LINK_SERVICE_CONFIG);
            identityLinkServiceConfiguration.setHistoricIdentityLinkService(new HistoricIdentityLinkServiceImpl(identityLinkServiceConfiguration) {

                @Override
                public HistoricIdentityLinkEntity createHistoricIdentityLink() {
                    final HistoricIdentityLinkEntity historicIdentityLink = super.createHistoricIdentityLink();
                    if (isNull(historicIdentityLink.getCreateTime())) {
                        final Date now = processEngineConfiguration.getClock().getCurrentTime();
                        historicIdentityLink.setCreateTime(now);
                    }
                    return historicIdentityLink;
                }
            });
        }

        @Override
        public int getPriority() {
            return 0;
        }
    }
```

and then register it in the ProcessEngineConfiguration like so:
```java
        conf.addConfigurator(new FixFlowableEngineIssue1309EngineConfigurator());
```

**Comment by filiphr** [comment]
Thanks for reporting this @FranPregernik. You are right the `createTime` should always be set and we have pushed a fix for that on master. It will be part of the next release.

Regarding your kludge, nice handling of the problem.  The fix we did is one level lower on the entity manager.
