### ISSUE TITLE
email task fails in 6.4.0 after upgrading from 6.2.1

### ISSUE THREAD

**Issue by bvedam** [flowable/flowable-engine#1332]
Hi - I was using 6.2.1 with the following email server configuration
email.host=smtp.mycompany.com
email.port=25
email.useCredentials=false
email.username=
email.password=

I then upgraded to 6.4.0, where the config variable names have changed and useCredentials doesn't exist anymore. Doc says it is implicit based on whether a value is provided to username or not.

flowable.mail.server.host=smtp.mycompany.com
flowable.mail.server.port=25
flowable.mail.server.username=
flowable.mail.server.password=

But the email task fails during workflow execution with the following error
{
  "name": "StatusCodeError",
  "statusCode": 500,
  "message": "500 - {\"message\":\"Internal server error\",\"exception\":\"Could not send e-mail in execution 116711\"}",
  "error": {
    "message": "Internal server error",
    "exception": "Could not send e-mail in execution 116711"
  },
.......
}

I tried using using the flowable.mail.server.useCredentials but that didn't work either. I even added the old config variables email.xxxxx to the properties but that did't help either.

Appreciate your help in figuring out the root-cause here.

**Comment by tijsrademakers** [comment]
Hi,

Are you using this in the Flowable Task application?

**Comment by bvedam** [comment]
I have the task application installed, but I am not using it. We have a custom app accessing workflow instances thru REST APIs.

**Comment by tijsrademakers** [comment]
Ok thanks, do you have the Flowable starter or flowable-spring-boot-autoconfigure modules as dependency? Because here you can see that it sets the email configuration in the ProcessEngineConfiguration:

https://github.com/flowable/flowable-engine/blob/master/modules/flowable-spring-boot/flowable-spring-boot-starters/flowable-spring-boot-autoconfigure/src/main/java/org/flowable/spring/boot/ProcessEngineAutoConfiguration.java

If you didn't include the starter or autoconfigure module, then you need to set the email configuration in a similar way in your application.

**Comment by bvedam** [comment]
Thanks for your quick response. Currently all apps (idm, admin, task, rest, modeler) are being deployed from the respective war files I got from the flowable-6.4.0.zip. The only place where I see email configuration is flowable-task module's flowable-default.properties file. 

Now to include the module you mentioned, could you tell me which module's property file should be modified?

**Comment by bvedam** [comment]
Hi - After further troubleshooting I noticed that the Jobs-Deadletter Jobs showed me the stack trace for the failed email task. Looks like it is still trying to connect to the default host/port
 **Couldn't connect to host, port: localhost, 1025**

Appears the mail server properties from flowable-default.properties are not being picked up, while the rest of the properties are.  However, if I set the Asynchronous flag for the mail task, it successfully sends the email. Could this be a bug.

	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56)
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51)
	at org.flowable.job.service.impl.asyncexecutor.ExecuteAsyncRunnable.executeJob(ExecuteAsyncRunnable.java:128)
	at org.flowable.job.service.impl.asyncexecutor.ExecuteAsyncRunnable.run(ExecuteAsyncRunnable.java:116)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.commons.mail.EmailException: Sending the email to the following server failed : localhost:1025
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1469)
	at org.apache.commons.mail.Email.send(Email.java:1496)
	at org.flowable.engine.impl.bpmn.behavior.MailActivityBehavior.execute(MailActivityBehavior.java:102)
	... 21 more
Caused by: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: localhost, 1025; timeout 60000;
  nested exception is:
	java.net.ConnectException: Connection refused (Connection refused)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2209)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:740)
	at javax.mail.Service.connect(Service.java:366)
	at javax.mail.Service.connect(Service.java:246)
	at javax.mail.Service.connect(Service.java:195)
	at javax.mail.Transport.send0(Transport.java:254)
	at javax.mail.Transport.send(Transport.java:124)
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1459)
	... 23 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:357)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:238)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2175)

**Comment by bvedam** [comment]
Using Flowable v6.4.0.
mail properties defined in C:\uis-flowable\temp\flowable-task\WEB-INF\classes\flowable-default.properties

Response to @PascalSchumacher :
I verified that all my email tasks are Async. And this error is not frequent or reproducible. It fails once in a while on an email task that had previously worked numerous times. 
It acts like it falls back on default localhost mail server, if the custom SMTP config connection timed out or failed for some reason. Does Flowable have a retry option if custom email server fails or is offline, or has connection times out for some reason?

Thx

**Comment by filiphr** [comment]
@bvedam do you also have `flowable-rest` running or only `flowable-task`?

**Comment by bvedam** [comment]
I have flowable-rest too. Running 4 modules in prod (admin, idm, task, rest). DEV has modeler in addition
