### ISSUE TITLE
Flowable Modeler & Flowable Task & BPMN engine vs script format missing

### ISSUE THREAD

**Issue by cdeneux** [flowable/flowable-engine#1333]
Hi all,

Using Flowable Modeler, I wrote a simple process definition containing only a script task. I used a Flowable Application to deploy it into Flowable Task:
1. First, I create the process definition with setting neither the script format nor the script,
2. When checking the process definition with Flowable Modeler, I get an error. Normal !
3. I fixed the error setting a Groovy script (the script format was always empty),
4. When checking the process definition no error occurs
5. I deployed the process definition
6. Using Flowable Task, I tried to create a process instance without success. However, no error is dispayed at Flowable Task level. But, an error is logged at the web-application server side:
```
org.flowable.common.engine.api.FlowableException: Error in Script
	at org.flowable.engine.impl.bpmn.behavior.ScriptTaskActivityBehavior.execute(ScriptTaskActivityBehavior.java:82) ~[flowable-engine-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.executeActivityBehavior(ContinueProcessOperation.java:264) ~[flowable-engine-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.executeSynchronous(ContinueProcessOperation.java:158) ~[flowable-engine-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.continueThroughFlowNode(ContinueProcessOperation.java:113) ~[flowable-engine-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.continueThroughSequenceFlow(ContinueProcessOperation.java:311) ~[flowable-engine-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.run(ContinueProcessOperation.java:79) ~[flowable-engine-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:88) ~[flowable-engine-6.4.0-SNAPSHOT.jar:6.4.0-SNAPSHOT]
	...
```
7. When I had set the script format at script task level, all works fine.
8. Perhaps, if the script format is not set, the script must be a JavaScript. I tried with a JavaScript, but I got the same error

IMO, several inconsistency exist:
* Flowable Modeler should throw an error on process definition validation if the script format is not set,
* The error mentioned above should be returned to the user and displayed by Flowable Task,
* In this case, the error to return to the user should be clearer, for example: `Script format is not set`. Or a default script format must be used.

Regards,
Christophe

**Comment by PascalSchumacher** [comment]
Yes, the cause of this error is read hard to track down. It would be great if at least the error message retured by the engine would be improved.

**Comment by PascalSchumacher** [comment]
I took a look at the code the default scripting language is `juel`, see: https://github.com/flowable/flowable-engine/blob/97fe915e1d247c11983a4fc130efd2fb9ca1c447/modules/flowable-engine-common/src/main/java/org/flowable/common/engine/impl/scripting/ScriptingEngines.java#L37
