### ISSUE TITLE
xml lable flowable:delegateExpression cause error in mysql datasource

### ISSUE THREAD

**Issue by catfishlty** [flowable/flowable-engine#1375]
In my project:
spring-boot:2.1.0.M4
flowable-engine: 6.4.0

**I found that when i use default DataSource(H2 Database) and the default config , it works fine, the code is below**
```  java
@Qualifier("processEngine")
@Autowired
private ProcessEngine processEngine;
```

when i change the processEngine generate method to this, it will cause such problem.
and this is the config code
``` java
ProcessEngine processEngine = new StandaloneProcessEngineConfiguration()
                .setJdbcUrl(mySqlConfigProperties.getUrl())
                .setJdbcDriver(mySqlConfigProperties.getDriverClassName())
                .setJdbcUsername(mySqlConfigProperties.getUsername())
                .setJdbcPassword(mySqlConfigProperties.getPassword())
                .setDatabaseSchemaUpdate("true")
                .buildProcessEngine();
```
 there is the exception info  in console

``` java
org.flowable.common.engine.api.FlowableException: Exception while invoking TaskListener: Unknown property used in expression: ${applyCommitListener}
at org.flowable.engine.impl.bpmn.listener.ListenerNotificationHelper.executeTaskListeners(ListenerNotificationHelper.java:130)
at org.flowable.engine.impl.bpmn.listener.ListenerNotificationHelper.executeTaskListeners(ListenerNotificationHelper.java:109)
at org.flowable.engine.impl.util.TaskHelper.completeTask(TaskHelper.java:85)
at org.flowable.engine.impl.cmd.CompleteTaskCmd.execute(CompleteTaskCmd.java:64)
at org.flowable.engine.impl.cmd.CompleteTaskCmd.execute(CompleteTaskCmd.java:26)
at org.flowable.engine.impl.cmd.NeedsActiveTaskCmd.execute(NeedsActiveTaskCmd.java:58)
at org.flowable.engine.impl.interceptor.CommandInvoker$1.run(CommandInvoker.java:51)
at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:93)
at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:72)
at org.flowable.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:56)
at org.flowable.engine.impl.interceptor.BpmnOverrideContextInterceptor.execute(BpmnOverrideContextInterceptor.java:25)
at org.flowable.common.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:53)
at org.flowable.common.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:71)
at org.flowable.common.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30)
at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56)
at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51)
at org.flowable.engine.impl.TaskServiceImpl.complete(TaskServiceImpl.java:213)
at com.flowable.demo.FlowableLeaveTaskTest.testFlow(FlowableLeaveTaskTest.java:95)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
```

and this is the listener define in bpmn file
``` xml
<userTask flowable:assignee="${uid}" id="_3" name="some_name">
    <extensionElements>
        <flowable:taskListener event="complete" delegateExpression="${applyCommitListener}"/>
    </extensionElements>
</userTask>
```

and last this is the listener
``` java
@Slf4j
@Component(value = "applyCommitListener")
public class ApplyCommitListener implements TaskListener {
    @Override
    public void notify(DelegateTask delegateTask) {
        log.info("applyCommitListener");
   }
}
```

so please help me solve this problem, thx!

**Comment by catfishlty** [comment]
Thanks for your reply,
it is a very strange problem, when i use spring Autowired annotations (use the default DataSource) it works fine, so i don't think this component is not scanned by the Spring container

**Comment by filiphr** [comment]
The reason why it is not being picked up is because you are using the `StandaloneProcessEngineConfiguration`. This configuration knows nothing about Spring so it won't be able to use the `ApplicationContext`.

From what you are showing to me it looks like you are trying to have a process enigne that will work with a different datasource then the default one you have from Spring Boot. Is this correct? Do you want to have 2 `ProcessEngine` beans present?

What I am going to suggest to you is to modify the `SpringProcessEngineConfiguration` which is provided by the Flowable auto configuration.

A way to do this would be to provide a bean of `EngineConfigurationConfigurer<SpringProcessEngineConfiguration>`. This can look like:

```

@Bean
public EngineConfigurationConfigurer<SpringProcessEngineConfiguration> myCustomProcessEngineConfiguration(MySqlConfigProperties mySqlConfigProperties) {
    return engineConfiguration -> {
        // Perform the configuration here. 
        // keep in mind that the datasource is already set here.
    }
}
```

Another approach would be to provide your own bean of `SpringProcessEngineConfiguration`. However, keep in mind that in this case you are going to lose all defaults that the `ProcessEngineAutoConfiguration` is doing.

**Comment by catfishlty** [comment]
> The reason why it is not being picked up is because you are using the `StandaloneProcessEngineConfiguration`. This configuration knows nothing about Spring so it won't be able to use the `ApplicationContext`.
> 
> From what you are showing to me it looks like you are trying to have a process enigne that will work with a different datasource then the default one you have from Spring Boot. Is this correct? Do you want to have 2 `ProcessEngine` beans present?
> 
> What I am going to suggest to you is to modify the `SpringProcessEngineConfiguration` which is provided by the Flowable auto configuration.
> 
> A way to do this would be to provide a bean of `EngineConfigurationConfigurer<SpringProcessEngineConfiguration>`. This can look like:
> 
> ```
> 
> @Bean
> public EngineConfigurationConfigurer<SpringProcessEngineConfiguration> myCustomProcessEngineConfiguration(MySqlConfigProperties mySqlConfigProperties) {
>     return engineConfiguration -> {
>         // Perform the configuration here. 
>         // keep in mind that the datasource is already set here.
>     }
> }
> ```
> Another approach would be to provide your own bean of `SpringProcessEngineConfiguration`. However, keep in mind that in this case you are going to lose all defaults that the `ProcessEngineAutoConfiguration` is doing.

Thanks for the suggesions, it help me solve the problem.
But i still have some questions about the Flowable. If you don't mind, please send me a email where the address is in my profile, i wanna talk about these question.

**Comment by filiphr** [comment]
>But i still have some questions about the Flowable. If you don't mind, please send me a email where the address is in my profile, i wanna talk about these question.

If you have question about Flowable you can ask them on our [forum](https://forum.flowable.org/) where us or someone from the community can reply. Flowable being an open source project benefits from the fact that people can ask and answer questions in the open.

Closing this issue as it has been resolved
