### ISSUE TITLE
Can't run apps with Postgres driver

### ISSUE THREAD

**Issue by yonigibbs** [flowable/flowable-engine#1394]
I'm trying to run the flowable apps (e.g. IDM and Modeller) using a command-line to start them, and am having a problem getting them to connect to Postgres instead of H2: the system seems to fail to load the driver.

I'm following the documentation [here](https://www.flowable.org/docs/userguide/index.html#uiAppInstallation), where it says this:

> Since the UI apps are Spring Boot executable apps it is possible to run them as standalone applications without the need of an application server. Starting single application looks like: `java -jar flowable-idm.war`

I'd like to use Postgres rather than H2 so am trying to use Spring's externalised configuration as recommended in your documentation.  I can pass in my arg values using a command line such as this:

```
java -jar flowable-modeler.war --spring.datasource.driver-class-name=org.postgresql.Driver --spring.datasource.url=jdbc:postgresql://localhost:5433/flowable --spring.datasource.username=flowable --spring.datasource.password=flowable
```

The final step is that I need to add the Postgres driver JAR to the classpath.  The documentation at the end of section 15.1 tells me that I need to do download the JAR and then run the Spring Boot app providing a path to it, like this:

`java -Dloader.path=/location/to/your/driverfolder -jar flowable-idm.war`

I've done that, but I get this error:

```
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
...
Caused by: java.lang.IllegalStateException: Cannot load driver class: org.postgresql.Driver
        at org.springframework.util.Assert.state(Assert.java:94) ~[spring-core-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
        at org.springframework.boot.autoconfigure.jdbc.DataSourceProperties.determineDriverClassName(DataSourceProperties.java:224) ~[spring-boot-autoconfigure-2.0.5.RELEASE.jar!/:2.0.5.RELEASE]
```

I've been doing some reading and found [this](https://stackoverflow.com/questions/23427745/how-to-put-a-directory-first-on-the-classpath-with-spring-boot/23428682#23428682) on StackOverflow, which states:

> You can use `loader.path` but only if the `Main-Class` is `PropertiesLauncher` (so it depends how you built the JAR file). Maybe you need to re-build the JAR with packaging=ZIP in the Boot plugin

From what I can see the `packaging` setting is `war`, not `zip`.  I'm not sure if that matters or not.

Is there something I'm doing wrong?  Or is this a bug?

Incidentally, there is also a broken link on that documentation page I linked at the top, in section 15.1

> An example configuration can be found on [Github](https://github.com/flowable/flowable-engine/blob/master/modules/flowable-ui-task/flowable-ui-task-app/src/main/resources/application.properties).

The URL is https://github.com/flowable/flowable-engine/blob/master/modules/flowable-ui-task/flowable-ui-task-app/src/main/resources/application.properties, but looks like the file name should be `flowable-default.properties` now.

**Comment by filiphr** [comment]
Thanks for raising this @yonigibbs. Yes the documentation says that one can use `loader.path` to add extra jars to the classpath. However, as you noticed this does not work when the generated artifact is war as it is a different mechanism. This is an oversight from us and we are going to fix this in the documentation.

>From what I can see the packaging setting is `war`, not `zip`. I'm not sure if that matters or not.

Yes this matters a lot. I learned this the hard way as well. I thought that we would have win win if we do it as a `war` and get everything in one 😄 .

The only thing that you could do in this moment is to:

### Use normal servlet container (e.g. tomcat)

Use a normal tomcat and place the driver in the appropriate folder (e.g. tomcat `lib`).

### Patch the war

You can patch the war and add the postgres driver in the `WEB-INF/lib-provided` folder.

__________
>Incidentally, there is also a broken link on that documentation page I linked at the top, in section 15.1

We'll fix the broken link. Thanks for reporting it.

**Comment by yonigibbs** [comment]
Thanks @filiphr, we did just patch the war file manually in the end.

BTW: I've been stepping through the documentation and have a small number of minor comments. Just with the documentation itself rather than the software (e.g. missing steps in the instructions, or small typos). If you'd like me to share that list with you let me know how best to get it to you.

Thanks again.

**Comment by filiphr** [comment]
Great that it works for you @yonigibbs.

> If you'd like me to share that list with you let me know how best to get it to you.

Sharing it is definitely a good idea. There are different options. 

* Immediately create a PR with the documentation changes
* Create an issue or a forum post on our [forum](https://forum.flowable.org/) with the list and we can have a look at it

**Comment by yonigibbs** [comment]
Have created a forum issue: https://forum.flowable.org/t/some-minor-issues-with-documentation/2916

Thanks.
