### ISSUE TITLE
i

### ISSUE THREAD

**Issue by miriambron** [flowable/flowable-engine#1408]
using flowable in docker containers.
while trying to create process in flowable 6.4 via Rest API got an exception.

The API:

POST runtime/process-instances
{
“processDefinitionKey”:“XXXX”,
“variables”: [
{
“name”:“myVar”,
“value”:“This is a variable”,
}
]
}

Exception:

Caused by: java.lang.NoClassDefFoundError: org/apache/ivy/core/report/ResolveReport
flowable-rest-6.4 | at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_181]
flowable-rest-6.4 | at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_181]
flowable-rest-6.4 | at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_181]
flowable-rest-6.4 | at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_181]
flowable-rest-6.4 | at java.beans.Introspector.getPublicDeclaredMethods(Introspector.java:1336) ~[?:1.8.0_181]
flowable-rest-6.4 | at java.beans.Introspector.getTargetMethodInfo(Introspector.java:1197) ~[?:1.8.0_181]
flowable-rest-6.4 | at java.beans.Introspector.getBeanInfo(Introspector.java:426) ~[?:1.8.0_181]
flowable-rest-6.4 | at java.beans.Introspector.getBeanInfo(Introspector.java:173) ~[?:1.8.0_181]
flowable-rest-6.4 | at groovy.lang.MetaClassImpl$15.run(MetaClassImpl.java:3328) ~[groovy-2.4.15.jar!/:2.4.15]
flowable-rest-6.4 | at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_181]
flowable-rest-6.4 | at groovy.lang.MetaClassImpl.addProperties(MetaClassImpl.java:3326) ~[groovy-2.4.15.jar!/:2.4.15]
flowable-rest-6.4 | at groovy.lang.MetaClassImpl.initialize(MetaClassImpl.java:3303) ~[groovy-2.4.15.jar!/:2.4.15]
flowable-rest-6.4 | at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:289) ~[groovy-2.4.15.jar!/:2.4.15]
flowable-rest-6.4 | at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:331) ~[groovy-2.4.15.jar!/:2.4.15]
flowable-rest-6.4 | at groovy.grape.GrapeIvy.$getStaticMetaClass(GrapeIvy.groovy) ~[groovy-2.4.15.jar!/:2.4.15]
flowable-rest-6.4 | at groovy.grape.GrapeIvy.(GrapeIvy.groovy:77) ~[groovy-2.4.15.jar!/:2.4.15]
flowable-rest-6.4 | at sun.reflect.GeneratedConstructorAccessor151.newInstance(Unknown Source) ~[?:?]
flowable-rest-6.4 | at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_181]
flowable-rest-6.4 | at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_181]
flowable-rest-6.4 | at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_181]
flowable-rest-6.4 | at groovy.grape.Grape.getInstance(Grape.java:121) ~[groovy-2.4.15.jar!/:2.4.15]
flowable-rest-6.4 | at groovy.grape.Grape.grab(Grape.java:159) ~[groovy-2.4.15.jar!/:2.4.15]
flowable-rest-6.4 | at groovy.grape.GrabAnnotationTransformation.visit(GrabAnnotationTransformation.java:376) ~[groovy-2.4.15.jar!/:2.4.15]
flowable-rest-6.4 | at org.codehaus.groovy.transform.ASTTransformationVisitor$3.call(ASTTransformationVisitor.java:346) ~[groovy-2.4.15.jar!/:2.4.15]
flowable-rest-6.4 | at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:966) ~[groovy-2.4.15.jar!/:2.4.15]
flowable-rest-6.4 | at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:626) ~[groovy-2.4.15.jar!/:2.4.15]
flowable-rest-6.4 | at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:602) ~[groovy-2.4.15.jar!/:2.4.15]
flowable-rest-6.4 | at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:579) ~[groovy-2.4.15.jar!/:2.4.15]
flowable-rest-6.4 | at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:323) ~[groovy-2.4.15.jar!/:2.4.15]
flowable-rest-6.4 | at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:293) ~[groovy-2.4.15.jar!/:2.4.15]
flowable-rest-6.4 | at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:279) ~[groovy-2.4.15.jar!/:2.4.15]
flowable-rest-6.4 | at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:236) ~[groovy-2.4.15.jar!/:2.4.15]
flowable-rest-6.4 | at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.getScriptClass(GroovyScriptEngineImpl.java:335) ~[groovy-jsr223-2.5.2.jar!/:2.5.2]
flowable-rest-6.4 | at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:157) ~[groovy-jsr223-2.5.2.jar!/:2.5.2]
flowable-rest-6.4 | at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233) ~[?:1.8.0_181]
flowable-rest-6.4 | at org.flowable.common.engine.impl.scripting.ScriptingEngines.evaluate(ScriptingEngines.java:87) ~[flowable-engine-common-6.4.0.jar!/:6.4.0]
flowable-rest-6.4 | at org.flowable.common.engine.impl.scripting.ScriptingEngines.evaluate(ScriptingEngines.java:73) ~[flowable-engine-common-6.4.0.jar!/:6.4.0]
flowable-rest-6.4 | at org.flowable.engine.impl.bpmn.behavior.ScriptTaskActivityBehavior.execute(ScriptTaskActivityBehavior.java:78) ~[flowable-engine-6.4.0.jar!/:6.4.0]
flowable-rest-6.4 | at org.flowable.engine.impl.agenda.ContinueProcessOperation.executeActivityBehavior(ContinueProcessOperation.java:264) ~[flowable-engine-6.4.0.jar!/:6.4.0]
flowable-rest-6.4 | at org.flowable.engine.impl.agenda.ContinueProcessOperation.executeSynchronous(ContinueProcessOperation.java:158) ~[flowable-engine-6.4.0.jar!/:6.4.0]
flowable-rest-6.4 | at org.flowable.engine.impl.agenda.ContinueProcessOperation.continueThroughFlowNode(ContinueProcessOperation.java:113) ~[flowable-engine-6.4.0.jar!/:6.4.0]
flowable-rest-6.4 | at org.flowable.engine.impl.agenda.ContinueProcessOperation.continueThroughSequenceFlow(ContinueProcessOperation.java:311) ~[flowable-engine-6.4.0.jar!/:6.4.0]
flowable-rest-6.4 | at org.flowable.engine.impl.agenda.ContinueProcessOperation.run(ContinueProcessOperation.java:79) ~[flowable-engine-6.4.0.jar!/:6.4.0]
flowable-rest-6.4 | at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:88) ~[flowable-engine-6.4.0.jar!/:6.4.0]
flowable-rest-6.4 | at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:72) ~[flowable-engine-6.4.0.jar!/:6.4.0]
flowable-rest-6.4 | at org.flowable.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:56) ~[flowable-engine-6.4.0.jar!/:6.4.0]
flowable-rest-6.4 | at org.flowable.engine.impl.interceptor.BpmnOverrideContextInterceptor.execute(BpmnOverrideContextInterceptor.java:25) ~[flowable-engine-6.4.0.jar!/:6.4.0]
flowable-rest-6.4 | at org.flowable.common.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:53) ~[flowable-engine-common-6.4.0.jar!/:6.4.0]
flowable-rest-6.4 | at org.flowable.common.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:71) ~[flowable-engine-common-6.4.0.jar!/:6.4.0]
flowable-rest-6.4 | at org.flowable.common.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:49) ~[flowable-spring-common-6.4.0.jar!/:6.4.0]
flowable-rest-6.4 | at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
flowable-rest-6.4 | at org.flowable.common.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:46) ~[flowable-spring-common-6.4.0.jar!/:6.4.0]
flowable-rest-6.4 | at org.flowable.common.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30) ~[flowable-engine-common-6.4.0.jar!/:6.4.0]
flowable-rest-6.4 | at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56) ~[flowable-engine-common-6.4.0.jar!/:6.4.0]
flowable-rest-6.4 | at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51) ~[flowable-engine-common-6.4.0.jar!/:6.4.0]
flowable-rest-6.4 | at org.flowable.engine.impl.RuntimeServiceImpl.startProcessInstance(RuntimeServiceImpl.java:673) ~[flowable-engine-6.4.0.jar!/:6.4.0]
flowable-rest-6.4 | at org.flowable.engine.impl.runtime.ProcessInstanceBuilderImpl.start(ProcessInstanceBuilderImpl.java:146) ~[flowable-engine-6.4.0.jar!/:6.4.0]
flowable-rest-6.4 | at org.flowable.rest.service.api.runtime.process.ProcessInstanceCollectionResource.createProcessInstance(ProcessInstanceCollectionResource.java:291) ~[flowable-rest-6.4.0.jar!/:6.4.0]
flowable-rest-6.4 | at sun.reflect.GeneratedMethodAccessor494.invoke(Unknown Source) ~[?:?]
flowable-rest-6.4 | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
flowable-rest-6.4 | at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
flowable-rest-6.4 | at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209) ~[spring-web-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
flowable-rest-6.4 | at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
flowable-rest-6.4 | at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
flowable-rest-6.4 | at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:891) ~[spring-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
flowable-rest-6.4 | at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
flowable-rest-6.4 | at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
flowable-rest-6.4 | at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991) [spring-webmvc-5.0.9.RELEASE.jar!/:5.0.9.RELEASE]
flowable-rest-6.4 | … 86 more

**Comment by miriambron** [comment]
by mistake , can be deleted
