### ISSUE TITLE
NPE when starting a new process

### ISSUE THREAD

**Issue by inakihn** [flowable/flowable-engine#1520]
NPE happens on current master branch.

Steps to reproduce:

Model a simple process, with just start and end event.
![image](https://user-images.githubusercontent.com/18142467/50904181-f2b4fd00-141f-11e9-8d94-f181deab6404.png)
Start an instance of the process.

Throws this error:

> 2019-01-09 15:01:25.727 ERROR 7732 --- [io-9999-exec-10] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [/flowable-task] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
java.lang.NullPointerException: null
	at java.util.HashMap.putMapEntries(HashMap.java:501) ~[?:1.8.0_181]
	at java.util.HashMap.putAll(HashMap.java:785) ~[?:1.8.0_181]
	at org.flowable.engine.impl.runtime.ProcessInstanceBuilderImpl.startFormVariables(ProcessInstanceBuilderImpl.java:151) ~[classes/:?]
	at org.flowable.engine.impl.RuntimeServiceImpl.startProcessInstanceWithForm(RuntimeServiceImpl.java:170) 

To be able to start a new process without this error, I have used an init form in the process. That way the null pointer doesn't happen.

**Comment by dbmalkovsky** [comment]
Fixed with push with this  [PR](https://github.com/flowable/flowable-engine/commit/20466e3db83dd44921f42c39a9418639fba839f6).   Joram you beat me to the fix.  Thanks.
