### ISSUE TITLE
Flowable 6.4.1 Modeler - CMMN stage no longer accepting exit sentry

### ISSUE THREAD

**Issue by MaximeGodeau** [flowable/flowable-engine#1563]
Hello,

Since the new version of flowable (6.4.1), it is no longer possible to add an exit sentry in a stage in the flowable-modeler application.

After adding it, no application can be deployed nor the XML be downloaded.  We can see the following errors in the logs:
`2019-01-30 13:47:16.320 ERROR 1 --- [nio-8080-exec-7] o.f.u.m.s.ModelImageService              : Error creating thumbnail cmmn image 3d37391e-1f29-11e9-87c3-0242ac110002
java.lang.NullPointerException: null
        at org.flowable.cmmn.editor.json.converter.CmmnJsonConverter.createSentryParts(CmmnJsonConverter.java:530) ~[flowable-cmmn-json-converter-6.4.1.jar:6.4.1]
        at org.flowable.cmmn.editor.json.converter.CmmnJsonConverter.postProcessElements(CmmnJsonConverter.java:508) ~[flowable-cmmn-json-converter-6.4.1.jar:6.4.1]
        at org.flowable.cmmn.editor.json.converter.CmmnJsonConverter.convertToCmmnModel(CmmnJsonConverter.java:373) ~[flowable-cmmn-json-converter-6.4.1.jar:6.4.1]
        at org.flowable.cmmn.editor.json.converter.CmmnJsonConverter.convertToCmmnModel(CmmnJsonConverter.java:288) ~[flowable-cmmn-json-converter-6.4.1.jar:6.4.1]
        at org.flowable.ui.modeler.service.ModelImageService.generateCmmnThumbnailImage(ModelImageService.java:83) ~[flowable-ui-modeler-logic-6.4.1.jar:6.4.1]
        at org.flowable.ui.modeler.service.ModelImageService$$FastClassBySpringCGLIB$$6d09a974.invoke(<generated>) ~[flowable-ui-modeler-logic-6.4.1.jar:6.4.1]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.12.RELEASE.jar:5.0.12.RELEASE]`

And 
`2019-01-30 13:49:48.644 ERROR 1 --- [nio-8080-exec-3] o.f.u.m.s.ModelServiceImpl               : Could not generate CMMN model for 3d37391e-1f29-11e9-87c3-0242ac110002
org.flowable.ui.common.service.exception.InternalServerErrorException: Could not generate CMMN model
        at org.flowable.ui.modeler.service.ModelServiceImpl.getCmmnModel(ModelServiceImpl.java:641) ~[flowable-ui-modeler-logic-6.4.1.jar:6.4.1]
        at org.flowable.ui.modeler.service.ModelServiceImpl.getCmmnModel(ModelServiceImpl.java:616) ~[flowable-ui-modeler-logic-6.4.1.jar:6.4.1]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[spring-aop-5.0.12.RELEASE.jar:5.0.12.RELEASE]`

This feature is working fine in the 6.4.0.

Regards,

Maxime

**Comment by jbarrez** [comment]
Thanks for reporting! This is fixed on master: https://github.com/flowable/flowable-engine/commit/c6a5d7e2ae3bd3654f8aef40ac0a2fe58c392f15#diff-90b2fa9077a71bbfc84609c1ec543269R531
