### ISSUE TITLE
reading response of rest client through resttemplate

### ISSUE THREAD

**Issue by getkavya** [flowable/flowable-engine#1673]
java.lang.NullPointerException: null
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:889) ~[jackson-core-2.9.8.jar:2.9.8]
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2551) ~[jackson-databind-2.9.8.jar:2.9.8]
	at com.example.oauth2.client.controllers.EmployeeController.showEmployees(EmployeeController.java:60) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]

**Comment by filiphr** [comment]
@getkavya how is this linked with Flowable?

**Comment by getkavya** [comment]
Access Token Response---------<302,[WWW-Authenticate:"Basic realm="oauth2/client"", X-Content-Type-Options:"nosniff", X-XSS-Protection:"1; mode=block", Cache-Control:"no-cache, no-store, max-age=0, must-revalidate", Pragma:"no-cache", Expires:"0", X-Frame-Options:"DENY", Location:"http://localhost:8080/login", Content-Length:"0", Date:"Tue, 26 Mar 2019 07:33:11 GMT"]>
[2m2019-03-26 13:03:11.285[0;39m [31mERROR[0;39m [35m22840[0;39m [2m---[0;39m [2m[nio-8090-exec-3][0;39m [36mo.a.c.c.C.[.[.[/].[dispatcherServlet]   [0;39m [2m:[0;39m Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: (String)"<302,[WWW-Authenticate:"Basic realm="oauth2/client"", X-Content-Type-Options:"nosniff", X-XSS-Protection:"1; mode=block", Cache-Control:"no-cache, no-store, max-age=0, must-revalidate", Pragma:"no-cache", Expires:"0", X-Frame-Options:"DENY", Location:"http://localhost:8080/login", Content-Length:"0", Date:"Tue, 26 Mar 2019 07:33:11 GMT"]>"; line: 1, column: 2]

**Comment by getkavya** [comment]
it is not linked to Flowable. You can close it
