### ISSUE TITLE
ModelImageService - Error creating thumbnail

### ISSUE THREAD

**Issue by dgkm** [flowable/flowable-engine#1859]
Version: 6.5.0

> I'm getting the following exception when modeler creating a thumbnail upon saving the BPMN diagram.  Is it a known issue and/or a bug?

```2019-07-26 00:22:36.549 ERROR 1 --- [nio-8080-exec-8] o.f.u.m.s.ModelImageService              : Error creating thumbnail image 04019394-9f46-11e9-b69a-0242c0a81003
2019-07-26T00:22:36.562306377Z 
java.lang.NullPointerException: null
at sun.awt.FontConfiguration.getVersion(Unknown Source) ~[?:1.8.0_212]
at sun.awt.FontConfiguration.readFontConfigFile(Unknown Source) ~[?:1.8.0_212]
at sun.awt.FontConfiguration.init(Unknown Source) ~[?:1.8.0_212]
at sun.awt.X11FontManager.createFontConfiguration(Unknown Source) ~[?:1.8.0_212]
at sun.font.SunFontManager$2.run(Unknown Source) ~[?:1.8.0_212]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_212]
at sun.font.SunFontManager.<init>(Unknown Source) ~[?:1.8.0_212]
at sun.awt.FcFontManager.<init>(Unknown Source) ~[?:1.8.0_212]
at sun.awt.X11FontManager.<init>(Unknown Source) ~[?:1.8.0_212]
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_212]
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_212]
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_212]
at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_212]
at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_212]
at sun.font.FontManagerFactory$1.run(Unknown Source) ~[?:1.8.0_212]
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_212]
at sun.font.FontManagerFactory.getInstance(Unknown Source) ~[?:1.8.0_212]
at sun.font.SunFontManager.getInstance(Unknown Source) ~[?:1.8.0_212]
at sun.font.FontDesignMetrics.getMetrics(Unknown Source) ~[?:1.8.0_212]
at sun.java2d.SunGraphics2D.getFontMetrics(Unknown Source) ~[?:1.8.0_212]
at org.flowable.image.impl.DefaultProcessDiagramCanvas.initialize(DefaultProcessDiagramCanvas.java:219) ~[flowable-image-generator-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
at org.flowable.image.impl.DefaultProcessDiagramCanvas.<init>(DefaultProcessDiagramCanvas.java:178) ~[flowable-image-generator-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
at org.flowable.image.impl.DefaultProcessDiagramGenerator.initProcessDiagramCanvas(DefaultProcessDiagramGenerator.java:1041) ~[flowable-image-generator-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
at org.flowable.image.impl.DefaultProcessDiagramGenerator.generateProcessDiagram(DefaultProcessDiagramGenerator.java:574) ~[flowable-image-generator-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
at org.flowable.image.impl.DefaultProcessDiagramGenerator.generateImage(DefaultProcessDiagramGenerator.java:553) ~[flowable-image-generator-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
at org.flowable.image.impl.DefaultProcessDiagramGenerator.generateImage(DefaultProcessDiagramGenerator.java:560) ~[flowable-image-generator-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
at org.flowable.image.impl.DefaultProcessDiagramGenerator.generatePngImage(DefaultProcessDiagramGenerator.java:565) ~[flowable-image-generator-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
at org.flowable.ui.modeler.util.ImageGenerator.createImage(ImageGenerator.java:39) ~[flowable-ui-modeler-logic-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
at org.flowable.ui.modeler.service.ModelImageService.generateThumbnailImage(ModelImageService.java:70) ~[flowable-ui-modeler-logic-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
at org.flowable.ui.modeler.service.ModelImageService$$FastClassBySpringCGLIB$$6d09a974.invoke(<generated>) ~[flowable-ui-modeler-logic-6.5.0-SNAPSHOT.jar:6.5.0-SNAPSHOT]
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.1.7.RELEASE.jar:5.1.7.RELEASE]
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749) ~[spring-aop-5.1.7.RELEASE.jar:5.1.7.RELEASE]```

**Comment by unamanic** [comment]
Looks like it's related to the switch to Alpine base images and this issue with AdoptOpenJDK:

https://github.com/AdoptOpenJDK/openjdk-build/issues/693

**Comment by dgkm** [comment]
@unamanic Spot on and perfect fix.  

> No more exception and the thumbnail is getting generated with the new build images using the changes to the Dockerfile in PR #1860 .

Thank you.
