### ISSUE TITLE
Custom Mybatis  Mapper Error

### ISSUE THREAD

**Issue by heywakeup** [flowable/flowable-engine#1872]
My Mapper like this:

@Mapper
@Repository
public interface FlowableMapper {

    /**
     * Update historic activity instance delete reason int.
     *
     * @param id     the id
     * @param reason the reason
     * @return the int
     */
    @Update("UPDATE ACT_HI_ACTINST SET DELETE_REASON_ =  #{reason} WHERE ID_ =  #{id}")
    Integer updateHistoricActivityInstanceDeleteReason(@Param("id") String id,
                                                       @Param("reason") String reason);
}

And config file like this:

flowable:
  customMybatisMappers:
    - com.sy.dic.process.dao.FlowableMapper

And Use the mapper like this:

processEngine.getManagementService()
                        .executeCustomSql(
                                new AbstractCustomSqlExecution<FlowableMapper, Integer>(FlowableMapper.class) {
                                    @Override
                                    public Integer execute(FlowableMapper flowableMapper) {
                                        return flowableMapper
                                                .updateHistoricActivityInstanceDeleteReason(historicActivityInstance.getId(),
                                                        "Change activity to " + taskDefId);
                                    }
                                }));

the thow exception .
org.apache.ibatis.binding.BindingException: Type interface com.sy.dic.process.dao.FlowableMapper is not known to the MapperRegistry.
	at org.apache.ibatis.binding.MapperRegistry.getMapper(MapperRegistry.java:47)
	at org.apache.ibatis.session.Configuration.getMapper(Configuration.java:763)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.getMapper(DefaultSqlSession.java:291)
	at org.flowable.engine.impl.cmd.ExecuteCustomSqlCmd.execute(ExecuteCustomSqlCmd.java:35)
	at org.flowable.engine.impl.interceptor.CommandInvoker$1.run(CommandInvoker.java:51)
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:93)
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:72)
	at org.flowable.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:56)
	at org.flowable.engine.impl.interceptor.BpmnOverrideContextInterceptor.execute(BpmnOverrideContextInterceptor.java:25)
	at org.flowable.common.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:53)
	at org.flowable.common.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:72)
	at org.flowable.common.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:51)
	at org.flowable.common.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30)
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56)
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51)
	at org.flowable.engine.impl.ManagementServiceImpl.executeCustomSql(ManagementServiceImpl.java:282)
	at com.sy.dic.service.impl.CommonProcessServiceImpl.lambda$doBackTo$3(CommonProcessServiceImpl.java:316)

**Comment by tijsrademakers** [comment]
Hi,

It looks like your Mapper class is not made available to the MyBatis configuration. Are you sure the FlowableMapper is scanned and added to the MyBatis configuration?

**Comment by tijsrademakers** [comment]
Closing the issue due to no response, please reopen when needed or use the Flowable forum for more questions.
