### ISSUE TITLE
i find a bug org.apache.ibatis.ognl.NoSuchPropertyException: org.flowable.task.service.impl.TaskQueryImpl.withoutDeleteReason

### ISSUE THREAD

**Issue by pengzhiheng** [flowable/flowable-engine#1891]
i find a bug
when i use 
List list3 = taskService.createTaskQuery().or().taskCandidateGroup("pengzhiheng13222").taskAssignee("pengzhiheng13222").endOr().list();
it will error ,error is :
org.apache.ibatis.exceptions.PersistenceException: 
### Cause: org.apache.ibatis.builder.BuilderException: Error evaluating expression 'orQueryObject.withoutDeleteReason'. Cause: org.apache.ibatis.ognl.NoSuchPropertyException: org.flowable.task.service.impl.TaskQueryImpl.withoutDeleteReason
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at org.flowable.common.engine.impl.db.DbSqlSession.selectListWithRawParameter(DbSqlSession.java:202)
	at org.flowable.common.engine.impl.db.DbSqlSession.selectListWithRawParameter(DbSqlSession.java:196)
	at org.flowable.common.engine.impl.db.DbSqlSession.selectList(DbSqlSession.java:157)
	at org.flowable.task.service.impl.persistence.entity.data.impl.MybatisTaskDataManager.findTasksByQueryCriteria(MybatisTaskDataManager.java:102)
	at org.flowable.task.service.impl.persistence.entity.TaskEntityManagerImpl.findTasksByQueryCriteria(TaskEntityManagerImpl.java:181)
	at org.flowable.task.service.impl.TaskQueryImpl.executeList(TaskQueryImpl.java:1640)
	at org.flowable.common.engine.impl.query.AbstractQuery.execute(AbstractQuery.java:153)
	at org.flowable.engine.impl.interceptor.CommandInvoker$1.run(CommandInvoker.java:51)
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:93)
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:72)
	at org.flowable.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:56)
	at org.flowable.engine.impl.interceptor.BpmnOverrideContextInterceptor.execute(BpmnOverrideContextInterceptor.java:25)
	at org.flowable.common.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:53)
	at org.flowable.common.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:72)
	at org.flowable.common.spring.SpringTransactionInterceptor.lambda$execute$0(SpringTransactionInterceptor.java:56)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.flowable.common.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:56)
	at org.flowable.common.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30)
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56)
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51)
	at org.flowable.common.engine.impl.query.AbstractQuery.list(AbstractQuery.java:117)
	at org.flowable.task.service.impl.TaskQueryImpl.list(TaskQueryImpl.java:1993)
	at com.hellobike.bos.workflow.AppTest3.testMail(AppTest3.java:112)
	at com.hellobike.bos.workflow.AppTest3.main(AppTest3.java:83)
Caused by: org.apache.ibatis.builder.BuilderException: Error evaluating expression 'orQueryObject.withoutDeleteReason'. Cause: org.apache.ibatis.ognl.NoSuchPropertyException: org.flowable.task.service.impl.TaskQueryImpl.withoutDeleteReason
	at org.apache.ibatis.scripting.xmltags.OgnlCache.getValue(OgnlCache.java:46)
	at org.apache.ibatis.scripting.xmltags.ExpressionEvaluator.evaluateBoolean(ExpressionEvaluator.java:32)
	at org.apache.ibatis.scripting.xmltags.IfSqlNode.apply(IfSqlNode.java:34)
	at org.apache.ibatis.scripting.xmltags.MixedSqlNode.apply(MixedSqlNode.java:33)
	at org.apache.ibatis.scripting.xmltags.TrimSqlNode.apply(TrimSqlNode.java:55)
	at org.apache.ibatis.scripting.xmltags.MixedSqlNode.apply(MixedSqlNode.java:33)
	at org.apache.ibatis.scripting.xmltags.ForEachSqlNode.apply(ForEachSqlNode.java:80)
	at org.apache.ibatis.scripting.xmltags.MixedSqlNode.apply(MixedSqlNode.java:33)
	at org.apache.ibatis.scripting.xmltags.TrimSqlNode.apply(TrimSqlNode.java:55)
	at org.apache.ibatis.scripting.xmltags.MixedSqlNode.apply(MixedSqlNode.java:33)
	at org.apache.ibatis.scripting.xmltags.DynamicSqlSource.getBoundSql(DynamicSqlSource.java:41)
	at org.apache.ibatis.mapping.MappedStatement.getBoundSql(MappedStatement.java:292)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:81)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	... 25 more
Caused by: org.apache.ibatis.ognl.NoSuchPropertyException: org.flowable.task.service.impl.TaskQueryImpl.withoutDeleteReason
	at org.apache.ibatis.ognl.ObjectPropertyAccessor.getProperty(ObjectPropertyAccessor.java:151)
	at org.apache.ibatis.ognl.OgnlRuntime.getProperty(OgnlRuntime.java:2685)
	at org.apache.ibatis.ognl.ASTProperty.getValueBody(ASTProperty.java:114)
	at org.apache.ibatis.ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at org.apache.ibatis.ognl.SimpleNode.getValue(SimpleNode.java:258)
	at org.apache.ibatis.ognl.ASTChain.getValueBody(ASTChain.java:141)
	at org.apache.ibatis.ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at org.apache.ibatis.ognl.SimpleNode.getValue(SimpleNode.java:258)
	at org.apache.ibatis.ognl.Ognl.getValue(Ognl.java:470)
	at org.apache.ibatis.ognl.Ognl.getValue(Ognl.java:434)
	at org.apache.ibatis.scripting.xmltags.OgnlCache.getValue(OgnlCache.java:44)
	... 38 more

**Comment by tijsrademakers** [comment]
Which version of Flowable are you using? How are you running this query? With a Spring Boot application or something else?

**Comment by pengzhiheng** [comment]
> Which version of Flowable are you using? How are you running this query? With a Spring Boot application or something else?

i am use it with springboot ,the dependecy version is 

<dependency>
            <groupId>org.flowable</groupId>
            <artifactId>flowable-spring-boot-starter-rest</artifactId>
            <version>6.4.2</version>
        </dependency>

**Comment by tijsrademakers** [comment]
The issue should be fixed on master now.

**Comment by imEzreal** [comment]
大佬 怎么解决

**Comment by unesco3187** [comment]
Try to solve it by upgrading mybatis version
