### ISSUE TITLE
 I found a bug, Unknown column 'RES.DELETE_REASON_' in 'where clause' when taskService is using or ()

### ISSUE THREAD

**Issue by unesco3187** [flowable/flowable-engine#2331]
**use spring in the project，The jar package introduced by maven is as follows**
<dependency>
    <groupId>org.flowable</groupId>
    <artifactId>flowable-engine</artifactId>
    <version>6.4.2</version>
</dependency>
<dependency>
    <groupId>org.flowable</groupId>
    <artifactId>flowable-spring</artifactId>
    <version>6.4.2</version>
</dependency>

**java code:**

taskService.createTaskQuery().includeProcessVariables()
                .or()
                .taskVariableValueEquals("type", "firstAudit")
                .taskVariableValueEquals("type", "secondAudit")
                .endOr().list();

**error msg:**

org.apache.ibatis.exceptions.PersistenceException: 
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'RES.DELETE_REASON_' in 'where clause'

	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at org.flowable.common.engine.impl.db.DbSqlSession.selectListWithRawParameter(DbSqlSession.java:202)
	at org.flowable.common.engine.impl.db.DbSqlSession.selectListWithRawParameterNoCacheCheck(DbSqlSession.java:178)
	at org.flowable.task.service.impl.persistence.entity.data.impl.MybatisTaskDataManager.findTasksWithRelatedEntitiesByQueryCriteria(MybatisTaskDataManager.java:123)
	at org.flowable.task.service.impl.persistence.entity.TaskEntityManagerImpl.findTasksWithRelatedEntitiesByQueryCriteria(TaskEntityManagerImpl.java:186)
	at org.flowable.task.service.impl.TaskQueryImpl.executeList(TaskQueryImpl.java:1638)
	at org.flowable.common.engine.impl.query.AbstractQuery.execute(AbstractQuery.java:153)
	at org.flowable.engine.impl.interceptor.CommandInvoker$1.run(CommandInvoker.java:51)
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:93)
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:72)
	at org.flowable.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:56)
	at org.flowable.engine.impl.interceptor.BpmnOverrideContextInterceptor.execute(BpmnOverrideContextInterceptor.java:25)
	at org.flowable.common.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:53)
	at org.flowable.common.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:72)
	at org.flowable.common.spring.SpringTransactionInterceptor.lambda$execute$0(SpringTransactionInterceptor.java:56)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.flowable.common.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:56)
	at org.flowable.common.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:35)
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56)
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51)
	at org.flowable.common.engine.impl.query.AbstractQuery.list(AbstractQuery.java:117)
	at org.flowable.task.service.impl.TaskQueryImpl.list(TaskQueryImpl.java:1993)
	at com.wisedu.campuses.flow.flowTest.query(flowTest.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:252)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'RES.DELETE_REASON_' in 'where clause'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:939)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1192)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.PreparedStatementLogger.invoke(PreparedStatementLogger.java:59)
	at com.sun.proxy.$Proxy107.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:63)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	... 51 more

**Comment by tijsrademakers** [comment]
Hi,
Thanks for reporting the issue, but this part of the Task query is only reached when the taskWithoutDeleteReason option is used on the task query. Can you attach the code of the flowTest class to see what is triggering this exactly?
Thanks

**Comment by unesco3187** [comment]
Hi,
This is my flowTest class, not using taskWithoutDeleteReason

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = "classpath:spring-api-test.xml")
public class flowTest {

    @Autowired
    private TaskService taskService;


    @Test
    public void query(){
        taskService.createTaskQuery().includeProcessVariables()
                .or()
                .taskVariableValueEquals("type", "firstAudit")
                .taskVariableValueEquals("type", "secondAudit")
                .list();
    }
}

**Comment by unesco3187** [comment]
> Hi,
> Thanks for reporting the issue, but this part of the Task query is only reached when the taskWithoutDeleteReason option is used on the task query. Can you attach the code of the flowTest class to see what is triggering this exactly?
> Thanks

This is my flowTest class, not using taskWithoutDeleteReason

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = "classpath:spring-api-test.xml")
public class flowTest {

@Autowired
private TaskService taskService;


@Test
public void query(){
    taskService.createTaskQuery().includeProcessVariables()
            .or()
            .taskVariableValueEquals("type", "firstAudit")
            .taskVariableValueEquals("type", "secondAudit")
            .list();
}
}

**Comment by unesco3187** [comment]
debug source code found，
When executing .list (), the following code will be executed finally
![image](https://user-images.githubusercontent.com/18564706/81479475-0d86c400-9256-11ea-8046-8a5345679485.png)
![image](https://user-images.githubusercontent.com/18564706/81479531-60f91200-9256-11ea-89a4-0b84316ad881.png)
![image](https://user-images.githubusercontent.com/18564706/81479544-6fdfc480-9256-11ea-9991-6875b07b1a19.png)

But i don't know why?
Thanks

**Comment by unesco3187** [comment]
![image](https://user-images.githubusercontent.com/18564706/81506296-e4366880-9327-11ea-9730-3cb37fa8525f.png)

After executing this.rootSqlNode.apply (context); after the method is called withoutDeleteReason ()

**Comment by unesco3187** [comment]
> Hi,
> Thanks for reporting the issue, but this part of the Task query is only reached when the taskWithoutDeleteReason option is used on the task query. Can you attach the code of the flowTest class to see what is triggering this exactly?
> Thanks

Hi,
Solved the problem by upgrading mybatis version and mybatis-spring version
Thanks
