### ISSUE TITLE
DmnEngine not work

### ISSUE THREAD

**Issue by jizhengdaling** [flowable/flowable-engine#255]
# hi，
My flowable.cfg.xml:
`<bean id="dmnEngineConfiguration" class="org.flowable.dmn.engine.impl.cfg.StandaloneDmnEngineConfiguration">
   <property name="jdbcUrl" value="jdbc:mysql://127.0.0.1:3306/flowable6" />
    <property name="jdbcDriver" value="com.mysql.jdbc.Driver" />
    <property name="jdbcUsername" value="root" />
    <property name="jdbcPassword" value="" />
</bean>`
I build DmnEngine like this:
` DmnEngineConfiguration dmnEngineConfiguration = DmnEngineConfiguration.createDmnEngineConfigurationFromInputStream(in);
		 dmnEngine = dmnEngineConfiguration.buildDmnEngine();
		 repositoryService=dmnEngine.getDmnRepositoryService();`

and then i use this code:
`@Test
	public void deploySingleDecision() {

		dmnRepositoryService
				.createDeployment()
				.name("secondDeployment")
				.addClasspathResource(
						"com/shareniu/flowablestudy/ch3/multiple_conclusions.dmn")
				.tenantId("testTenant").deploy();
	}`

its's wrong 
org.flowable.dmn.xml.exception.DmnXMLException: cvc-elt.1: 找不到元素 'definitions' 的声明。
	at org.flowable.dmn.xml.converter.DmnXMLConverter.convertToDmnModel(DmnXMLConverter.java:161) ~[flowable-dmn-xml-converter-6.0.0.jar:6.0.0]
	at org.flowable.dmn.engine.impl.parser.DmnParse.execute(DmnParse.java:80) ~[flowable-dmn-engine-6.0.0.jar:6.0.0]
	at org.flowable.dmn.engine.impl.deployer.ParsedDeploymentBuilder.createDmnParseFromResource(ParsedDeploymentBuilder.java:89) ~[flowable-dmn-engine-6.0.0.jar:6.0.0]

## multiple_conclusions.dmn 

`<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/DMN/20151130" id="simple" name="Simple" namespace="http://activiti.org/dmn">
    <decision id="decision" name="Simple decision">
        <decisionTable id="decisionTable">
          <input>
            <inputExpression id="input1" typeRef="number">
                <text>input1</text>
            </inputExpression>
          </input>
          <output id="output1" label="Output 1" name="output1" typeRef="string" />
          <output id="output2" label="Output 2" name="output2" typeRef="number" />
          <rule>
            <inputEntry id="inputEntry1">
                <text><![CDATA[> 10]]></text>
            </inputEntry>
            <outputEntry id="outputEntry1_1">
                <text>'test'</text>
            </outputEntry>
            <outputEntry id="outputEntry2_1">
                <text>1</text>
            </outputEntry>
          </rule>
          <rule>
            <inputEntry id="inputEntry2">
                <text><![CDATA[< 10]]></text>
            </inputEntry>
            <outputEntry id="outputEntry1_2">
                <text>'test2'</text>
            </outputEntry>
            <outputEntry id="outputEntry2_2">
                <text>2</text>
            </outputEntry>
          </rule>
          <rule>
            <inputEntry id="inputEntry3">
                <text><![CDATA[== 10]]></text>
            </inputEntry>
            <outputEntry id="outputEntry1_3">
                <text>'test3'</text>
            </outputEntry>
            <outputEntry id="outputEntry2_3">
                <text>3</text>
            </outputEntry>
          </rule>
        </decisionTable>
    </decision>
</definitions>`

**Comment by tijsrademakers** [comment]
The namespace should be http://www.omg.org/spec/DMN/20151101. And the config file should be flowable.dmn.cfg.xml if you want it to be picked up automatically. But it could be that you are loading it directly from the file reference (that code is not included in the issue description).

**Comment by ouyida3** [comment]
@tijsrademakers ,hi, now when I visit http://www.omg.org/spec/DMN/20151101 , get 404 error.
Should I change it into http://www.omg.org/spec/DMN/20151101/dmn.xsd?

I get an exception cvc-elt.1 when I use DMN.
So I change the code:`flowable-engine/modules/flowable-dmn-xml-converter/src/main/resources/org/flowable/impl/dmn/parser/dmn.xsd`, and `mvn install` a new jar.
With this new jar, the exception disappeared.

Exception details:
```
ERROR:  'org.xml.sax.SAXParseException; lineNumber: 3; columnNumber: 4; cvc-elt.1: 找不到元素 'definitions' 的声明。'
2019-04-10 10:03:12.869 [http-nio-8830-exec-1] ERROR o.flowable.common.engine.impl.interceptor.CommandContext -
				Error while closing command context
org.flowable.dmn.xml.exception.DmnXMLException: javax.xml.stream.XMLStreamException: org.xml.sax.SAXParseException; lineNumber: 3; columnNumber: 4; cvc-elt.1: 找不到元素 'definitions' 的声明。
	at org.flowable.dmn.xml.converter.DmnXMLConverter.convertToDmnModel(DmnXMLConverter.java:199)
	at org.flowable.dmn.engine.impl.parser.DmnParse.execute(DmnParse.java:80)
	at org.flowable.dmn.engine.impl.deployer.ParsedDeploymentBuilder.createDmnParseFromResource(ParsedDeploymentBuilder.java:87)
	at org.flowable.dmn.engine.impl.deployer.ParsedDeploymentBuilder.build(ParsedDeploymentBuilder.java:53)
	at org.flowable.dmn.engine.impl.deployer.DmnDeployer.deploy(DmnDeployer.java:47)
	at org.flowable.dmn.engine.impl.persistence.deploy.DeploymentManager.deploy(DeploymentManager.java:55)
	at org.flowable.dmn.engine.impl.cmd.DeployCmd.execute(DeployCmd.java:102)
	at org.flowable.dmn.engine.impl.cmd.DeployCmd.execute(DeployCmd.java:38)
	at org.flowable.common.engine.impl.interceptor.DefaultCommandInvoker.execute(DefaultCommandInvoker.java:22)
	at org.flowable.common.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:53)
	at org.flowable.common.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:71)
	at org.flowable.dmn.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:49)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.flowable.dmn.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:46)
	at org.flowable.common.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30)
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56)
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51)
	at org.flowable.dmn.engine.impl.DmnRepositoryServiceImpl.deploy(DmnRepositoryServiceImpl.java:60)
	at org.flowable.dmn.engine.impl.repository.DmnDeploymentBuilderImpl.deploy(DmnDeploymentBuilderImpl.java:167)
	at com.asiainfo.cloud.service.TimerRedPacketService.service(TimerRedPacketService.java:48)
	at com.asiainfo.cloud.controller.TimerRedPacketController.timerRedPacket(TimerRedPacketController.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.cloud.sleuth.instrument.web.ExceptionLoggingFilter.doFilter(ExceptionLoggingFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at brave.servlet.TracingFilter.doFilter(TracingFilter.java:86)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:834)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.xml.sax.SAXException: javax.xml.stream.XMLStreamException: org.xml.sax.SAXParseException; lineNumber: 3; columnNumber: 4; cvc-elt.1: 找不到元素 'definitions' 的声明。
	at com.sun.org.apache.xerces.internal.jaxp.validation.StAXValidatorHelper.validate(StAXValidatorHelper.java:109)
	at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorImpl.validate(ValidatorImpl.java:123)
	at javax.xml.validation.Validator.validate(Validator.java:124)
	at org.flowable.dmn.xml.converter.DmnXMLConverter.validateModel(DmnXMLConverter.java:116)
	at org.flowable.dmn.xml.converter.DmnXMLConverter.convertToDmnModel(DmnXMLConverter.java:192)
	... 92 common frames omitted
Caused by: javax.xml.transform.TransformerException: javax.xml.stream.XMLStreamException: org.xml.sax.SAXParseException; lineNumber: 3; columnNumber: 4; cvc-elt.1: 找不到元素 'definitions' 的声明。
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:749)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:351)
	at com.sun.org.apache.xerces.internal.jaxp.validation.StAXValidatorHelper.validate(StAXValidatorHelper.java:105)
	... 96 common frames omitted
Caused by: javax.xml.stream.XMLStreamException: org.xml.sax.SAXParseException; lineNumber: 3; columnNumber: 4; cvc-elt.1: 找不到元素 'definitions' 的声明。
	at com.sun.org.apache.xalan.internal.xsltc.trax.StAXStream2SAX.handleCharacters(StAXStream2SAX.java:247)
	at com.sun.org.apache.xalan.internal.xsltc.trax.StAXStream2SAX.bridge(StAXStream2SAX.java:152)
	at com.sun.org.apache.xalan.internal.xsltc.trax.StAXStream2SAX.parse(StAXStream2SAX.java:101)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transformIdentity(TransformerImpl.java:688)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:737)
	... 98 common frames omitted
Caused by: org.xml.sax.SAXParseException: cvc-elt.1: 找不到元素 'definitions' 的声明。
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1900)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:740)
	at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorHandlerImpl.startElement(ValidatorHandlerImpl.java:570)
	at com.sun.org.apache.xml.internal.serializer.ToXMLSAXHandler.closeStartTag(ToXMLSAXHandler.java:208)
	at com.sun.org.apache.xml.internal.serializer.ToXMLSAXHandler.characters(ToXMLSAXHandler.java:528)
	at com.sun.org.apache.xalan.internal.xsltc.trax.StAXStream2SAX.handleCharacters(StAXStream2SAX.java:245)
	... 102 common frames omitted
```
