### ISSUE TITLE
Thread[flowable-event-change-detector-1] keeping write log and cannot stop it

### ISSUE THREAD

**Issue by iambiglee** [flowable/flowable-engine#2558]
**Describe the bug**
I release a flowable-springboot in my Linux server, and catalina keeping writing log as below. It repeats once every millisecond, and that cause my catalina log near 1000M a day

```
25-Aug-2020 09:38:14.866 INFO [flowable-event-change-detector-1] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [org.flowable.common.spring.SpringTransactionInterceptor]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [org.flowable.common.spring.SpringTransactionInterceptor]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
		at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1385)
		at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1373)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1226)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188)
		at ch.qos.logback.classic.spi.PackagingDataCalculator.loadClass(PackagingDataCalculator.java:204)
		at ch.qos.logback.classic.spi.PackagingDataCalculator.bestEffortLoadClass(PackagingDataCalculator.java:222)
		at ch.qos.logback.classic.spi.PackagingDataCalculator.computeBySTEP(PackagingDataCalculator.java:135)
		at ch.qos.logback.classic.spi.PackagingDataCalculator.populateUncommonFrames(PackagingDataCalculator.java:111)
		at ch.qos.logback.classic.spi.PackagingDataCalculator.populateFrames(PackagingDataCalculator.java:104)
		at ch.qos.logback.classic.spi.PackagingDataCalculator.calculate(PackagingDataCalculator.java:58)
		at ch.qos.logback.classic.spi.ThrowableProxy.calculatePackagingData(ThrowableProxy.java:142)
		at ch.qos.logback.classic.spi.LoggingEvent.<init>(LoggingEvent.java:122)
		at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:419)
		at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
		at ch.qos.logback.classic.Logger.error(Logger.java:538)
		at org.flowable.eventregistry.impl.management.EventRegistryChangeDetectionRunnable.run(EventRegistryChangeDetectionRunnable.java:37)
		at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
```

**Expected behavior**
I want to know why this happend and how to fixed it

**Code**

**Additional context**
[Version]Springboot-flowable-start;6.5.
We packaged him into a jar and released it on a tomcat together with other businesses code

**Comment by iambiglee** [comment]
Is that because I started 2 tomcat in one server?

**Comment by iambiglee** [comment]
it is about thread "flowable-event-change-detector-1" is not daemon thread, and it will cost tomcat is close ,but the thread is still alive, and unfortunately ,  it is a schedule thread and it runs  every 60s. 
So, if you close the tomcat with tomcat shutdown.sh  thread "flowable-event-change-detector-1" may still alive, and it will cause write this logs
