### ISSUE TITLE
flowable upgrade from 4.2 to 5.0

### ISSUE THREAD

**Issue by GauCho89** [flowable/flowable-engine#2569]
**Describe the bug**
After upgrade of flowable from 4.2 to 5.0 and running the upgrade SQL script flowable-task and flowable-rest stops.

**Expected behavior**
Flowable-task and flowable-rest should be up and running after the upgrade.

**Code**
26abc675dff7ac54e43e but is now: 8:d7c4da9276bcfffbfb0ebfb25e3f7b05
        at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:291) ~[liquibase-core-3.8.0.jar:?]
        at liquibase.Liquibase.update(Liquibase.java:198) ~[liquibase-core-3.8.0.jar:?]
        at liquibase.Liquibase.update(Liquibase.java:179) ~[liquibase-core-3.8.0.jar:?]
        at liquibase.Liquibase.update(Liquibase.java:175) ~[liquibase-core-3.8.0.jar:?]
        at liquibase.Liquibase.update(Liquibase.java:168) ~[liquibase-core-3.8.0.jar:?]
        Caused by: liquibase.exception.ValidationFailedException: Validation Failed:
          org/flowable/cmmn/db/liquibase/flowable-cmmn-db-changelog.xml::8::flowable was: 7:d168de628476556968549f4a355baacb but is now: 8:e8c2eb1ce28bc301efe07e0e29757781
          org/flowable/cmmn/db/liquibase/flowable-cmmn-db-changelog.xml::9::flowable was: 7:20048a5d52039eaabb32dbb30240fc08 but is now: 8:4cb4782b9bdec5ced2a64c525aa7b3a0
          org/flowable/cmmn/db/liquibase/flowable-cmmn-db-changelog.xml::10::flowable was: 7:e20ea59573dc2a33bbf72043ea09ea4d but is now: 8:341c16be247f5d17badc9809da8691f9
          org/flowable/cmmn/db/liquibase/flowable-cmmn-db-changelog.xml::11::flowable was: 7:21c7a61ad7fb26abc675dff7ac54e43e but is now: 8:d7c4da9276bcfffbfb0ebfb25e3f7b05
                at liquibase.changelog.DatabaseChangeLog.validate(DatabaseChangeLog.java:291)
                at liquibase.Liquibase.update(Liquibase.java:198)
                at liquibase.Liquibase.update(Liquibase.java:179)
                at liquibase.Liquibase.update(Liquibase.java:175)
                at liquibase.Liquibase.update(Liquibase.java:168)
Caused by: liquibase.exception.ValidationFailedException: Validation Failed:

**Additional context**
the liquibase is having issues with the checksum MD5SUM.

2020-09-03 12:03:42.130 WARN 1977 — [o2-443-exec-131] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name ‘servletEndpointRegistrar’ defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/web/ServletEndpointManagementContextConfiguration$WebMvcServletEndpointManagementContextConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar]: Factory method ‘servletEndpointRegistrar’ threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name ‘processEngineEndpoint’ defined in class path resource [org/flowable/spring/boot/EndpointAutoConfiguration.class]: Unsatisfied dependency expressed through method ‘processEngineEndpoint’ parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name ‘processEngine’ defined in class path resource [org/flowable/spring/boot/ProcessEngineServicesAutoConfiguration$AlreadyInitializedAppEngineConfiguration.class]: Unsatisfied dependency expressed through method ‘processEngine’ parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name ‘flowableAppEngine’: FactoryBean threw exception on object creation; nested exception is org.flowable.common.engine.api.FlowableException: Error initialising eventregistry data model

2020-09-03 12:03:42.132 INFO 1977 — [o2-443-exec-131] o.s.s.c.ThreadPoolTaskExecutor : Shutting down ExecutorService ‘applicationTaskExecutor’

2020-09-03 12:03:42.132 INFO 1977 — [o2-443-exec-131] c.z.h.HikariDataSource : flowable-rest - Shutdown initiated…

2020-09-03 12:03:42.147 INFO 1977 — [o2-443-exec-131] c.z.h.HikariDataSource : flowable-rest - Shutdown completed.

*********************************************************************************************************************

ACT_CMMN_DATABASECHANGELOG and FLW_EV_DATABASECHANGELOG, already had an entry with a different checksum (MD5SUM).

Also, the create/alter statements mentioned in the file flowable.mysql.upgradestep.6.4.2.to.6.5.0.all.sql doesn’t work as those tables/columns are already present.

Below is the flowable.mysql.upgradestep.6.4.2.to.6.5.0.all.sql file entries.

update ACT_GE_PROPERTY set VALUE_ = ‘6.5.0.6’ where NAME_ = ‘common.schema.version’;

update ACT_GE_PROPERTY set VALUE_ = ‘6.5.0.6’ where NAME_ = ‘entitylink.schema.version’;

alter table ACT_HI_IDENTITYLINK add column SUB_SCOPE_ID_ varchar(255);

create index ACT_IDX_HI_IDENT_LNK_SUB_SCOPE on ACT_HI_IDENTITYLINK(SUB_SCOPE_ID_, SCOPE_TYPE_);

alter table ACT_RU_IDENTITYLINK add column SUB_SCOPE_ID_ varchar(255);

create index ACT_IDX_IDENT_LNK_SUB_SCOPE on ACT_RU_IDENTITYLINK(SUB_SCOPE_ID_, SCOPE_TYPE_);

update ACT_GE_PROPERTY set VALUE_ = ‘6.5.0.6’ where NAME_ = ‘identitylink.schema.version’;

update ACT_GE_PROPERTY set VALUE_ = ‘6.5.0.6’ where NAME_ = ‘job.schema.version’;

create table FLW_RU_BATCH (
ID_ varchar(64) not null,
REV_ integer,
TYPE_ varchar(64) not null,
SEARCH_KEY_ varchar(255),
SEARCH_KEY2_ varchar(255),
CREATE_TIME_ datetime(3) not null,
COMPLETE_TIME_ datetime(3),
STATUS_ varchar(255),
BATCH_DOC_ID_ varchar(64),
TENANT_ID_ varchar(255) default ‘’,
primary key (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;

create table FLW_RU_BATCH_PART (
ID_ varchar(64) not null,
REV_ integer,
BATCH_ID_ varchar(64),
TYPE_ varchar(64) not null,
SCOPE_ID_ varchar(64),
SUB_SCOPE_ID_ varchar(64),
SCOPE_TYPE_ varchar(64),
SEARCH_KEY_ varchar(255),
SEARCH_KEY2_ varchar(255),
CREATE_TIME_ datetime(3) not null,
COMPLETE_TIME_ datetime(3),
STATUS_ varchar(255),
RESULT_DOC_ID_ varchar(64),
TENANT_ID_ varchar(255) default ‘’,
primary key (ID_)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_bin;

create index FLW_IDX_BATCH_PART on FLW_RU_BATCH_PART(BATCH_ID_);

alter table FLW_RU_BATCH_PART
add constraint FLW_FK_BATCH_PART_PARENT
foreign key (BATCH_ID_)
references FLW_RU_BATCH (ID_);

insert into ACT_GE_PROPERTY values (‘batch.schema.version’, ‘6.5.0.6’, 1);

alter table ACT_HI_TASKINST add column PROPAGATED_STAGE_INST_ID_ varchar(255);

alter table ACT_RU_TASK add column PROPAGATED_STAGE_INST_ID_ varchar(255);

update ACT_GE_PROPERTY set VALUE_ = ‘6.5.0.6’ where NAME_ = ‘task.schema.version’;

update ACT_GE_PROPERTY set VALUE_ = ‘6.5.0.6’ where NAME_ = ‘variable.schema.version’;

update ACT_GE_PROPERTY set VALUE_ = ‘6.5.0.6’ where NAME_ = ‘eventsubscription.schema.version’;

alter table ACT_RU_EXECUTION add column REFERENCE_ID_ varchar(255);
alter table ACT_RU_EXECUTION add column REFERENCE_TYPE_ varchar(255);

alter table ACT_RU_EXECUTION add column PROPAGATED_STAGE_INST_ID_ varchar(255);

alter table ACT_HI_PROCINST add column REFERENCE_ID_ varchar(255);
alter table ACT_HI_PROCINST add column REFERENCE_TYPE_ varchar(255);

update ACT_GE_PROPERTY set VALUE_ = ‘6.5.0.6’ where NAME_ = ‘schema.version’;
update ACT_ID_PROPERTY set VALUE_ = ‘6.5.0.6’ where NAME_ = ‘schema.version’;

UPDATE ACT_APP_DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = ‘192.168.10.1 (192.168.10.1)’, LOCKGRANTE
D = ‘2020-01-22 08:26:43.187’ WHERE ID = 1 AND LOCKED = 0;

UPDATE ACT_APP_DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;

UPDATE ACT_CMMN_DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = ‘192.168.10.1 (192.168.10.1)’, LOCKGRANT
ED = ‘2020-01-22 08:26:43.977’ WHERE ID = 1 AND LOCKED = 0;

ALTER TABLE ACT_CMMN_HI_PLAN_ITEM_INST ADD SHOW_IN_OVERVIEW_ BIT(1) NULL;

INSERT INTO ACT_CMMN_DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRI
PTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES (‘8’, ‘flowable’, ‘org/flow
able/cmmn/db/liquibase/flowable-cmmn-db-changelog.xml’, NOW(), 8, ‘7:d168de628476556968549f4a355baacb’, ’
addColumn tableName=ACT_CMMN_HI_PLAN_ITEM_INST’, ‘’, ‘EXECUTED’, NULL, NULL, ‘3.5.3’, ‘9678004051’);

ALTER TABLE ACT_CMMN_RU_PLAN_ITEM_INST ADD EXTRA_VALUE_ VARCHAR(255) NULL;

ALTER TABLE ACT_CMMN_HI_PLAN_ITEM_INST ADD EXTRA_VALUE_ VARCHAR(255) NULL;

INSERT INTO ACT_CMMN_DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRI
PTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES (‘9’, ‘flowable’, ‘org/flow
able/cmmn/db/liquibase/flowable-cmmn-db-changelog.xml’, NOW(), 9, ‘7:20048a5d52039eaabb32dbb30240fc08’, ’
addColumn tableName=ACT_CMMN_RU_PLAN_ITEM_INST; addColumn tableName=ACT_CMMN_HI_PLAN_ITEM_INST’, ‘’, ‘EXE
CUTED’, NULL, NULL, ‘3.5.3’, ‘9678004051’);

ALTER TABLE ACT_CMMN_RU_CASE_INST ADD REFERENCE_ID_ VARCHAR(255) NULL;

ALTER TABLE ACT_CMMN_RU_CASE_INST ADD REFERENCE_TYPE_ VARCHAR(255) NULL;

CREATE INDEX ACT_IDX_CASE_INST_REF_ID_ ON ACT_CMMN_RU_CASE_INST(REFERENCE_ID_);

ALTER TABLE ACT_CMMN_HI_CASE_INST ADD REFERENCE_ID_ VARCHAR(255) NULL;

ALTER TABLE ACT_CMMN_HI_CASE_INST ADD REFERENCE_TYPE_ VARCHAR(255) NULL;

INSERT INTO ACT_CMMN_DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRI
PTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES (‘10’, ‘flowable’, ‘org/flo
wable/cmmn/db/liquibase/flowable-cmmn-db-changelog.xml’, NOW(), 10, ‘7:e20ea59573dc2a33bbf72043ea09ea4d’,
‘addColumn tableName=ACT_CMMN_RU_CASE_INST; addColumn tableName=ACT_CMMN_RU_CASE_INST; createIndex index
Name=ACT_IDX_CASE_INST_REF_ID_, tableName=ACT_CMMN_RU_CASE_INST; addColumn tableName=ACT_CMMN_HI_CASE_INS
T; addColumn tableName=ACT_CMMN_HI_CASE…’, ‘’, ‘EXECUTED’, NULL, NULL, ‘3.5.3’, ‘9678004051’);

ALTER TABLE ACT_CMMN_RU_PLAN_ITEM_INST ADD DERIVED_CASE_DEF_ID_ VARCHAR(255) NULL;

ALTER TABLE ACT_CMMN_HI_PLAN_ITEM_INST ADD DERIVED_CASE_DEF_ID_ VARCHAR(255) NULL;

INSERT INTO ACT_CMMN_DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRI
PTION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES (‘11’, ‘flowable’, ‘org/flo
wable/cmmn/db/liquibase/flowable-cmmn-db-changelog.xml’, NOW(), 11, ‘7:21c7a61ad7fb26abc675dff7ac54e43e’,
‘addColumn tableName=ACT_CMMN_RU_PLAN_ITEM_INST; addColumn tableName=ACT_CMMN_HI_PLAN_ITEM_INST’, ‘’, ‘E
XECUTED’, NULL, NULL, ‘3.5.3’, ‘9678004051’);

UPDATE ACT_CMMN_DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;

CREATE TABLE FLW_EV_DATABASECHANGELOGLOCK (ID INT NOT NULL, LOCKED BIT(1) NOT NULL, LOCKGRANTED datetime
NULL, LOCKEDBY VARCHAR(255) NULL, CONSTRAINT PK_FLW_EV_DATABASECHANGELOGLOCK PRIMARY KEY (ID));

DELETE FROM FLW_EV_DATABASECHANGELOGLOCK;

INSERT INTO FLW_EV_DATABASECHANGELOGLOCK (ID, LOCKED) VALUES (1, 0);

UPDATE FLW_EV_DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = ‘192.168.10.1 (192.168.10.1)’, LOCKGRANTED
= ‘2020-01-22 08:26:44.423’ WHERE ID = 1 AND LOCKED = 0;

CREATE TABLE FLW_EV_DATABASECHANGELOG (ID VARCHAR(255) NOT NULL, AUTHOR VARCHAR(255) NOT NULL, FILENAME V
ARCHAR(255) NOT NULL, DATEEXECUTED datetime NOT NULL, ORDEREXECUTED INT NOT NULL, EXECTYPE VARCHAR(10) NO
T NULL, MD5SUM VARCHAR(35) NULL, DESCRIPTION VARCHAR(255) NULL, COMMENTS VARCHAR(255) NULL, TAG VARCHAR(2
55) NULL, LIQUIBASE VARCHAR(20) NULL, CONTEXTS VARCHAR(255) NULL, LABELS VARCHAR(255) NULL, DEPLOYMENT_ID
VARCHAR(10) NULL);

CREATE TABLE FLW_EVENT_DEPLOYMENT (ID_ VARCHAR(255) NOT NULL, NAME_ VARCHAR(255) NULL, CATEGORY_ VARCHAR(
255) NULL, DEPLOY_TIME_ datetime(3) NULL, TENANT_ID_ VARCHAR(255) NULL, PARENT_DEPLOYMENT_ID_ VARCHAR(255
) NULL, CONSTRAINT PK_FLW_EVENT_DEPLOYMENT PRIMARY KEY (ID_));

CREATE TABLE FLW_EVENT_RESOURCE (ID_ VARCHAR(255) NOT NULL, NAME_ VARCHAR(255) NULL, DEPLOYMENT_ID_ VARCH
AR(255) NULL, RESOURCE_BYTES_ LONGBLOB NULL, CONSTRAINT PK_FLW_EVENT_RESOURCE PRIMARY KEY (ID_));

CREATE TABLE FLW_EVENT_DEFINITION (ID_ VARCHAR(255) NOT NULL, NAME_ VARCHAR(255) NULL, VERSION_ INT NULL,
KEY_ VARCHAR(255) NULL, CATEGORY_ VARCHAR(255) NULL, DEPLOYMENT_ID_ VARCHAR(255) NULL, TENANT_ID_ VARCHA
R(255) NULL, RESOURCE_NAME_ VARCHAR(255) NULL, DESCRIPTION_ VARCHAR(255) NULL, CONSTRAINT PK_FLW_EVENT_DE
FINITION PRIMARY KEY (ID_));

CREATE UNIQUE INDEX ACT_IDX_EVENT_DEF_UNIQ ON FLW_EVENT_DEFINITION(KEY_, VERSION_, TENANT_ID_);

CREATE TABLE FLW_CHANNEL_DEFINITION (ID_ VARCHAR(255) NOT NULL, NAME_ VARCHAR(255) NULL, VERSION_ INT NUL
L, KEY_ VARCHAR(255) NULL, CATEGORY_ VARCHAR(255) NULL, DEPLOYMENT_ID_ VARCHAR(255) NULL, CREATE_TIME_ da
tetime(3) NULL, TENANT_ID_ VARCHAR(255) NULL, RESOURCE_NAME_ VARCHAR(255) NULL, DESCRIPTION_ VARCHAR(255)
NULL, CONSTRAINT PK_FLW_CHANNEL_DEFINITION PRIMARY KEY (ID_));

CREATE UNIQUE INDEX ACT_IDX_CHANNEL_DEF_UNIQ ON FLW_CHANNEL_DEFINITION(KEY_, VERSION_, TENANT_ID_);

INSERT INTO FLW_EV_DATABASECHANGELOG (ID, AUTHOR, FILENAME, DATEEXECUTED, ORDEREXECUTED, MD5SUM, DESCRIPT
ION, COMMENTS, EXECTYPE, CONTEXTS, LABELS, LIQUIBASE, DEPLOYMENT_ID) VALUES (‘1’, ‘flowable’, ‘org/flowab
le/eventregistry/db/liquibase/flowable-eventregistry-db-changelog.xml’, NOW(), 1, ‘7:0aaa7b01343f4cdaf101
9cd2de3f98f3’, ‘createTable tableName=FLW_EVENT_DEPLOYMENT; createTable tableName=FLW_EVENT_RESOURCE; cre
ateTable tableName=FLW_EVENT_DEFINITION; createIndex indexName=ACT_IDX_EVENT_DEF_UNIQ, tableName=FLW_EVEN
T_DEFINITION; createTable tableName=FLW_CHANNEL_DEFIN…’, ‘’, ‘EXECUTED’, NULL, NULL, ‘3.5.3’, ‘96780044
47’);

UPDATE FLW_EV_DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;

UPDATE ACT_DMN_DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = ‘192.168.10.1 (192.168.10.1)’, LOCKGRANTE
D = ‘2020-01-22 08:26:44.648’ WHERE ID = 1 AND LOCKED = 0;

UPDATE ACT_DMN_DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;

UPDATE ACT_FO_DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = ‘192.168.10.1 (192.168.10.1)’, LOCKGRANTED
= ‘2020-01-22 08:26:44.755’ WHERE ID = 1 AND LOCKED = 0;

UPDATE ACT_FO_DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;

UPDATE ACT_CO_DATABASECHANGELOGLOCK SET LOCKED = 1, LOCKEDBY = ‘192.168.10.1 (192.168.10.1)’, LOCKGRANTED
= ‘2020-01-22 08:26:44.830’ WHERE ID = 1 AND LOCKED = 0;

UPDATE ACT_CO_DATABASECHANGELOGLOCK SET LOCKED = 0, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;

the alter/create command doesn’t work.
If I do not run the insert commands for the above two tables, the flowable task and rest would come up.

forum discussion: https://forum.flowable.org/t/flowable-task-down/6204/11

**Comment by tijsrademakers** [comment]
Hi @GauCho89 , are you using the manual SQL scripts or using the automatic upgrade feature of Flowable?
