### ISSUE TITLE
Flowable ui not support mysql 5.7

### ISSUE THREAD

**Issue by HackToday** [flowable/flowable-engine#2921]
**Describe the bug**

I used flowable 6.6 version and mysql 5.7, mysql-connector 5.1.46

I started flowable-ui can got following errors:

```
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set org/flowable/dmn/db/liquibase/flowable-dmn-db-changelog.xml::7::flowable:
     Reason: liquibase.exception.DatabaseException: Can't DROP 'ACT_IDX_DEC_TBL_UNIQ'; check that column/key exists [Failed SQL: (1091) DROP INDEX ACT_IDX_DEC_TBL_UNIQ ON flowable.ACT_DMN_DECISION_TABLE]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:646) ~[liquibase-core-3.8.0.jar:na]
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53) ~[liquibase-core-3.8.0.jar:na]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83) ~[liquibase-core-3.8.0.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:202) ~[liquibase-core-3.8.0.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:179) ~[liquibase-core-3.8.0.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:175) ~[liquibase-core-3.8.0.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:168) ~[liquibase-core-3.8.0.jar:na]
	at org.flowable.common.engine.impl.db.LiquibaseBasedSchemaManager.schemaUpdate(LiquibaseBasedSchemaManager.java:103) ~[flowable-engine-common-6.6.0.jar:6.6.0]
	... 84 common frames omitted
Caused by: liquibase.exception.DatabaseException: Can't DROP 'ACT_IDX_DEC_TBL_UNIQ'; check that column/key exists [Failed SQL: (1091) DROP INDEX ACT_IDX_DEC_TBL_UNIQ ON flowable.ACT_DMN_DECISION_TABLE]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:402) ~[liquibase-core-3.8.0.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:59) ~[liquibase-core-3.8.0.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:131) ~[liquibase-core-3.8.0.jar:na]
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1273) ~[liquibase-core-3.8.0.jar:na]
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1255) ~[liquibase-core-3.8.0.jar:na]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:609) ~[liquibase-core-3.8.0.jar:na]
	... 91 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Can't DROP 'ACT_IDX_DEC_TBL_UNIQ'; check that column/key exists
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:na]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3976) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3912) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2482) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2440) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745) ~[mysql-connector-java-5.1.46.jar:5.1.46]
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95) ~[HikariCP-3.4.5.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-3.4.5.jar:na]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(J
```
**Expected behavior**

Expected  flowable-ui can run correctly

**Code**
If applicable, add the code that you are using when having the issue.

**Additional context**
Add the version of Flowable that you are using, the database vendor and if you are using Flowable within Spring Boot, the Flowable Task application etc.

**Comment by HackToday** [comment]
It seems. https://flowable.com/open-source/docs/bpmn/ch14-Applications/

not have any info about supported mysql versions

**Comment by filiphr** [comment]
From which version are you upgrading? Have you manually done some SQL changes to the database?

The failure is happening when an index is [dropped](https://github.com/flowable/flowable-engine/blob/aa8c5851f4bbc7a04089cdc5849314c5827d6ff5/modules/flowable-dmn-engine/src/main/resources/org/flowable/dmn/db/liquibase/flowable-dmn-db-changelog.xml#L162). However, that index is added in the [step](https://github.com/flowable/flowable-engine/blob/aa8c5851f4bbc7a04089cdc5849314c5827d6ff5/modules/flowable-dmn-engine/src/main/resources/org/flowable/dmn/db/liquibase/flowable-dmn-db-changelog.xml#L152) before that.

We do support MySQL 5.7. You can easily see that by checking the [MySQL](https://github.com/flowable/flowable-engine/actions/workflows/mysql.yml) workflow and seeing the DB versions that we run the tests against.

**Comment by HackToday** [comment]
@filiphr  I just follow the guide here 

https://flowable.com/open-source/docs/bpmn/ch14-Applications/

It is fresh install, not upgrading.


Also I tried manual configure with docker image  `flowable/flowable-ui` (manual change db driver and new image and start) Also failed the same case.

Could you help why new install kick upgrading ? I am not sure why it did that way

**Comment by filiphr** [comment]
mysql-connector 5.1.46 is from February 2018. We suggest using a newer version of the JDBC driver.

We are testing with the following version:

```
<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <version>8.0.19</version>
</dependency>
```

**Comment by HackToday** [comment]
@filiphr still hit the same issue

```
	at org.flowable.common.engine.impl.db.LiquibaseBasedSchemaManager.schemaUpdate(LiquibaseBasedSchemaManager.java:103) ~[flowable-engine-common-6.6.0.jar:6.6.0]
	... 84 common frames omitted
Caused by: liquibase.exception.DatabaseException: Can't DROP 'ACT_IDX_DEC_TBL_UNIQ'; check that column/key exists [Failed SQL: (1091) DROP INDEX ACT_IDX_DEC_TBL_UNIQ ON flowable.ACT_DMN_DECISION_TABLE]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:402) ~[liquibase-core-3.8.0.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:59) ~[liquibase-core-3.8.0.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:131) ~[liquibase-core-3.8.0.jar:na]
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1273) ~[liquibase-core-3.8.0.jar:na]
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1255) ~[liquibase-core-3.8.0.jar:na]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:609) ~[liquibase-core-3.8.0.jar:na]
	... 91 common frames omitted
Caused by: java.sql.SQLSyntaxErrorException: Can't DROP 'ACT_IDX_DEC_TBL_UNIQ'; check that column/key exists
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:764) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95) ~[HikariCP-3.4.5.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-3.4.5.jar:na]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:398) ~[liquibase-core-3.8.0.jar:na]
	... 96 common frames omitted
```

**Comment by HackToday** [comment]
According to  test result,  flowable-ui (docker image `https://hub.docker.com/r/flowable/flowable-ui`. change flowable driver configuration ) with mysql 5.7 and mysql connector 8.0.19 not work either.  

Also https://flowable.com/open-source/docs/bpmn/ch14-Applications/. deploy ways not work with mysql driver.

**Comment by filiphr** [comment]
I just run the `FlowableUiApplication` locally with MySQL 5.7 and it worked correctly. Please share your entire log output.

**Comment by HackToday** [comment]
[flowable-ui-failure.txt](https://github.com/flowable/flowable-engine/files/6469884/flowable-ui-failure.txt)


@filiphr  please check the attached full logs

**Comment by filiphr** [comment]
@HackToday the error in this logs is not the same as the one you shared initially. 

Your current error is

```
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set org/flowable/dmn/db/liquibase/flowable-dmn-db-changelog.xml::8::flowable:
     Reason: liquibase.exception.DatabaseException: Table 'flowable.act_dmn_decision' doesn't exist [Failed SQL: (1146) ALTER TABLE flowable.ACT_DMN_DECISION ADD DECISION_TYPE_ VARCHAR(255) NULL]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:646) ~[liquibase-core-3.8.0.jar:na]
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53) ~[liquibase-core-3.8.0.jar:na]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83) ~[liquibase-core-3.8.0.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:202) ~[liquibase-core-3.8.0.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:179) ~[liquibase-core-3.8.0.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:175) ~[liquibase-core-3.8.0.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:168) ~[liquibase-core-3.8.0.jar:na]
	at org.flowable.common.engine.impl.db.LiquibaseBasedSchemaManager.schemaUpdate(LiquibaseBasedSchemaManager.java:103) ~[flowable-engine-common-6.6.0.jar:6.6.0]
	... 84 common frames omitted
Caused by: liquibase.exception.DatabaseException: Table 'flowable.act_dmn_decision' doesn't exist [Failed SQL: (1146) ALTER TABLE flowable.ACT_DMN_DECISION ADD DECISION_TYPE_ VARCHAR(255) NULL]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:402) ~[liquibase-core-3.8.0.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:59) ~[liquibase-core-3.8.0.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:131) ~[liquibase-core-3.8.0.jar:na]
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1273) ~[liquibase-core-3.8.0.jar:na]
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1255) ~[liquibase-core-3.8.0.jar:na]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:609) ~[liquibase-core-3.8.0.jar:na]
	... 91 common frames omitted
Caused by: java.sql.SQLSyntaxErrorException: Table 'flowable.act_dmn_decision' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:764) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648) ~[mysql-connector-java-8.0.19.jar:8.0.19]
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95) ~[HikariCP-3.4.5.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-3.4.5.jar:na]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:398) ~[liquibase-core-3.8.0.jar:na]
	... 96 common frames omitted
```

Also this is not a fresh install because it doesn't start creating the tables from scratch, but it starts from a later version.

**Comment by HackToday** [comment]
@filiphr  pls check the new log below. Thanks
[newlog.txt](https://github.com/flowable/flowable-engine/files/6497738/newlog.txt)

**Comment by filiphr** [comment]
Really weird @HackToday. Can you please share your setup so I can try to reproduce what you are seeing?
