### ISSUE TITLE
Module [groovy-jsr223 is loaded in version 3.0.7 and you are trying to load version 3.0.8

### ISSUE THREAD

**Issue by yaodwwy** [flowable/flowable-engine#2958]
**Describe the bug**
when I run with `java  -jar flowable-ui.war`

**Expected behavior**
not running, ExceptionInInitializerError null

**Code**
```
:: Flowable :: (v6.6.2.5)    :: Spring Boot ::  (v2.4.4)

2021-06-18 17:59:56.352  INFO 22784 --- [           main] o.f.u.application.FlowableUiApplication  : Starting FlowableUiApplication v6.6.2.5 using Java 1.8.0_202-ea on Adam with PID 22784 (C:\dev\flowable-engine\modules\flowable-ui\flowable-ui-app\target\flowable-ui.war started by Adam in C:\dev\flowable-engine\modules\flowable-ui\flowable-ui-app\target)
2021-06-18 17:59:56.358  INFO 22784 --- [           main] o.f.u.application.FlowableUiApplication  : No active profile set, falling back to default profiles: default
2021-06-18 17:59:57.731  WARN 22784 --- [kground-preinit] o.s.h.c.j.Jackson2ObjectMapperBuilder    : For Jackson Kotlin classes support please add "com.fasterxml.jackson.module:jackson-module-kotlin" to the classpath
2021-06-18 17:59:58.277 ERROR 22784 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.ExceptionInInitializerError: null
        at org.springframework.beans.factory.groovy.GroovyBeanDefinitionReader.<init>(GroovyBeanDefinitionReader.java:150) ~[spring-beans-5.3.6.jar!/:5.3.6]
        at org.springframework.boot.BeanDefinitionLoader.<init>(BeanDefinitionLoader.java:90) ~[spring-boot-2.4.4.jar!/:2.4.4]
        at org.springframework.boot.SpringApplication.createBeanDefinitionLoader(SpringApplication.java:749) [spring-boot-2.4.4.jar!/:2.4.4]
        at org.springframework.boot.SpringApplication.load(SpringApplication.java:692) [spring-boot-2.4.4.jar!/:2.4.4]
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:413) [spring-boot-2.4.4.jar!/:2.4.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:325) [spring-boot-2.4.4.jar!/:2.4.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1313) [spring-boot-2.4.4.jar!/:2.4.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) [spring-boot-2.4.4.jar!/:2.4.4]
        at org.flowable.ui.application.FlowableUiApplication.main(FlowableUiApplication.java:27) [classes!/:6.6.2.5]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_202-ea]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_202-ea]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_202-ea]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_202-ea]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [flowable-ui.war:6.6.2.5]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [flowable-ui.war:6.6.2.5]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [flowable-ui.war:6.6.2.5]
        at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59) [flowable-ui.war:6.6.2.5]
Caused by: groovy.lang.GroovyRuntimeException: Conflicting module versions. Module [groovy-jsr223 is loaded in version 3.0.7 and you are trying to load version 3.0.8
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl$DefaultModuleListener.onModule(MetaClassRegistryImpl.java:510) ~[groovy-3.0.8.jar!/:3.0.8]
        at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanExtensionModuleFromProperties(ExtensionModuleScanner.java:87) ~[groovy-3.0.8.jar!/:3.0.8]
        at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanExtensionModuleFromMetaInf(ExtensionModuleScanner.java:81) ~[groovy-3.0.8.jar!/:3.0.8]
        at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanClasspathModulesFrom(ExtensionModuleScanner.java:63) ~[groovy-3.0.8.jar!/:3.0.8]
        at org.codehaus.groovy.runtime.m12n.ExtensionModuleScanner.scanClasspathModules(ExtensionModuleScanner.java:54) ~[groovy-3.0.8.jar!/:3.0.8]
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:125) ~[groovy-3.0.8.jar!/:3.0.8]
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:86) ~[groovy-3.0.8.jar!/:3.0.8]
        at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:37) ~[groovy-3.0.8.jar!/:3.0.8]
        ... 17 common frames omitted
```

**Comment by yaodwwy** [comment]
anything I was missed?

**Comment by yaodwwy** [comment]
`<groovy.version>3.0.7</groovy.version>`
====>>
`<groovy.version>3.0.8</groovy.version>`

problem solved.
Maybe pom.xml not reload in right way...
