### ISSUE TITLE
ibatis ReflectionException when calling org.flowable.cmmn.api.aveTask(Task task);

### ISSUE THREAD

**Issue by andyverberne** [flowable/flowable-engine#2966]
**Describe the bug**
When calling the method: org.flowable.cmmn.api.CmmnTaskService.saveTask(Task task) the following exception occurs:
This is irrespective of the changes made to the task.
```
### Error updating database.  Cause: org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'VARCHAR' in 'class org.flowable.task.service.impl.persistence.entity.TaskEntityImpl'
### The error may exist in org/flowable/task/service/db/mapping/entity/Task.xml
### The error may involve org.flowable.task.service.impl.persistence.entity.TaskEntityImpl.updateTask
### The error occurred while executing an update
### Cause: org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'VARCHAR' in 'class org.flowable.task.service.impl.persistence.entity.TaskEntityImpl': org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'VARCHAR' in 'class org.flowable.task.service.impl.persistence.entity.TaskEntityImpl'
### The error may exist in org/flowable/task/service/db/mapping/entity/Task.xml
### The error may involve org.flowable.task.service.impl.persistence.entity.TaskEntityImpl.updateTask
### The error occurred while executing an update
### Cause: org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'VARCHAR' in 'class 

Caused by: org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'VARCHAR' in 'class org.flowable.task.service.impl.persistence.entity.TaskEntityImpl'
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.reflection.Reflector.getGetInvoker(Reflector.java:374)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.reflection.MetaClass.getGetInvoker(MetaClass.java:164)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.reflection.wrapper.BeanWrapper.getBeanProperty(BeanWrapper.java:162)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.reflection.wrapper.BeanWrapper.get(BeanWrapper.java:49)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.reflection.MetaObject.getValue(MetaObject.java:122)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.scripting.xmltags.DynamicContext$ContextMap.get(DynamicContext.java:102)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.scripting.xmltags.DynamicContext$ContextAccessor.getProperty(DynamicContext.java:113)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.ognl.OgnlRuntime.getProperty(OgnlRuntime.java:3338)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.ognl.ASTProperty.getValueBody(ASTProperty.java:121)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.ognl.SimpleNode.getValue(SimpleNode.java:258)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.ognl.ASTAssign.getValueBody(ASTAssign.java:52)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.ognl.SimpleNode.getValue(SimpleNode.java:258)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.ognl.ASTSequence.getValueBody(ASTSequence.java:63)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.ognl.SimpleNode.getValue(SimpleNode.java:258)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.ognl.Ognl.getValue(Ognl.java:560)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.ognl.Ognl.getValue(Ognl.java:524)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.scripting.xmltags.OgnlCache.getValue(OgnlCache.java:46)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.scripting.xmltags.TextSqlNode$BindingTokenParser.handleToken(TextSqlNode.java:77)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.parsing.GenericTokenParser.parse(GenericTokenParser.java:77)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.scripting.xmltags.TextSqlNode.apply(TextSqlNode.java:51)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.scripting.xmltags.MixedSqlNode.lambda$apply$0(MixedSqlNode.java:32)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.scripting.xmltags.MixedSqlNode.apply(MixedSqlNode.java:32)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.scripting.xmltags.IfSqlNode.apply(IfSqlNode.java:35)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.scripting.xmltags.MixedSqlNode.lambda$apply$0(MixedSqlNode.java:32)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.scripting.xmltags.MixedSqlNode.apply(MixedSqlNode.java:32)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.scripting.xmltags.TrimSqlNode.apply(TrimSqlNode.java:55)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.scripting.xmltags.MixedSqlNode.lambda$apply$0(MixedSqlNode.java:32)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.scripting.xmltags.MixedSqlNode.apply(MixedSqlNode.java:32)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.scripting.xmltags.DynamicSqlSource.getBoundSql(DynamicSqlSource.java:39)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.mapping.MappedStatement.getBoundSql(MappedStatement.java:305)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.executor.statement.BaseStatementHandler.<init>(BaseStatementHandler.java:64)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.executor.statement.PreparedStatementHandler.<init>(PreparedStatementHandler.java:41)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.executor.statement.RoutingStatementHandler.<init>(RoutingStatementHandler.java:46)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.session.Configuration.newStatementHandler(Configuration.java:658)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:48)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at deployment.zaakafhandelcomponent.war//org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	 99 more
OptionsAttachments
```

**Additional context**
Using flowable version 6.6.1.15 but the fix also applies to the master branch.

**Fix**
Problem is casued by the following line in the file: flowable-engine/modules/flowable-task-service/src/main/resources/org/flowable/task/service/db/mapping/entity/Task.xml
```
PROPAGATED_STAGE_INST_ID_ = ${propagatedStageInstanceId, jdbcType=VARCHAR},
```
Where the '$' character should be a '#'

**Comment by filiphr** [comment]
Fixed in PR #2968, thanks @andyverberne
