### ISSUE TITLE
Specified key was too long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by mbt522533623** [flowable/flowable-engine#2972]
Caused by: liquibase.exception.DatabaseException: Specified key was too long; max key length is 1000 bytes [Failed SQL: (1071) CREATE UNIQUE INDEX ACT_IDX_EVENT_DEF_UNIQ ON flowable.FLW_EVENT_DEFINITION(KEY_, VERSION_, TENANT_ID_)]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:393) ~[liquibase-core-4.3.5.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:82) ~[liquibase-core-4.3.5.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:150) ~[liquibase-core-4.3.5.jar:na]
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1278) ~[liquibase-core-4.3.5.jar:na]
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1260) ~[liquibase-core-4.3.5.jar:na]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637) ~[liquibase-core-4.3.5.jar:na]
	... 93 common frames omitted

**Comment by filiphr** [comment]
On which database does this happen?

**Comment by mbt522533623** [comment]
mysql

**Comment by mbt522533623** [comment]
> On which database does this happen?

mysql

**Comment by lytdev** [comment]
> mysql

use mysql innodb

**Comment by filiphr** [comment]
@mbt522533623 please try the suggestion my @lytdev and use mysql innodb. Closing this in the meantime.

Thanks @lytdev for the suggestion.
