### ISSUE TITLE
OutOfMemory error on download large content items

### ISSUE THREAD

**Issue by DevWantJustHaveFun** [flowable/flowable-engine#3009]
**Describe the bug**
When I download larges files (more than 1 GB) with the content api "/content-service/content-items/{contentItemId}/data" endpoint, I get some "out of memory error" and "max heap error"

** Example Stacktrace **

```
Heap
 garbage-first heap   total 1077248K, used 715658K [0x00000000be400000, 0x0000000100000000)
  region size 1024K, 1 young (1024K), 0 survivors (0K)
 Metaspace       used 224799K, capacity 231579K, committed 232412K, reserved 682404K
  class space    used 25796K, capacity 28434K, committed 28620K, reserved 477604K
jvmkill killing current process
2021-08-05 14:04:56.286 ERROR 1 --- [nio-9080-exec-6] o.f.c.r.e.BaseExceptionHandlerAdvice     : Unhandled exception
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1078) ~[spring-webmvc-5.3.7.jar:5.3.7]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.7.jar:5.3.7]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.7.jar:5.3.7]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.7.jar:5.3.7]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626) ~[tomcat-embed-core-9.0.46.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.7.jar:5.3.7]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[tomcat-embed-core-9.0.46.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.46.jar:9.0.46]
....
```

**Expected behavior**
I would be able to download larges file using the content api 

**Code**

In the endpoint "/content-service/content-items/{contentItemId}/data"
Converting the data inputstream into a ResponseEntity<byte[]> is not a good idea because the file will be loaded into the memory at some point.
I suggest to use  ResponseEntity<InputStreamResource> like in the following pull request

**Additional context**
I have the issue with flowable-work ; 3.9.X and 3.10.X
I'm using
JDK 11
Spring Boot 2.5.2
Open source dependency version:  6.6.X

**Comment by filiphr** [comment]
Done in https://github.com/flowable/flowable-engine/commit/6ca28be2ade938ba45d65372a88d8744f8e6ebb3. Thanks @DevWantJustHaveFun

**Comment by DevWantJustHaveFun** [comment]
@filiphr thanks!

I have also the same issue with this endpoint "/content-service/version-parent-items/{versionParentId}/data" in flowable-work so obviously I cannot fix it into flowable-engine. 

How to inform the flowable-work maintainer and have this fixed in flowable-work too ?

**Comment by filiphr** [comment]
@DevWantJustHaveFun for problems with flowable-work I would suggest that you raise a Support Issue through our Service Desk so we can track it.
