### ISSUE TITLE
The error may involve org.flowable.engine.impl.persistence.entity.ExecutionEntityImpl.bulkInsertExecution-Inline

### ISSUE THREAD

**Issue by ahjsyangliang** [flowable/flowable-engine#3038]
### Here are the one error on version 6.5.0

```
org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: java.sql.SQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`abs_db`.`act_ru_execution`, CONSTRAINT `ACT_FK_EXE_PARENT` FOREIGN KEY (`PARENT_ID_`) REFERENCES `act_ru_execution` (`ID_`) ON DELETE CASCADE)
### The error may exist in org/flowable/db/mapping/entity/Execution.xml
### The error may involve org.flowable.engine.impl.persistence.entity.ExecutionEntityImpl.bulkInsertExecution-Inline
### The error occurred while setting parameters
### SQL: insert into ACT_RU_EXECUTION (ID_, REV_, PROC_INST_ID_, BUSINESS_KEY_, PROC_DEF_ID_, ACT_ID_, IS_ACTIVE_, IS_CONCURRENT_,                                            IS_SCOPE_,IS_EVENT_SCOPE_, IS_MI_ROOT_, PARENT_ID_, SUPER_EXEC_, ROOT_PROC_INST_ID_, SUSPENSION_STATE_,                                            TENANT_ID_, NAME_, START_ACT_ID_, START_TIME_, START_USER_ID_, IS_COUNT_ENABLED_, EVT_SUBSCR_COUNT_,                                            TASK_COUNT_, JOB_COUNT_, TIMER_JOB_COUNT_, SUSP_JOB_COUNT_, DEADLETTER_JOB_COUNT_, VAR_COUNT_, ID_LINK_COUNT_,                                            CALLBACK_ID_, CALLBACK_TYPE_, REFERENCE_ID_, REFERENCE_TYPE_, PROPAGATED_STAGE_INST_ID_)     values                  (?,          1,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?         )        ,          (?,          1,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?,          ?         )
### Cause: java.sql.SQLIntegrityConstraintViolationException: Cannot add or update a child row: a foreign key constraint fails (`abs_db`.`act_ru_execution`, CONSTRAINT `ACT_FK_EXE_PARENT` FOREIGN KEY (`PARENT_ID_`) REFERENCES `act_ru_execution` (`ID_`) ON DELETE CASCADE)
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:199)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:184)
	at org.flowable.common.engine.impl.db.DbSqlSession.flushBulkInsert(DbSqlSession.java:540)
	at org.flowable.common.engine.impl.db.DbSqlSession.flushInsertEntities(DbSqlSession.java:496)
	at org.flowable.common.engine.impl.db.DbSqlSession.flushInserts(DbSqlSession.java:473)
	at org.flowable.common.engine.impl.db.DbSqlSession.flush(DbSqlSession.java:358)
	at org.flowable.common.engine.impl.interceptor.CommandContext.flushSessions(CommandContext.java:192)
	at org.flowable.common.engine.impl.interceptor.CommandContext.close(CommandContext.java:61)
	at org.flowable.common.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:81)
	at org.flowable.common.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:51)
	at org.flowable.common.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30)
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56)
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51)
	at org.flowable.engine.impl.FormServiceImpl.submitTaskFormData(FormServiceImpl.java:80)
```

**Comment by MasterLover** [comment]
https://github.com/betaseeker/How-To-Ask-Questions

**Comment by tijsrademakers** [comment]
Can you please add more information about when this error is thrown. Adding an example where this happens will help us, because then we can try and reproduce it.

**Comment by ahjsyangliang** [comment]
I am very glad to receive your reply, and I am sorry for the trouble caused to you by not providing enough information.  
 
Initially, my testing process was normal in both the development environment and the test environment.  This problem occurs when packaged and deployed to production.  We have checked the production and test environment configuration one by one, and there is no problem. Here is the environment configuration:  

1. centOS7.8
2. jdk1.8.0_131
3. maridb10.4.7
4. redis1.16

When this exception is thrown, the same exception is thrown when other tasks operate.  
 
This problem occurred when I selected and countersigned the sub-process. The following is my flow chart:  


![f09d836a-6733-426c-83a3-0e182b73ae23](https://user-images.githubusercontent.com/49012299/132157511-068d513d-cf7a-4717-81c3-798aac100a8b.png)
