### ISSUE TITLE
Api did not get reach their endpointing

### ISSUE THREAD

**Issue by Thirumalaisamy-paulraj** [flowable/flowable-engine#3155]
We have using tomcat web server and mariadb . and also flowable engine. while we try to restarting tomcat server it will get error on type.
at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1417)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
2021-12-21 07:13:48.018 INFO 129821 --- [ost-startStop-5] o.s.s.c.ThreadPoolTaskExecutor : Shutting down ExecutorService 'applicationTaskExecutor'
21-Dec-2021 07:13:48.306 INFO [localhost-startStop-5] org.apache.catalina.core.StandardWrapper.unload Waiting for [43] instance(s) to be deallocated for Servlet [dispatcherServlet]
21-Dec-2021 07:13:49.310 INFO [localhost-startStop-5] org.apache.catalina.core.StandardWrapper.unload Waiting for [43] instance(s) to be deallocated for Servlet [dispatcherServlet]
21-Dec-2021 07:13:50.312 INFO [localhost-startStop-5] org.apache.catalina.core.StandardWrapper.unload Waiting for [43] instance(s) to be deallocated for Servlet [dispatcherServlet]
2021-12-21 07:13:50.494 INFO 129821 --- [ost-startStop-5] o.f.j.s.i.a.AbstractAsyncExecutor : Shutting down the async job executor [org.flowable.spring.job.service.SpringAsyncExecutor].
Shutting down the async job executor [org.flowable.spring.job.service.SpringAsyncExecutor].Shutting down ExecutorService 'applicationTaskExecutor'
21-Dec-2021 07:13:48.306 INFO [localhost-startStop-5] org.apache.catalina.core.StandardWrapper.unload Waiting for [43] instance(s) to be deallocated for Servlet [dispatcherServlet]

**Comment by tijsrademakers** [comment]
Hi @Thirumalaisamy-paulraj , this error sometimes happens when shutting down Flowable. Or do you really see it at startup? If you see it at startup then there should be an exception message being included above this that explains why Flowable can't be started.
