### ISSUE TITLE
setAuthenticatedUserId to current authenticated user throws exception

### ISSUE THREAD

**Issue by lejtmany** [flowable/flowable-engine#3226]
**Describe the bug**
We're trying to launch a new process instance in a script task. We want this new process to have the same start user as the current process. Based on the documentation [here](https://www.flowable.com/open-source/docs/bpmn/ch07b-BPMN-Constructs/#start-events) we tried to use `setAuthenticatedUserId` prior to starting the process and setting the user id back to the original value in the `finally` block.
The following exception gets thrown within the delegate:
 ```
 2022-02-23 15:19:15.382 ERROR 1 --- [nio-8081-exec-9] o.a.c.c.C.[Tomcat].[localhost]           : Exception Processing ErrorPage[errorCode=0, location=/error]

org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.Object] to type [byte[]] for value 'SecurityContextImpl [Authentication=UsernamePasswordAuthenticationToken [Principal=org.flowable.common.engine.impl.identity.UserIdPrincipal@27c3ddb4, Credentials=[PROTECTED], Authenticated=false, Details=null, Granted Authorities=[]]]'; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer; nested exception is java.io.NotSerializableException: org.flowable.common.engine.impl.identity.UserIdPrincipal
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:47) ~[spring-core-5.3.14.jar:5.3.14]
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:192) ~[spring-core-5.3.14.jar:5.3.14]
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository.serialize(JdbcIndexedSessionRepository.java:623) ~[spring-session-jdbc-2.6.1.jar:2.6.1]
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository.lambda$updateSessionAttributes$6(JdbcIndexedSessionRepository.java:549) ~[spring-session-jdbc-2.6.1.jar:2.6.1]
	at org.springframework.jdbc.core.JdbcTemplate.lambda$update$2(JdbcTemplate.java:963) ~[spring-jdbc-5.3.14.jar:5.3.14]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:651) ~[spring-jdbc-5.3.14.jar:5.3.14]
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:960) ~[spring-jdbc-5.3.14.jar:5.3.14]
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:1015) ~[spring-jdbc-5.3.14.jar:5.3.14]
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository.updateSessionAttributes(JdbcIndexedSessionRepository.java:547) ~[spring-session-jdbc-2.6.1.jar:2.6.1]
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository.access$1300(JdbcIndexedSessionRepository.java:133) ~[spring-session-jdbc-2.6.1.jar:2.6.1]
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository$JdbcSession.lambda$save$10(JdbcIndexedSessionRepository.java:860) ~[spring-session-jdbc-2.6.1.jar:2.6.1]
	at org.springframework.transaction.support.TransactionOperations.lambda$executeWithoutResult$0(TransactionOperations.java:68) ~[spring-tx-5.3.14.jar:5.3.14]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.3.14.jar:5.3.14]
	at org.springframework.transaction.support.TransactionOperations.executeWithoutResult(TransactionOperations.java:67) ~[spring-tx-5.3.14.jar:5.3.14]
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository$JdbcSession.save(JdbcIndexedSessionRepository.java:836) ~[spring-session-jdbc-2.6.1.jar:2.6.1]
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository$JdbcSession.access$200(JdbcIndexedSessionRepository.java:665) ~[spring-session-jdbc-2.6.1.jar:2.6.1]
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository.save(JdbcIndexedSessionRepository.java:422) ~[spring-session-jdbc-2.6.1.jar:2.6.1]
	at org.springframework.session.jdbc.JdbcIndexedSessionRepository.save(JdbcIndexedSessionRepository.java:133) ~[spring-session-jdbc-2.6.1.jar:2.6.1]
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.commitSession(SessionRepositoryFilter.java:226) ~[spring-session-core-2.6.1.jar:2.6.1]
	at org.springframework.session.web.http.SessionRepositoryFilter$SessionRepositoryRequestWrapper.access$100(SessionRepositoryFilter.java:193) ~[spring-session-core-2.6.1.jar:2.6.1]
	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:145) ~[spring-session-core-2.6.1.jar:2.6.1]
	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:82) ~[spring-session-core-2.6.1.jar:2.6.1]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102) ~[spring-web-5.3.14.jar:5.3.14]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:711) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:461) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:385) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:313) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:403) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:249) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:344) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1732) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.56.jar:9.0.56]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: org.springframework.core.serializer.support.SerializationFailedException: Failed to serialize object using DefaultSerializer; nested exception is java.io.NotSerializableException: org.flowable.common.engine.impl.identity.UserIdPrincipal
	at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:64) ~[spring-core-5.3.14.jar:5.3.14]
	at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:33) ~[spring-core-5.3.14.jar:5.3.14]
	at org.springframework.core.convert.support.GenericConversionService$ConverterAdapter.convert(GenericConversionService.java:386) ~[spring-core-5.3.14.jar:5.3.14]
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:41) ~[spring-core-5.3.14.jar:5.3.14]
	... 46 common frames omitted
Caused by: java.io.NotSerializableException: org.flowable.common.engine.impl.identity.UserIdPrincipal
	at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source) ~[na:na]
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(Unknown Source) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeSerialData(Unknown Source) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source) ~[na:na]
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(Unknown Source) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeSerialData(Unknown Source) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(Unknown Source) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeObject0(Unknown Source) ~[na:na]
	at java.base/java.io.ObjectOutputStream.writeObject(Unknown Source) ~[na:na]
	at org.springframework.core.serializer.DefaultSerializer.serialize(DefaultSerializer.java:46) ~[spring-core-5.3.14.jar:5.3.14]
	at org.springframework.core.serializer.Serializer.serializeToByteArray(Serializer.java:56) ~[spring-core-5.3.14.jar:5.3.14]
	at org.springframework.core.serializer.support.SerializingConverter.convert(SerializingConverter.java:60) ~[spring-core-5.3.14.jar:5.3.14]
	... 49 common frames omitted
```
We've also tried `identityService.setAuthenticatedUserId(null);` but that seems to clear the authentication context altogether and log the user out.
The exception was also getting thrown when we just used `identityService.setAuthenticatedUserId(startUser)` and dispensed with the `finally` block altogether.
We've also tried `SecurityUtils.getCurrentUserId()` to get the current user id
**Expected behavior**
To be able to use `identityService.setAuthenticatedUserId` to start a process instance with a given id

**Code**
```java
  RuntimeService runtimeService = Context.getProcessEngineConfiguration().getRuntimeService();
  IdentityService identityService = Context.getProcessEngineConfiguration().getIdentityService();
  String olduserId = Authentication.getAuthenticatedUserId();
  String startUserId = runtimeService.createProcessInstanceQuery().processInstanceId(delegateTask.getProcessInstanceId()).singleResult().getStartUserId();
  try{
    identityService.setAuthenticatedUserId(startUserId);
    ProcessInstance newProcess = runtimeService.createProcessInstanceBuilder()
      .variables(taskVariables)
      .processDefinitionKey(processName)
      .start();
      delegateTask.setVariable(processName, newProcess.getId());
  } finally{
    identityService.setAuthenticatedUserId(olduserId);
  }
```

**Additional context**
Using the Flowable UI Application (6.7.2) with postgresql.

Thank you in advance for your help and a great project!

**Comment by lejtmany** [comment]
@filiphr Thank you that worked! Here's the code for anyone else that runs into this.
```java
    RuntimeService runtimeService = Context.getProcessEngineConfiguration().getRuntimeService();
    IdentityService identityService = Context.getProcessEngineConfiguration().getIdentityService();
    Principal olduser = Authentication.getAuthenticationContext().getPrincipal();
    String startUserId = runtimeService.createProcessInstanceQuery().processInstanceId(delegateTask.getProcessInstanceId()).singleResult().getStartUserId();
    try{
      identityService.setAuthenticatedUserId(startUserId);    
      ProcessInstance newProcess = runtimeService.createProcessInstanceBuilder()
        .variables(taskVariables)
        .processDefinitionKey(processName)
        .start();
        delegateTask.setVariable(processName, newProcess.getId());
    } finally{
      Authentication.getAuthenticationContext().setPrincipal(olduser);
    }
```
