### ISSUE TITLE
Incorrect log message for PlanItemInstanceState

### ISSUE THREAD

**Issue by mennotol** [flowable/flowable-engine#3280]
**Describe the bug**
The following cryptic log message appears when attempting to start a project: 
```
org.flowable.common.engine.api.FlowableIllegalStateException: Can only enable a plan item instance which is in state ENABLED
	at org.flowable.cmmn.engine.impl.cmd.StartPlanItemInstanceCmd.internalExecute(StartPlanItemInstanceCmd.java:55) ~[flowable-cmmn-engine-6.7.2.jar:6.7.2]
	at org.flowable.cmmn.engine.impl.cmd.AbstractNeedsPlanItemInstanceCmd.execute(AbstractNeedsPlanItemInstanceCmd.java:101) ~[flowable-cmmn-engine-6.7.2.jar:6.7.2]
	at org.flowable.cmmn.engine.impl.cmd.AbstractNeedsPlanItemInstanceCmd.execute(AbstractNeedsPlanItemInstanceCmd.java:34) ~[flowable-cmmn-engine-6.7.2.jar:6.7.2]
```

**Expected behavior**
A look at the code suggest the message should be: Can only enable a plan item instance which is *not* in state ENABLED

**Code**
NA

**Additional context**
Flowable 6.7.2, Spring boot 2.6.6

**Comment by dbmalkovsky** [comment]
The code in question is:
<pre>
@Override
protected void internalExecute(CommandContext commandContext, PlanItemInstanceEntity planItemInstanceEntity) {
    if (!PlanItemInstanceState.ENABLED.equals(planItemInstanceEntity.getState())) {
        throw new FlowableIllegalStateException("Can only enable a plan item instance which is in state ENABLED");
    }
    CommandContextUtil.getAgenda(commandContext).planStartPlanItemInstanceOperation(planItemInstanceEntity, null,
            new ChildTaskActivityBehavior.VariableInfo(childTaskVariables, childTaskFormVariables, childTaskFormOutcome, childTaskFormInfo));
}
</pre>
My reading of the code indicates that if the plan item instance has to be enabled as the exception is thrown only if the state is *NOT* enabled: ` if (!PlanItemInstanceState.ENABLED.equals(planItemInstanceEntity.getState()))`.  Thus the message is correct about the plan item requiring to be in the ENABLED state to start it.   It seems counter intuitive that you would want to start something that is not enabled, doesn't it?

**Comment by tiffmaelite** [comment]
Maybe the message should actually be "can only _start_ a plan item instance which is in state ENABLED"?
