### ISSUE TITLE
flowable-6.7.2 Table 'workflow.flw_channel_definition' doesn't exis

### ISSUE THREAD

**Issue by quaider** [flowable/flowable-engine#3294]
**Describe the bug**
i use a new project with flowable 6.7.2 and spring-boot 2.6.3, when start error throw with  Table 'workflow.flw_channel_definition' doesn't exist [Failed SQL: (1146) ALTER TABLE workflow.FLW_CHANNEL_DEFINITION ADD TYPE_ VARCHAR(255) NULL]

**Expected behavior**
start normally

**Code**
here is my config 
application.yaml

``` yaml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/workflow?useUnicode=true&characterEncoding=UTF-8&useSSL=false&nullCatalogMeansCurrent=true
    password: root
    username: root

flowable:
  database-schema-update: true
  database-schema: workflow
```

dependency
``` xml
<dependencies>
        <dependency>
            <groupId>org.flowable</groupId>
            <artifactId>flowable-spring-boot-starter</artifactId>
            <version>6.7.2</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
        </dependency>

    </dependencies>
```
and last is starter class
```java
@SpringBootApplication(proxyBeanMethods = false)
public class FlowableApplication {
    public static void main(String[] args) {
        SpringApplication.run(FlowableApplication.class, args);
    }
}
```

that all my code， i tried many times and drop my database again and again，but does not work

**Additional context**
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'appRepositoryServiceBean' defined in class path resource [org/flowable/spring/boot/app/AppEngineServicesAutoConfiguration.class]: Unsatisfied dependency expressed through method 'appRepositoryServiceBean' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flowableAppEngine': FactoryBean threw exception on object creation; nested exception is org.flowable.common.engine.api.FlowableException: Error initialising eventregistry data model
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.15.jar:5.3.15]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) [spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414) [spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) [spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) [spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) [spring-boot-2.6.3.jar:2.6.3]
	at org.example.flowable.boot.FlowableApplication.main(FlowableApplication.java:9) [classes/:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flowableAppEngine': FactoryBean threw exception on object creation; nested exception is org.flowable.common.engine.api.FlowableException: Error initialising eventregistry data model
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:176) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:101) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1884) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1284) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:267) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1614) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1571) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1352) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887) ~[spring-beans-5.3.15.jar:5.3.15]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791) ~[spring-beans-5.3.15.jar:5.3.15]
	... 19 common frames omitted
Caused by: org.flowable.common.engine.api.FlowableException: Error initialising eventregistry data model
	at org.flowable.common.engine.impl.db.LiquibaseBasedSchemaManager.initSchema(LiquibaseBasedSchemaManager.java:88) ~[flowable-engine-common-6.7.2.jar:6.7.2]
	at org.flowable.eventregistry.impl.db.EventDbSchemaManager.initSchema(EventDbSchemaManager.java:36) ~[flowable-event-registry-6.7.2.jar:6.7.2]
	at org.flowable.eventregistry.impl.cmd.SchemaOperationsEventRegistryEngineBuild.execute(SchemaOperationsEventRegistryEngineBuild.java:29) ~[flowable-event-registry-6.7.2.jar:6.7.2]
	at org.flowable.eventregistry.impl.cmd.SchemaOperationsEventRegistryEngineBuild.execute(SchemaOperationsEventRegistryEngineBuild.java:24) ~[flowable-event-registry-6.7.2.jar:6.7.2]
	at org.flowable.common.engine.impl.interceptor.DefaultCommandInvoker.execute(DefaultCommandInvoker.java:22) ~[flowable-engine-common-6.7.2.jar:6.7.2]
	at org.flowable.common.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:53) ~[flowable-engine-common-6.7.2.jar:6.7.2]
	at org.flowable.common.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:105) ~[flowable-engine-common-6.7.2.jar:6.7.2]
	at org.flowable.common.spring.SpringTransactionInterceptor.lambda$execute$0(SpringTransactionInterceptor.java:57) ~[flowable-spring-common-6.7.2.jar:6.7.2]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.3.15.jar:5.3.15]
	at org.flowable.common.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:57) ~[flowable-spring-common-6.7.2.jar:6.7.2]
	at org.flowable.common.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30) ~[flowable-engine-common-6.7.2.jar:6.7.2]
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56) ~[flowable-engine-common-6.7.2.jar:6.7.2]
	at org.flowable.eventregistry.impl.EventRegistryEngineImpl.<init>(EventRegistryEngineImpl.java:47) ~[flowable-event-registry-6.7.2.jar:6.7.2]
	at org.flowable.eventregistry.impl.EventRegistryEngineConfiguration.buildEventRegistryEngine(EventRegistryEngineConfiguration.java:195) ~[flowable-event-registry-6.7.2.jar:6.7.2]
	at org.flowable.eventregistry.spring.SpringEventRegistryEngineConfiguration.buildEventRegistryEngine(SpringEventRegistryEngineConfiguration.java:73) ~[flowable-event-registry-spring-6.7.2.jar:6.7.2]
	at org.flowable.eventregistry.spring.configurator.SpringEventRegistryConfigurator.initEventRegistryEngine(SpringEventRegistryConfigurator.java:57) ~[flowable-event-registry-spring-configurator-6.7.2.jar:6.7.2]
	at org.flowable.eventregistry.spring.configurator.SpringEventRegistryConfigurator.configure(SpringEventRegistryConfigurator.java:47) ~[flowable-event-registry-spring-configurator-6.7.2.jar:6.7.2]
	at org.flowable.common.engine.impl.AbstractEngineConfiguration.configuratorsAfterInit(AbstractEngineConfiguration.java:1109) ~[flowable-engine-common-6.7.2.jar:6.7.2]
	at org.flowable.app.engine.AppEngineConfiguration.init(AppEngineConfiguration.java:237) ~[flowable-app-engine-6.7.2.jar:6.7.2]
	at org.flowable.app.engine.AppEngineConfiguration.buildAppEngine(AppEngineConfiguration.java:193) ~[flowable-app-engine-6.7.2.jar:6.7.2]
	at org.flowable.app.spring.SpringAppEngineConfiguration.buildAppEngine(SpringAppEngineConfiguration.java:66) ~[flowable-app-engine-spring-6.7.2.jar:6.7.2]
	at org.flowable.app.spring.AppEngineFactoryBean.getObject(AppEngineFactoryBean.java:58) ~[flowable-app-engine-spring-6.7.2.jar:6.7.2]
	at org.flowable.app.spring.AppEngineFactoryBean.getObject(AppEngineFactoryBean.java:31) ~[flowable-app-engine-spring-6.7.2.jar:6.7.2]
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:169) ~[spring-beans-5.3.15.jar:5.3.15]
	... 31 common frames omitted
Caused by: org.flowable.common.engine.api.FlowableException: Error updating eventregistry engine tables
	at org.flowable.common.engine.impl.db.LiquibaseBasedSchemaManager.schemaUpdate(LiquibaseBasedSchemaManager.java:129) ~[flowable-engine-common-6.7.2.jar:6.7.2]
	at org.flowable.eventregistry.impl.db.EventDbSchemaManager.schemaUpdate(EventDbSchemaManager.java:63) ~[flowable-event-registry-6.7.2.jar:6.7.2]
	at liquibase.Scope.lambda$child$0(Scope.java:177) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Scope.child(Scope.java:186) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Scope.child(Scope.java:176) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Scope.child(Scope.java:155) ~[liquibase-core-4.5.0.jar:na]
	at org.flowable.common.engine.impl.db.LiquibaseBasedSchemaManager.runForLiquibase(LiquibaseBasedSchemaManager.java:93) ~[flowable-engine-common-6.7.2.jar:6.7.2]
	at org.flowable.common.engine.impl.db.LiquibaseBasedSchemaManager.initSchema(LiquibaseBasedSchemaManager.java:81) ~[flowable-engine-common-6.7.2.jar:6.7.2]
	... 54 common frames omitted
Caused by: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set org/flowable/eventregistry/db/liquibase/flowable-eventregistry-db-changelog.xml::2::flowable:
     Reason: liquibase.exception.DatabaseException: Table 'workflow.flw_channel_definition' doesn't exist [Failed SQL: (1146) ALTER TABLE workflow.FLW_CHANNEL_DEFINITION ADD TYPE_ VARCHAR(255) NULL]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:124) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Liquibase.lambda$null$0(Liquibase.java:265) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:177) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Scope.child(Scope.java:186) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Scope.child(Scope.java:176) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Scope.child(Scope.java:155) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Scope.child(Scope.java:239) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:264) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:177) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Scope.child(Scope.java:186) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Scope.child(Scope.java:176) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Scope.child(Scope.java:155) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Liquibase.runInScope(Liquibase.java:2404) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:211) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:197) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:193) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:185) ~[liquibase-core-4.5.0.jar:na]
	at org.flowable.common.engine.impl.db.LiquibaseBasedSchemaManager.schemaUpdate(LiquibaseBasedSchemaManager.java:127) ~[flowable-engine-common-6.7.2.jar:6.7.2]
	... 61 common frames omitted
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set org/flowable/eventregistry/db/liquibase/flowable-eventregistry-db-changelog.xml::2::flowable:
     Reason: liquibase.exception.DatabaseException: Table 'workflow.flw_channel_definition' doesn't exist [Failed SQL: (1146) ALTER TABLE workflow.FLW_CHANNEL_DEFINITION ADD TYPE_ VARCHAR(255) NULL]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:695) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:49) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:111) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:177) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Scope.child(Scope.java:186) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Scope.child(Scope.java:176) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Scope.child(Scope.java:155) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:110) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:177) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Scope.child(Scope.java:186) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Scope.child(Scope.java:176) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Scope.child(Scope.java:155) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Scope.child(Scope.java:239) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:94) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:177) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Scope.child(Scope.java:186) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Scope.child(Scope.java:176) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Scope.child(Scope.java:155) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Scope.child(Scope.java:239) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.Scope.child(Scope.java:243) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:66) ~[liquibase-core-4.5.0.jar:na]
	... 78 common frames omitted
Caused by: liquibase.exception.DatabaseException: Table 'workflow.flw_channel_definition' doesn't exist [Failed SQL: (1146) ALTER TABLE workflow.FLW_CHANNEL_DEFINITION ADD TYPE_ VARCHAR(255) NULL]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:393) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:82) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:150) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1279) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1261) ~[liquibase-core-4.5.0.jar:na]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:660) ~[liquibase-core-4.5.0.jar:na]
	... 98 common frames omitted
Caused by: java.sql.SQLSyntaxErrorException: Table 'workflow.flw_channel_definition' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:763) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-4.0.3.jar:na]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:389) ~[liquibase-core-4.5.0.jar:na]
	... 103 common frames omitted

**Comment by quaider** [comment]
mysql version: 5.7.26

**Comment by quaider** [comment]
i can only make my application running successfully with the flowing config, with many module disabled, is it correct?
``` yaml
flowable:
  database-schema-update: true
  database-schema: workflow
  eventregistry:
    enabled: false
  dmn:
    enabled: false
  content:
    enabled: false
  cmmn:
    enabled: false
```

**Comment by filiphr** [comment]
Are you starting with an empty database?

**Comment by quaider** [comment]
> Are you starting with an empty database?

yes,  and i tried to delete and create an empty database many times

**Comment by filiphr** [comment]
Can you please try removing the `flowable.database-schema` property and try? It would also be good to share the entire log file from the bootup.

**Comment by quaider** [comment]
> Can you please try removing the `flowable.database-schema` property and try? It would also be good to share the entire log file from the bootup.

same exception _Table 'ww.flw_channel_definition' doesn't exist_

[boot.log](https://github.com/flowable/flowable-engine/files/8620374/boot.log)

**Comment by quaider** [comment]
![image](https://user-images.githubusercontent.com/12459496/166682842-161cebfe-8e77-4834-92f5-c7fa566e17b1.png)

**Comment by linyuchi2017** [comment]
Have you solved this problem

**Comment by HaiyangLiang** [comment]
The driver uses lowercase by default when checking the mysql table, but the table names in flowable sql are all uppercase, you can set the table name to use all lowercase in the mysql configuration file.

`
[mysqld] 
lower_case_table_names=1
`

**Comment by HaiyangLiang** [comment]
The driver uses lowercase by default when checking the mysql table, but the table names in flowable sql are all uppercase, you can set the table name to use all lowercase in the mysql configuration file.

```
[mysqld] 
lower_case_table_names=1
```
