### ISSUE TITLE
NPE when trying to import several WSDLs used by different service tasks

### ISSUE THREAD

**Issue by cdeneux** [flowable/flowable-engine#333]
With a BPMN definition containing several WSDL imports as:

    <definitions ...>
      <import location="classpath:su/multi-start/archivageService.wsdl" namespace="http://petals.ow2.org/se-flowable/unit-test/multi-start/archivageService"
      importType="http://schemas.xmlsoap.org/wsdl/" />
      <import location="classpath:su/multi-start/notifyService.wsdl" namespace="http://petals.ow2.org/se-flowable/unit-test/multi-start/notifyService"
      importType="http://schemas.xmlsoap.org/wsdl/" />
    </definitions>

the following NPE occurs when associated service tasks are executed:
```
2017/04/07 11:18:43,301 GMT+0100 SEVERE [org.flowable.engine.impl.asyncexecutor.ExecuteAsyncRunnable] : Job 19 failed
java.lang.NullPointerException
    at org.flowable.engine.impl.bpmn.data.ItemDefinition.createInstance(ItemDefinition.java:42)
    at org.flowable.engine.impl.bpmn.behavior.WebServiceActivityBehavior.initializeIoSpecification(WebServiceActivityBehavior.java:177)
    at org.flowable.engine.impl.bpmn.behavior.WebServiceActivityBehavior.execute(WebServiceActivityBehavior.java:120)
    at org.flowable.engine.impl.agenda.ContinueProcessOperation.executeActivityBehavior(ContinueProcessOperation.java:197)
    ...
```

I think that this problem is due to the usage of a bad key nature in method `org.flowable.engine.impl.bpmn.behavior.WebServiceActivityBehavior.fillImporterInfo(...)`. The import type (WSDL, XSD, ...) is used as key for map `xmlImporterMap` (that seems exist to avoid importing the same import several times). IMO, the namespace of the import should be used as key.

**Comment by tijsrademakers** [comment]
Merged the PR, thanks
