### ISSUE TITLE
insert into ACT_RU_EXECUTION    Lock wait timeout exceeded; try restarting transaction

### ISSUE THREAD

**Issue by muwanou** [flowable/flowable-engine#3350]
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
org.apache.ibatis.exceptions.PersistenceException: 
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:200)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185)
	at org.flowable.common.engine.impl.db.DbSqlSession.flushBulkInsert(DbSqlSession.java:473)
	at org.flowable.common.engine.impl.db.DbSqlSession.flushInsertEntities(DbSqlSession.java:429)
	at org.flowable.common.engine.impl.db.DbSqlSession.flushInserts(DbSqlSession.java:406)
	at org.flowable.common.engine.impl.db.DbSqlSession.flush(DbSqlSession.java:291)
	at org.flowable.common.engine.impl.interceptor.CommandContext.flushSessions(CommandContext.java:191)
	at org.flowable.common.engine.impl.interceptor.CommandContext.close(CommandContext.java:61)
	at org.flowable.common.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:81)
	at org.flowable.common.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:51)
	at org.flowable.common.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30)
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56)
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51)

**Comment by muwanou** [comment]
flowable version 6.4.2
mysql version 5.6.30-log 
innodb_lock_wait_timeout   10

**Comment by mbjex** [comment]
Experiencing the exact same issue on flowable 6.5.0
For me, sometimes it happens with ACT_RU_EXECUTION and sometimes with ACT_RU_ACTINST:

> ### Error updating database.  Cause: com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
### The error may exist in org/flowable/db/mapping/entity/ActivityInstance.xml
### The error may involve org.flowable.engine.impl.persistence.entity.ActivityInstanceEntityImpl.bulkInsertActivityInstance-Inline
### The error occurred while setting parameters
### SQL: insert into ACT_RU_ACTINST (...

**Comment by muwanou** [comment]
这是来自华博QQ邮箱的自动回复邮件，我会尽快回复你。

**Comment by lkzlee** [comment]
+1 ，how to resolve？

**Comment by gcamaralooplex** [comment]
Was anyone able to resolve this?

**Comment by Kangmin-He** [comment]
same issue, sometimes it also happens with ACT_RU_VARIABLE, anyone has resolved it?

**Comment by muwanou** [comment]
这是来自华博QQ邮箱的自动回复邮件，我会尽快回复你。

**Comment by whnsdad** [comment]
same issue, sometimes it also happens with ACT_HI_TASKINST and ACT_HI_ACTINST

**Comment by muwanou** [comment]
这是来自华博QQ邮箱的自动回复邮件，我会尽快回复你。
