### ISSUE TITLE
org.activiti.engine.ActivitiException: UserTask should not be signalled before complete

### ISSUE THREAD

**Issue by hanumanthraju** [flowable/flowable-engine#3596]
Hi Team,

When moving task to next status getting below error: **UserTask should not be signalled before complete**
2023-01-27T20:38:26.083 ERROR [io-8000-exec-10] o.a.e.impl.interceptor.CommandContext    []: Error while closing command context

org.activiti.engine.ActivitiException: UserTask should not be signalled before complete
 at org.activiti.engine.impl.bpmn.behavior.UserTaskActivityBehavior.trigger(UserTaskActivityBehavior.java:266)
 at org.activiti.engine.impl.agenda.TriggerExecutionOperation.run(TriggerExecutionOperation.java:38)
 at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:73)
 at org.activiti.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:57)
 at org.activiti.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:42)
 at org.activiti.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:48)
 at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:59)
 at org.activiti.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47)
 at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
 at org.activiti.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)
 at org.activiti.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:29)
 at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:44)
 at org.activiti.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:39)
 at org.activiti.engine.impl.TaskServiceImpl.complete(TaskServiceImpl.java:202)
 at java.util.ArrayList.forEach(ArrayList.java:1259)

Activity version : **7.1.0.M6**

Thank you,
Raju

**Comment by tijsrademakers** [comment]
This is not the Activiti project, this is Flowable, please report the issue on the correct project
