### ISSUE TITLE
ExecutionTreeNode toString() triggers FlowableException related to v5 process definition

### ISSUE THREAD

**Issue by aaronkavlie-wf** [flowable/flowable-engine#363]
I'm testing `ExecutionTreeUtil.buildExecutionTree()`. Despite triggering deployment of the process definition within the body of the test, I get this error when calling the node's `toString()` method:

```
org.flowable.engine.common.api.FlowableException: Found Flowable 5 process definition, but no compatibility handler on the classpath
	at org.flowable.engine.impl.util.Flowable5Util.getFlowable5CompatibilityHandler(Flowable5Util.java:130)
	at org.flowable.engine.impl.util.ProcessDefinitionUtil.getProcess(ProcessDefinitionUtil.java:55)
	at org.flowable.engine.impl.persistence.entity.ExecutionEntityImpl.getCurrentFlowElement(ExecutionEntityImpl.java:260)
	at org.flowable.engine.debug.ExecutionTreeNode.getCurrentFlowElementId(ExecutionTreeNode.java:111)
	at org.flowable.engine.debug.ExecutionTreeNode.internalToString(ExecutionTreeNode.java:93)
	at org.flowable.engine.debug.ExecutionTreeNode.toString(ExecutionTreeNode.java:85)
	at com.workiva.workflow.SendForReviewTest.lambda$testSendForReview$2(SendForReviewTest.java:191)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.workiva.workflow.SendForReviewTest.testSendForReview(SendForReviewTest.java:188)
[...]
```

I can't find anything in my test code that should cause the process definition to be deployed as a Flowable v5 process. The [logic for determining that it's a v5 process definition](https://github.com/flowable/flowable-engine/blob/master/modules/flowable-engine/src/main/java/org/flowable/engine/impl/util/ProcessDefinitionUtil.java#L54-L55) seems questionable.

**Comment by martin-grofcik** [comment]
Hi Aaron,

the problem is 
`        if (Context.getProcessEngineConfiguration() == null) {
            return Flowable5Util.getFlowable5CompatibilityHandler().getProcessDefinitionProcessObject(processDefinitionId);
`
- No process engine configuration in the context. In that case Flowable6 is supposed to deal with version5 process definition.
The solution is just easy. Set 
`Context.setProcessEngineConfiguration(processEngineConfig)`
before your method call.

**Comment by tijsrademakers** [comment]
Hi Aaron,

Are you running the ExecutionTreeUtil.buildExecutionTree() logic from within a transaction / Command? This is not a util class that is meant to be used outside a transaction / Command. You can easily run one using something like:

`
managementService.executeCommand(new Command<Void>() {

    @Override
    public Void execute(CommandContext commandContext) {
        ExecutionTreeUtil.buildExecutionTree(execution);
        return null;
    }
});
`

Then the Context instance is there as well.

**Comment by aaronkavlie-wf** [comment]
> Are you running the ExecutionTreeUtil.buildExecutionTree() logic from within a transaction / Command?

No, I'll give `managementService.executeCommand()` a try. Thanks.

It seems that this is a case of a valid error condition, but the wrong error message.
Some docs and API improvements for building an execution tree would help, but I'm not sure that this is really meant to be a public API.
