### ISSUE TITLE
Can't run flowable-ui.war with database driver

### ISSUE THREAD

**Issue by dhois** [flowable/flowable-engine#3652]
**Describe the bug**
Hello! I followed the documentation of running `flowable-ui.war` in standalone mode. The documentation states that if you want to change the database-driver you can use the property `-Dloader.path=/location/to/your/driverfolder`. If I try that, the application crashes with the following exception:

```common
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is
// ...
Caused by: java.lang.IllegalStateException: Cannot load driver class: com.microsoft.sqlserver.jdbc.SQLServerDriver
        at org.springframework.util.Assert.state(Assert.java:97) ~[spring-core-5.3.24.jar!/:5.3.24]
        at org.springframework.boot.autoconfigure.jdbc.DataSourceProperties.determineDriverClassName(DataSourceProperties.java:171) ~[spring-boot-autoconfigure-2.7.6.jar!/:2.7.6]
        at org.springframework.boot.autoconfigure.jdbc.DataSourceProperties.initializeDataSourceBuilder(DataSourceProperties.java:123) ~[spring-boot-autoconfigure-2.7.6.jar!/:2.7.6]
        at org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration.createDataSource(DataSourceConfiguration.java:48) ~[spring-boot-autoconfigure-2.7.6.jar!/:2.7.6]
        at org.springframework.boot.autoconfigure.jdbc.DataSourceConfiguration$Hikari.dataSource(DataSourceConfiguration.java:90) ~[spring-boot-autoconfigure-2.7.6.jar!/:2.7.6]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.24.jar!/:5.3.24]
        ... 111 common frames omitted
```

**Code**
I use the following command to run `flowable-ui.war`

```console
java -Dloader.path=./driver -jar flowable-ui.war --spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver --spring.datasource.url="jdbc:sqlserver://localhost:1433;databaseName=flowabledb" --spring.datasource.username=flowable --spring.datasource.password=flowable
```

My folder 'driver' is at the same level as the `flowable-ui.war` with a file `mssql-jdbc-12.2.0.jre11.jar` in it

**Additional context**
This issue seems very similar, if not identical, to the following two issues: [Issue-2900](https://github.com/flowable/flowable-engine/issues/2900) and [Issue-1394](https://github.com/flowable/flowable-engine/issues/1394). Is there something missing in the documentation, or did I do something wrong?

**Comment by filiphr** [comment]
Using the Spring Boot `loader.path` property does not work for executable WAR applications like the `flowable-ui.war`. You need find an alternative way to add the driver on the classpath of the application. If you build your own flowable-ui.jar application then you can use the `loader.path` property.
