### ISSUE TITLE
PropertyNotFoundException: Target unreachable, base expression '<method>' resolved to null

### ISSUE THREAD

**Issue by RonaldTrump78** [flowable/flowable-engine#391]
Hi,
I have an instance of com.fasterxml.jackson.databind.node.ArrayNode in my context. Now I want to evaluate an expression as following "array.get(0).asText()". From time to time the expression runs in the following exception:

Caused by: org.activiti.engine.impl.javax.el.PropertyNotFoundException: Target unreachable, base expression '<method>' resolved to null
	at org.activiti.engine.impl.juel.AstMethod.invoke(AstMethod.java:92)
	at org.activiti.engine.impl.juel.AstMethod.eval(AstMethod.java:86)
	at org.activiti.engine.impl.juel.AstBinary$SimpleOperator.eval(AstBinary.java:27)
	at org.activiti.engine.impl.juel.AstBinary.eval(AstBinary.java:106)
	at org.activiti.engine.impl.juel.AstEval.eval(AstEval.java:50)
	at org.activiti.engine.impl.juel.AstNode.getValue(AstNode.java:26)
	at org.activiti.engine.impl.juel.TreeValueExpression.getValue(TreeValueExpression.java:114)
	at org.activiti.engine.impl.delegate.ExpressionGetInvocation.invoke(ExpressionGetInvocation.java:33)
	at org.activiti.engine.impl.delegate.DelegateInvocation.proceed(DelegateInvocation.java:37)

Problematic statement can be found in class org.activiti.engine.impl.javax.el.BeanELResolver, method findMethod. The method getMethods returns an unpredictable ordered list of methods. So if the get(String) comes before get(int), null is returned on the invocation of that method and the aforementioned exception is raised on the evaluation of method "asText". The getMethod(String, Class...) might solve the issue, but the types array passed to the findMethod is null in my case, as it won't be passed by the AstMethod.eval method. Only for AstString and AstBoolean, but not for AstNumber a types array is initialized.
Best regards, Ronald

**Comment by tijsrademakers** [comment]
Hi Ronald,

This is a problem with the JUEL implementation, because in JUEL 2.2 this is still implemented like this. I would advise to use a Helper class and use that in your expression instead of working with the ArrayNode directly.
