### ISSUE TITLE
Flowable 7.1.0 problems on postgres database

### ISSUE THREAD

**Issue by myyychal** [flowable/flowable-engine#3984]
**Describe the bug**
When starting my application that uses flowable in 7.1.0 on postgres database I get error:
```
2024-10-24 17:42:54,972 runner-stwmscw6-project-15310-concurrent-0 quarkus-run.jar[1131] ERROR [org.flo.com.eng.imp.int.CommandContext] (main) Error while closing command context: org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.apache.ibatis.type.TypeException: Could not set parameters for mapping: ParameterMapping{property='lockOwner', mode=IN, javaType=class java.lang.String, jdbcType=NVARCHAR, numericScale=null, resultMapId='null', jdbcTypeName='null', expression='null'}. Cause: org.apache.ibatis.type.TypeException: Error setting non null for parameter #1 with JdbcType NVARCHAR . Try setting a different JdbcType for this parameter or a different configuration property. Cause: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgPreparedStatement.setNString(int, String) is not yet implemented.
### The error may exist in org/flowable/job/service/db/mapping/entity/Job.xml
### The error may involve org.flowable.job.service.impl.persistence.entity.JobEntityImpl.selectJobByQueryCriteria-Inline
### The error occurred while setting parameters
### SQL: SELECT RES.*                     from ACT_RU_JOB RES          WHERE  RES.LOCK_OWNER_ = ?                order by RES.ID_ asc
### Cause: org.apache.ibatis.type.TypeException: Could not set parameters for mapping: ParameterMapping{property='lockOwner', mode=IN, javaType=class java.lang.String, jdbcType=NVARCHAR, numericScale=null, resultMapId='null', jdbcTypeName='null', expression='null'}. Cause: org.apache.ibatis.type.TypeException: Error setting non null for parameter #1 with JdbcType NVARCHAR . Try setting a different JdbcType for this parameter or a different configuration property. Cause: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgPreparedStatement.setNString(int, String) is not yet implemented.
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:156)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:142)
	at org.flowable.common.engine.impl.db.DbSqlSession.selectListWithRawParameter(DbSqlSession.java:284)
	at org.flowable.common.engine.impl.db.DbSqlSession.selectListWithRawParameter(DbSqlSession.java:247)
	at org.flowable.common.engine.impl.db.DbSqlSession.selectList(DbSqlSession.java:171)
	at org.flowable.job.service.impl.persistence.entity.data.impl.MybatisJobDataManager.findJobsByQueryCriteria(MybatisJobDataManager.java:113)
	at org.flowable.job.service.impl.persistence.entity.JobEntityManagerImpl.findJobsByQueryCriteria(JobEntityManagerImpl.java:72)
	at org.flowable.job.service.impl.cmd.UnacquireOwnedJobsCmd.execute(UnacquireOwnedJobsCmd.java:54)
	at org.flowable.job.service.impl.cmd.UnacquireOwnedJobsCmd.execute(UnacquireOwnedJobsCmd.java:25)
	at org.flowable.engine.impl.interceptor.CommandInvoker$1.run(CommandInvoker.java:73)
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:179)
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:124)
	at org.flowable.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:78)
	at my.app.errorhandling.ActivitiErrorHandlingCommandInterceptor.execute(ActivitiErrorHandlingCommandInterceptor.java:137)
	at org.flowable.engine.impl.interceptor.BpmnOverrideContextInterceptor.execute(BpmnOverrideContextInterceptor.java:26)
	at org.flowable.common.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:53)
	at org.flowable.common.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:105)
	at org.flowable.common.engine.impl.interceptor.JtaTransactionInterceptor.execute(JtaTransactionInterceptor.java:66)
	at org.flowable.common.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30)
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56)
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51)
	at org.flowable.job.service.impl.asyncexecutor.AbstractAsyncExecutor.unlockOwnedJobs(AbstractAsyncExecutor.java:81)
	at org.flowable.job.service.impl.asyncexecutor.DefaultAsyncJobExecutor.startAdditionalComponents(DefaultAsyncJobExecutor.java:111)
	at org.flowable.job.service.impl.asyncexecutor.AbstractAsyncExecutor.start(AbstractAsyncExecutor.java:105)
	at org.flowable.engine.impl.ProcessEngineImpl.startExecutors(ProcessEngineImpl.java:98)
	at org.flowable.engine.impl.cfg.ProcessEnginePostEngineBuildConsumer.accept(ProcessEnginePostEngineBuildConsumer.java:41)
	at org.flowable.engine.impl.cfg.ProcessEnginePostEngineBuildConsumer.accept(ProcessEnginePostEngineBuildConsumer.java:26)
	at org.flowable.common.engine.impl.AbstractBuildableEngineConfiguration.buildEngine(AbstractBuildableEngineConfiguration.java:32)
	at org.flowable.engine.ProcessEngineConfiguration.buildProcessEngine(ProcessEngineConfiguration.java:164)
	at my.app.activiti.ActivitiBpmEngine.<init>(ActivitiBpmEngine.java:176)
	at my.app.BpmServicesImpl.<init>(BpmServicesImpl.java:104)
	at my.app.BpmServicesCoordinator.newServices(BpmServicesCoordinator.java:50)
	at my.app.BpmServicesCoordinator.createForDomain(BpmServicesCoordinator.java:104)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at my.app.BpmServicesCoordinator.forDomain(BpmServicesCoordinator.java:97)
	at my.app.BpmServicesProviderImpl.forDomain(BpmServicesProviderImpl.java:20)
	at my.app.BpmServices.forDomain(BpmServices.java:52)
	at my.app.BpmServicesBean.lambda$init$0(BpmServicesBean.java:37)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1116)
	at my.app.BpmServicesBean.init(BpmServicesBean.java:34)
	at my.app.BpmServicesBean_Observer_init_0c4uIHcn31tuqm6m-V2AskQoMik.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:351)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:333)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:80)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:155)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:106)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
Caused by: org.apache.ibatis.type.TypeException: Could not set parameters for mapping: ParameterMapping{property='lockOwner', mode=IN, javaType=class java.lang.String, jdbcType=NVARCHAR, numericScale=null, resultMapId='null', jdbcTypeName='null', expression='null'}. Cause: org.apache.ibatis.type.TypeException: Error setting non null for parameter #1 with JdbcType NVARCHAR . Try setting a different JdbcType for this parameter or a different configuration property. Cause: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgPreparedStatement.setNString(int, String) is not yet implemented.
	at org.apache.ibatis.scripting.defaults.DefaultParameterHandler.setParameters(DefaultParameterHandler.java:92)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.parameterize(PreparedStatementHandler.java:97)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.parameterize(RoutingStatementHandler.java:65)
	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:91)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:64)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:336)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:158)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:110)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:90)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:154)
	... 60 more
Caused by: org.apache.ibatis.type.TypeException: Error setting non null for parameter #1 with JdbcType NVARCHAR . Try setting a different JdbcType for this parameter or a different configuration property. Cause: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgPreparedStatement.setNString(int, String) is not yet implemented.
	at org.apache.ibatis.type.BaseTypeHandler.setParameter(BaseTypeHandler.java:76)
	at org.apache.ibatis.scripting.defaults.DefaultParameterHandler.setParameters(DefaultParameterHandler.java:90)
	... 69 more
Caused by: java.sql.SQLFeatureNotSupportedException: Method org.postgresql.jdbc.PgPreparedStatement.setNString(int, String) is not yet implemented.
	at org.postgresql.Driver.notImplemented(Driver.java:743)
	at org.postgresql.jdbc.PgPreparedStatement.setNString(PgPreparedStatement.java:1554)
	at io.agroal.pool.wrapper.PreparedStatementWrapper.setNString(PreparedStatementWrapper.java:451)
	at org.apache.ibatis.type.NStringTypeHandler.setNonNullParameter(NStringTypeHandler.java:31)
	at org.apache.ibatis.type.NStringTypeHandler.setNonNullParameter(NStringTypeHandler.java:26)
	at org.apache.ibatis.type.BaseTypeHandler.setParameter(BaseTypeHandler.java:74)
	... 70 more
```

**Expected behavior**
My app starts

**Code**
If applicable, add the code that you are using when having the issue.

**Additional context**
I am using Flowable version 7.1.0 and quarkus (3.11.3) on POSTGRES datablase (works on oracle). I see that there were changes in mybatis xml files changing type from VARCHAR to NVARCHAR.

**Comment by filiphr** [comment]
Looking at 

```
at org.apache.ibatis.type.NStringTypeHandler.setNonNullParameter(NStringTypeHandler.java:31)
```

It seems like the `NStringTypeHandler` is used for setting parameters. However, what should be used is `FlowableStringTypeHandler`. Can you please share how you are creating an instance of  the `ProcessEngineConfiguration`

**Comment by myyychal** [comment]
I am doing it like that:
```
    public ProcessEngineConfiguration loadConfig() {
        ProcessEngineConfiguration activitiConfig = loadBasicConfig();

        BpmDatabaseConfiguration engineDatabase = config.engineDatabase();
        activitiConfig.setClassLoader(ActivitiConfigLoader.class.getClassLoader());
        activitiConfig.setDatabaseTablePrefix(engineDatabase.tablePrefix().toString());
        boolean useHistory = config.historyEnabled();
        activitiConfig.setDbHistoryUsed(useHistory);
        if (!useHistory) {
            activitiConfig.setHistoryLevel(HistoryLevel.NONE);
        }

        if (activitiConfig instanceof JtaProcessEngineConfiguration) {
            JtaProcessEngineConfiguration jtaConfig = (JtaProcessEngineConfiguration) activitiConfig;
            setupTransactionManager(jtaConfig);
        }

        activitiConfig.setDatabaseSchemaUpdate("NO_CHECK");
        SqlDialectHandler.SqlDialect dialect = engineDatabase.databaseDialect();
        if (dialect.equals(SqlDialect.ORACLE)) {
            activitiConfig.setDatabaseType(dialect.getActivitiDatabaseType());
            activitiConfig.setJdbcDriver("oracle.jdbc.driver.OracleDriver");
        } else if (dialect.equals(SqlDialect.POSTGRES)) {
            activitiConfig.setDatabaseType(dialect.getActivitiDatabaseType());
            activitiConfig.setJdbcDriver("org.postgresql.Driver");
        } else {
            throw new InvalidConfigurationException("Could not set dialect different than Oracle or Postgres ");
        }

        Optional<String> dsName = engineDatabase.datasourceName();
        Optional<String> quarkusDatasourceName = engineDatabase.quarkusDatasourceName();

        if (quarkusDatasourceName.isPresent() && QuarkusDatabaseSelector.isQuarkusDataSourceAvailable()) {
            activitiConfig.setDataSource(engineDatabase.datasource());
        } else if (dsName.isPresent()) {
            activitiConfig.setDataSourceJndiName(dsName.get());
        } else {
            Supplier<RuntimeException> ex = () -> new RuntimeException("Missing Activiti database config");
            activitiConfig.setJdbcUrl(engineDatabase.connectionUrl().orElseThrow(ex));
            activitiConfig.setJdbcUsername(engineDatabase.connectionUsername().orElseThrow(ex));
            activitiConfig.setJdbcPassword(engineDatabase.connectionPassword().orElseThrow(ex));
        }

        if (activitiConfig instanceof ProcessEngineConfigurationImpl) {
            Optional<DeploymentCache<ProcessDefinitionCacheEntry>> definitionsCache = config.processDefinitionsCache()
                    .map(BpmConfiguredDeploymentCache::new);

            Optional<DeploymentCache<Object>> knowledgeBaseCache = config.knowledgeBaseCache()
                    .map(BpmConfiguredDeploymentCache::new);

            ProcessEngineConfigurationImpl configImpl = (ProcessEngineConfigurationImpl) activitiConfig;

            configImpl.setProcessDefinitionCache(definitionsCache.orElseGet(BpmDeploymentCache::new));
            configImpl.setKnowledgeBaseCache(knowledgeBaseCache.orElseGet(BpmDeploymentCache::new));
            setBpmnModelCache(configImpl);
        }


        return activitiConfig;
    }
```
So it's loaded from a file (method `loadBasicConfig()`) which first line looks like this:
```
    <bean id="processEngineConfiguration" class="com.comarch.oss.bpm.activiti.config.CustomJtaProcessEngineConfiguration">
```
and CustomJtaProcessEngineConfiguration looks like this:
```
public class CustomJtaProcessEngineConfiguration extends JtaProcessEngineConfiguration {

    private static final String PROPERTY_LOGGING_ENABLED = "bpm.activiti.mybatis.logging";

    @Override
    public Configuration initMybatisConfiguration(Environment environment, Reader reader, Properties properties) {
        Configuration configuration = super.initMybatisConfiguration(environment, reader, properties);

        if (isLoggingEnabled()) {
            configuration.addInterceptor(new QueryLoggingInterceptor());
            configuration.addInterceptor(new UpdateLoggingInterceptor());
            configuration.addInterceptor(new CommitLoggingInterceptor());
            configuration.addInterceptor(new RollbackLoggingInterceptor());
        }
        return configuration;
    }

    private static boolean isLoggingEnabled() {
        return ConfigProvider.getConfig()
                .getOptionalValue(PROPERTY_LOGGING_ENABLED, Boolean.class)
                .orElse(false);
    }

    @Override
    public void initMybatisTypeHandlers(Configuration configuration) {
        TypeHandlerRegistry typeHandlerRegistry = configuration.getTypeHandlerRegistry();
        typeHandlerRegistry.register(VariableType.class, JdbcType.VARCHAR, new IbatisVariableTypeHandler(variableTypes));

        /*
          SQL Statement With High Cursor Count Because Of Bind Mismatch(14)
          Reason (Doc ID 2568532.1) - increase in child cursors while using query with timestamp.
          <p>
          Oracle Support suggest to use setObject() method for Timestamps.
          This is because scale of all Timestamps can not be set to the maximum while using setNull() method.
         */
        if ("oracle".equals(databaseType)) {
            typeHandlerRegistry.register(JdbcType.TIMESTAMP, new CustomDateToTimestampTypeHandler());
            typeHandlerRegistry.register(Date.class, JdbcType.TIMESTAMP, CustomDateToTimestampTypeHandler.class);
            typeHandlerRegistry.register(Object.class, JdbcType.TIMESTAMP, CustomObjectToTimestampTypeHandler.class);
        }
    }

}
```
So I start to think that there might be some changes needed in my class CustomJtaProcessEngineConfiguration...

**Comment by filiphr** [comment]
That's a lot of customizations @myyychal. 

>So I start to think that there might be some changes needed in my class CustomJtaProcessEngineConfiguration...

And you would be right. From what I can see in your `initMybatisTypeHandlers` you are not calling the super method that has quite some logic in Flowable. I would suggest to look into that.

I am going to close the issue as it is not a Flowable problem.

**Comment by myyychal** [comment]
@filiphr , and how about this comment of ours:
```
        /*
          SQL Statement With High Cursor Count Because Of Bind Mismatch(14)
          Reason (Doc ID 2568532.1) - increase in child cursors while using query with timestamp.
          <p>
          Oracle Support suggest to use setObject() method for Timestamps.
          This is because scale of all Timestamps can not be set to the maximum while using setNull() method.
         */
         ```
         where we added custom handlers:
         ```
         @MappedJdbcTypes(JdbcType.TIMESTAMP)
@MappedTypes(Date.class)
public class CustomDateToTimestampTypeHandler extends DateTypeHandler {

    private static final int MAX_ORACLE_BIND_SCALE_FOR_TIMESTAMP = 9;

    @Override
    public void setParameter(PreparedStatement ps, int i, Date parameter, JdbcType jdbcType) {
        if (parameter == null) {
            handleNullParameter(ps, i, jdbcType);
        } else {
            handleNotNullParameter(ps, i, parameter, jdbcType);
        }
    }

    private void handleNullParameter(PreparedStatement ps, int i, JdbcType jdbcType) {
        if (jdbcType == null) {
            throw new TypeException("JDBC requires that the JdbcType must be specified for all nullable parameters.");
        }
        try {
            ps.setObject(i, null, jdbcType.TYPE_CODE, MAX_ORACLE_BIND_SCALE_FOR_TIMESTAMP);
        } catch (SQLException e) {
            throw new TypeException("Error setting null for parameter #" + i + " with JdbcType " + jdbcType + " . "
                    + "Try setting a different JdbcType for this parameter or a different jdbcTypeForNull configuration property. "
                    + "Cause: " + e, e);
        }
    }

    private void handleNotNullParameter(PreparedStatement ps, int i, Date parameter, JdbcType jdbcType) {
        try {
            ps.setObject(i, parameter, jdbcType.TYPE_CODE, MAX_ORACLE_BIND_SCALE_FOR_TIMESTAMP);
        } catch (Exception e) {
            throw new TypeException("Error setting non null for parameter #" + i + " with JdbcType " + jdbcType + " . "
                    + "Try setting a different JdbcType for this parameter or a different configuration property. "
                    + "Cause: " + e, e);
        }
    }

}
```
/**
 * SQL Statement With High Cursor Count Because Of Bind Mismatch(14)
 * Reason (Doc ID 2568532.1) - increase in child cursors while using query with timestamp.
 * <p>
 * Oracle Support suggest to use setObject() method for Timestamps.
 * This is because scale of all Timestamps can not be set to the maximum while using setNull() method.
 */
@MappedJdbcTypes(JdbcType.TIMESTAMP)
@MappedTypes(Object.class)
public class CustomObjectToTimestampTypeHandler extends BaseTypeHandler<Object> {

    private static final int MAX_ORACLE_BIND_SCALE_FOR_TIMESTAMP = 9;

    @Override
    public void setParameter(PreparedStatement ps, int i, Object parameter, JdbcType jdbcType) {
        if (parameter == null) {
            handleNullParameter(ps, i, jdbcType);
        } else {
            handleNotNullParameter(ps, i, parameter, jdbcType);
        }
    }

    private void handleNullParameter(PreparedStatement ps, int i, JdbcType jdbcType) {
        if (jdbcType == null) {
            throw new TypeException("JDBC requires that the JdbcType must be specified for all nullable parameters.");
        }
        try {
            ps.setObject(i, null, jdbcType.TYPE_CODE, MAX_ORACLE_BIND_SCALE_FOR_TIMESTAMP);
        } catch (SQLException e) {
            throw new TypeException("Error setting null for parameter #" + i + " with JdbcType " + jdbcType + " . "
                    + "Try setting a different JdbcType for this parameter or a different jdbcTypeForNull configuration property. "
                    + "Cause: " + e, e);
        }
    }

    private void handleNotNullParameter(PreparedStatement ps, int i, Object parameter, JdbcType jdbcType) {
        try {
            setNonNullParameter(ps, i, parameter, jdbcType);
        } catch (Exception e) {
            throw new TypeException("Error setting non null for parameter #" + i + " with JdbcType " + jdbcType + " . "
                    + "Try setting a different JdbcType for this parameter or a different configuration property. "
                    + "Cause: " + e, e);
        }
    }

    @Override
    public void setNonNullParameter(PreparedStatement ps, int i, Object parameter, JdbcType jdbcType) throws SQLException {
        ps.setObject(i, parameter, jdbcType.TYPE_CODE, MAX_ORACLE_BIND_SCALE_FOR_TIMESTAMP);
    }

    @Override
    public Object getNullableResult(ResultSet rs, String columnName) throws SQLException {
        Timestamp sqlTimestamp = rs.getTimestamp(columnName);
        if (sqlTimestamp != null) {
            return new Date(sqlTimestamp.getTime());
        }
        return null;
    }

    @Override
    public Object getNullableResult(ResultSet rs, int columnIndex) throws SQLException {
        Timestamp sqlTimestamp = rs.getTimestamp(columnIndex);
        if (sqlTimestamp != null) {
            return new Date(sqlTimestamp.getTime());
        }
        return null;
    }

    @Override
    public Object getNullableResult(CallableStatement cs, int columnIndex) throws SQLException {
        Timestamp sqlTimestamp = cs.getTimestamp(columnIndex);
        if (sqlTimestamp != null) {
            return new Date(sqlTimestamp.getTime());
        }
        return null;
    }

}
```
do you think that it might be something to look at as a fix in flowable?
