### ISSUE TITLE
multiInstance subprocess of revoking tasks has bug

### ISSUE THREAD

**Issue by luoyi1029** [flowable/flowable-engine#3999]
**Describe the bug**
In the multiInstance subprocess of departments, 
if Receiver sends A and then withdraws, Receiver sends B and then withdraws, Receiver sends A and A sends B。
error : No outging sequence flow of element 'Activity_1xk5x7b' could be selected for continuing the process， How to solve it?

**Code**
taskService.complete(taskBo.getTaskId(), processVariables);

**Additional context**
Flowable 6.8.1 
![subProcess](https://github.com/user-attachments/assets/0cdcb964-9612-4390-805b-c95bebc4b5fd)

**Comment by luoyi1029** [comment]
16:57:22.349 [http-nio-9001-exec-2] ERROR c.g.c.c.GlobalExceptionAdvice - [validatedFlowableException,111] - 运行时异常:
org.flowable.common.engine.api.FlowableException: No outgoing sequence flow of element 'Activity_1xk5x7b' could be selected for continuing the process
	at org.flowable.engine.impl.agenda.TakeOutgoingSequenceFlowsOperation.leaveFlowNode(TakeOutgoingSequenceFlowsOperation.java:251)
	at org.flowable.engine.impl.agenda.TakeOutgoingSequenceFlowsOperation.handleFlowNode(TakeOutgoingSequenceFlowsOperation.java:155)
	at org.flowable.engine.impl.agenda.TakeOutgoingSequenceFlowsOperation.run(TakeOutgoingSequenceFlowsOperation.java:105)
	at org.flowable.common.engine.impl.AbstractEngineConfiguration.lambda$new$0(AbstractEngineConfiguration.java:138)
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:130)
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:114)
	at org.flowable.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:72)
	at org.flowable.engine.impl.interceptor.BpmnOverrideContextInterceptor.execute(BpmnOverrideContextInterceptor.java:26)
	at org.flowable.common.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:53)
	at org.flowable.common.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:105)
	at org.flowable.common.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:52)
	at org.flowable.common.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30)
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56)
	at org.flowable.common.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51)
	at org.flowable.engine.impl.TaskServiceImpl.complete(TaskServiceImpl.java:223)

**Comment by luoyi1029** [comment]
[process_send_doc-formkey.xml.txt](https://github.com/user-attachments/files/18092690/process_send_doc-formkey.xml.txt)
xml file

**Comment by filiphr** [comment]
>No outgoing sequence flow of element 'Activity_1xk5x7b' could be selected for continuing the process

Based on that error it means that there is no sequence flow that can be taken out of the user task with id 'Activity_1xk5x7b'. I can see that there is one sequence flow out of it. This sequence flow has a condition on it `${flag==11}`, so I assume that the `flag` variable does not have the value of `11` and thus it is not possible to take that flow and there is no other flow that it can go out through.

Can you provide a reproducible example for this?

**Comment by luoyi1029** [comment]
complete() ~ ariables is  {flag:11, gateFlag:103}发自我的手机-------- 原始邮件 --------发件人： Filip Hrisafov ***@***.***>日期： 2024年12月11日周三 17:36收件人： flowable/flowable-engine ***@***.***>抄送： luoyi1029 ***@***.***>, Author ***@***.***>主    题： Re: [flowable/flowable-engine] multiInstance subprocess of revoking tasks has bug (Issue #3999)

No outgoing sequence flow of element 'Activity_1xk5x7b' could be selected for continuing the process

Based on that error it means that there is no sequence flow that can be taken out of the user task with id 'Activity_1xk5x7b'. I can see that there is one sequence flow out of it. This sequence flow has a condition on it ${flag==11}, so I assume that the flag variable does not have the value of 11 and thus it is not possible to take that flow and there is no other flow that it can go out through.
Can you provide a reproducible example for this?

**Comment by luoyi1029** [comment]
complete() ~ variables is  {flag:11, gateFlag:103}.i think variables is right, call complete() is succuss when first to leader B！发自我的手机-------- 原始邮件 --------发件人： Filip Hrisafov ***@***.***>日期： 2024年12月11日周三 17:36收件人： flowable/flowable-engine ***@***.***>抄送： luoyi1029 ***@***.***>, Author ***@***.***>主    题： Re: [flowable/flowable-engine] multiInstance subprocess of revoking tasks has bug (Issue #3999)

No outgoing sequence flow of element 'Activity_1xk5x7b' could be selected for continuing the process

Based on that error it means that there is no sequence flow that can be taken out of the user task with id 'Activity_1xk5x7b'. I can see that there is one sequence flow out of it. This sequence flow has a condition on it ${flag==11}, so I assume that the flag variable does not have the value of 11 and thus it is not possible to take that flow and there is no other flow that it can go out through.
Can you provide a reproducible example for this?

**Comment by luoyi1029** [comment]
to Leader B complete() 
variables = {flag=13, assigneeList=[155], deptId=100, assignee=156, bgsId=125, gateFlag=101}

**Comment by luoyi1029** [comment]
to Leader B complete() 
variables = {flag=13, assigneeList=[155], deptId=100, assignee=156, bgsId=125, gateFlag=101}

**Comment by filiphr** [comment]
@luoyi1029 can you provide a unit test showing this problem?
