### ISSUE TITLE
java.io.NotSerializableException: org.activiti.bpmn.model.BpmnModel

### ISSUE THREAD

**Issue by qiudaoke** [flowable/flowable-engine#481]
hi 
 I use redis store processDefinitionCache, My flowable.cfg.xml like this
<property name="processDefinitionCache">
		<bean class="com.shareniu.shareniu_activiti6.ch2.ShareniuDeploymentCache"></bean>
		</property>
**ShareniuDeploymentCache:**
Jedis jedis=new Jedis("127.0.0.1",6379);
	public ProcessDefinitionCacheEntry get(String id) {
		Object object = cache.get(id);
		if (object !=null) {
			jedis.set(id.getBytes(), ObjectToArrayUtils.toByteArray(object));
		}
		System.out.println(id);
		return null;
	}
error message:
java.io.NotSerializableException: org.activiti.bpmn.model.BpmnModel
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1548)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1509)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
	at com.shareniu.shareniu_activiti6.ch2.ObjectToArrayUtils.toByteArray(ObjectToArrayUtils.java:17)

**Comment by duzhuo** [comment]
Hi, I have the same problem. How did you solve it?

**Comment by linehammer** [comment]
java.io.NotSerializableException can occur when you serialize an inner class instance because serializing such an inner class instance will result in serialization of its associated outer class instance as well. How to solve it?

- If the class is yours, make the class serializable by implementing the interface [java](http://net-informations.com/java/cjava/default.htm).io.Serializable.
- All non primitive members implement Serializable (or are transient instead)
- If your class is an inner class it's either static or the outer class implements Serializable
- If the class is 3rd party, but you don't need it in the serialized form, mark the field as transient

It is important to note that Serialization of inner classes (i.e., nested classes that are not static member classes), including local and anonymous classes, is strongly discouraged.
