### ISSUE TITLE
CXF WSDL Importer can't import element of type base64Binary

### ISSUE THREAD

**Issue by victornoel** [flowable/flowable-engine#482]
I have a WSDL with an element defined of type `s:base64Binary` (from `http://www.w3.org/2001/XMLSchema`).

When I import that WSDL in a process, CxfWSDLImporter is called to import the WSDL and it fails with the following exception:
```
[main] ERROR org.flowable.engine.common.impl.interceptor.AbstractCommandContext - Error while closing command context
org.flowable.engine.common.api.FlowableException: Could not find importer for type http://schemas.xmlsoap.org/wsdl/
	at org.flowable.engine.impl.bpmn.behavior.WebServiceActivityBehavior.fillImporterInfo(WebServiceActivityBehavior.java:280)
	at org.flowable.engine.impl.bpmn.behavior.WebServiceActivityBehavior.fillDefinitionMaps(WebServiceActivityBehavior.java:189)
	at org.flowable.engine.impl.bpmn.behavior.WebServiceActivityBehavior.execute(WebServiceActivityBehavior.java:113)
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.executeActivityBehavior(ContinueProcessOperation.java:197)
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.executeSynchronous(ContinueProcessOperation.java:148)
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.continueThroughFlowNode(ContinueProcessOperation.java:106)
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.run(ContinueProcessOperation.java:72)
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:81)
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:65)
	at org.flowable.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:49)
	at org.flowable.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:51)
	at org.flowable.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:64)
	at org.flowable.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30)
	at org.flowable.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56)
	at org.flowable.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51)
	at org.flowable.engine.impl.RuntimeServiceImpl.startProcessInstanceByKey(RuntimeServiceImpl.java:98)
       ...
```

After some research with the debugger, I found that the following exception was thrown (and ignored, not such a good idea IMHO):
```
org.flowable.engine.common.api.FlowableClassLoadingException: Class not found: byte[]
	at org.flowable.engine.impl.util.ReflectUtil.loadClass(ReflectUtil.java:87)
	at org.flowable.engine.impl.webservice.CxfWSDLImporter._importFields(CxfWSDLImporter.java:213)
	at org.flowable.engine.impl.webservice.CxfWSDLImporter.importFields(CxfWSDLImporter.java:203)
	at org.flowable.engine.impl.webservice.CxfWSDLImporter.importStructure(CxfWSDLImporter.java:192)
	at org.flowable.engine.impl.webservice.CxfWSDLImporter.importTypes(CxfWSDLImporter.java:175)
	at org.flowable.engine.impl.webservice.CxfWSDLImporter.importFrom(CxfWSDLImporter.java:129)
	at org.flowable.engine.impl.webservice.CxfWSDLImporter.importFrom(CxfWSDLImporter.java:87)
	at org.flowable.engine.impl.bpmn.behavior.WebServiceActivityBehavior.fillImporterInfo(WebServiceActivityBehavior.java:273)
	at org.flowable.engine.impl.bpmn.behavior.WebServiceActivityBehavior.fillDefinitionMaps(WebServiceActivityBehavior.java:189)
	at org.flowable.engine.impl.bpmn.behavior.WebServiceActivityBehavior.execute(WebServiceActivityBehavior.java:113)
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.executeActivityBehavior(ContinueProcessOperation.java:197)
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.executeSynchronous(ContinueProcessOperation.java:148)
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.continueThroughFlowNode(ContinueProcessOperation.java:106)
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.run(ContinueProcessOperation.java:72)
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:81)
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:65)
	at org.flowable.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:49)
	at org.flowable.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:51)
	at org.flowable.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:64)
	at org.flowable.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30)
	at org.flowable.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56)
	at org.flowable.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51)
	at org.flowable.engine.impl.RuntimeServiceImpl.startProcessInstanceByKey(RuntimeServiceImpl.java:98)
       ...
Caused by: java.lang.ClassNotFoundException: byte[]
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at org.flowable.engine.impl.util.ReflectUtil.loadClass(ReflectUtil.java:279)
	at org.flowable.engine.impl.util.ReflectUtil.loadClass(ReflectUtil.java:68)
	... 49 more
```

I suppose this is easily fixed by handling arrays of primitives in a special way.

**Comment by tijsrademakers** [comment]
This has no priority in the project, therefore closing the issue.
