### ISSUE TITLE
Form deployment fails: Unrecognized field "editorJson"

### ISSUE THREAD

**Issue by zwets** [flowable/flowable-engine#599]
Deployment fails in current master, seemingly due to forms failing to deploy.

Reproduce:
1. Design a simple model referencing a simple form in the Modeler App. Create an App and add the model to it. Tick `publish` when saving the app. The "Save and close editor" button will appear to do nothing.
2. Untick `publish` to save the model. Click "publish" to deploy the model. A red bar briefly appears and nothing is deployed.
3. Export the App as a zip file, then deploy this using the _Admin App_. Now, the process definitions are deployed but the forms aren't.
4. Extract a single form definition from the zip file, deploy using REST to the `form-api`. This gives a JSON parsing exception and the stack trace that follows:

```
    09:00:00,476 -8080-exec-7 ERROR org.flowable.rest.exception.BaseExceptionHandlerAdvice - Unhandled exception
    org.flowable.engine.common.api.FlowableException: Error parsing form definition JSON
      at org.flowable.form.engine.impl.parser.FormDefinitionParse.execute(FormDefinitionParse.java:96)
    [...]
      at org.flowable.form.engine.impl.parser.FormDefinitionParse.execute(FormDefinitionParse.java:83)
    Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "editorJson" (class org.flowable.form.model.FormModel), not marked as ignorable (8 known properties: "outcomes", "version", "fields", "id", "description", "key", "outcomeVariableName", "name"])
```

**Comment by tijsrademakers** [comment]
Hi,

In the App details screen there two options to download the app, one is a zip to import in another modeler environment. But there's also the option to generate a BAR file and this is the one you should use to deploy using the Flowable Admin app. Please reopen if this also doesn't work.
