### ISSUE TITLE
Classcast exception in org.flowable.test.ldap.LdapGroupCacheTest

### ISSUE THREAD

**Issue by dbmalkovsky** [flowable/flowable-engine#65]
I was running tests and ran across an issue in `org.flowable.test.ldap.LdapGroupCacheTest.java` where `IdmIdentityServiceImpl`  cannot be cast to `LDAPIdentityServiceImpl`.  I assume this is result of the refactoring of the IDM modules.

Here is the top of the traceback.

```java
-------------------------------------------------------------------------------
Test set: org.flowable.test.ldap.LdapGroupCacheTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 9.673 sec <<< FAILURE!
testLdapGroupCacheExpiration(org.flowable.test.ldap.LdapGroupCacheTest)  Time elapsed: 6.307 sec  <<< ERROR!
java.lang.ClassCastException: org.flowable.idm.engine.impl.IdmIdentityServiceImpl cannot be cast to org.flowable.ldap.LDAPIdentityServiceImpl
	at org.flowable.test.ldap.LdapGroupCacheTest.setUp(LdapGroupCacheTest.java:33)
	at junit.framework.TestCase.runBare(TestCase.java:139)
```

I will leave it to the main authors as to decide the proper changes.

**Comment by tijsrademakers** [comment]
Thanks, fixed
