### ISSUE TITLE
Classcast exception when taking sequence flow

### ISSUE THREAD

**Issue by kristofdepypere** [flowable/flowable-engine#654]
I have the following situation after updating from activiti 5.21:

`java.lang.ClassCastException: org.flowable.bpmn.model.SequenceFlow cannot be cast to org.flowable.bpmn.model.FlowNode
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.continueThroughSequenceFlow(ContinueProcessOperation.java:282)
	at org.flowable.engine.impl.agenda.ContinueProcessOperation.run(ContinueProcessOperation.java:77)
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:88)
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:72)
	at org.flowable.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:56)
	at org.flowable.engine.impl.interceptor.BpmnOverrideContextInterceptor.execute(BpmnOverrideContextInterceptor.java:25)`

This happens in the org.flowable.engine.impl.agenda.ContinueProcessOperation#continueThroughSequenceFlow method where a SequenceFlow is input, but casts happen to org.flowable.bpmn.model.FlowNode but they don't seem to be in the same hierarchy.

Existing version is activiti 5.21, it happens right after switching to flowable 6.2.0

**Comment by tijsrademakers** [comment]
Hi, thanks for sharing this. Could you also share the BPMN XML and point to the execution where this error is happening?

**Comment by kristofdepypere** [comment]
Attached the bpmn used. It has only one execution.

[Expense_process.bpmn.zip](https://github.com/flowable/flowable-engine/files/1467114/Expense_process.bpmn.zip)

**Comment by tijsrademakers** [comment]
This is a really straightforward BPMN process, so this runs perfectly fine with Flowable 6. Did you deploy the BPMN XML as a new process definition to the Flowable 6 Engine, or was it already deployed on the 5.21 engine? If it was already deployed, are you using the embedded Flowable 5 engine in Flowable 6 by using the flowable5-compatibility modules as described in the migration guide?

**Comment by tijsrademakers** [comment]
Please reopen the issue when you are still running into this, but closing it for now.

**Comment by 777sfdf** [comment]
May I ask how this problem was ultimately resolved through a version change or other means

**Comment by 777sfdf** [comment]
May I ask how this problem was ultimately resolved through a version change or other means
