### ISSUE TITLE
DeploymentManager.resolveDecisionTable() throws NullPointerException 

### ISSUE THREAD

**Issue by quaff** [flowable/flowable-engine#656]
```java
@Component
public class Test {

	@Autowired
	private DmnRepositoryService dmnRepositoryService;

	@Autowired
	private DmnEngineConfiguration dmnEngineConfiguration;

	public void test() {
		DmnDecisionTable decisionTable = dmnRepositoryService.createDecisionTableQuery().decisionTableKey("test")
				.latestVersion().singleResult();
		dmnEngineConfiguration.getDeploymentManager().resolveDecisionTable(decisionTable);
	}

}
```
```xml
<?xml version="1.0" encoding="UTF-8"?>
<beans 
	xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd">
	
	<bean id="dmnEngineConfiguration" class="org.ironrhino.flowable.dmn.spring.SpringDmnEngineConfiguration">
		<property name="dataSource" ref="dataSource" />
		<property name="transactionManager" ref="transactionManager"/>
		<property name="databaseSchemaUpdate" value="${dmnEngineConfiguration.databaseSchemaUpdate:true}" />
		<property name="enableSafeDmnXml" value="${dmnEngineConfiguration.enableSafeDmnXml:true}"/>
		<property name="historyEnabled" value="${dmnEngineConfiguration.historyEnabled:true}" />
		<property name="deploymentResources" value="${dmnEngineConfiguration.deploymentResources:classpath*:/resources/dmn/*.dmn}" />
	</bean>
	
	<bean id="dmnEngine" class="org.flowable.dmn.spring.DmnEngineFactoryBean">
		<property name="dmnEngineConfiguration" ref="dmnEngineConfiguration" />
	</bean>
	
	<bean id="dmnRepositoryService" factory-bean="dmnEngine" factory-method="getDmnRepositoryService" />
	<bean id="dmnRuleService" factory-bean="dmnEngine" factory-method="getDmnRuleService" />
	<bean id="dmnHistoryService" factory-bean="dmnEngine" factory-method="getDmnHistoryService" />
 
</beans>
```
```
Caused by: java.lang.NullPointerException
	at org.flowable.engine.common.impl.db.AbstractDataManager.getSession(AbstractDataManager.java:45) ~[flowable-engine-common-6.2.0.jar:6.2.0]
	at org.flowable.engine.common.impl.db.AbstractDataManager.getEntityCache(AbstractDataManager.java:53) ~[flowable-engine-common-6.2.0.jar:6.2.0]
	at org.flowable.engine.common.impl.db.AbstractDataManager.findById(AbstractDataManager.java:63) ~[flowable-engine-common-6.2.0.jar:6.2.0]
	at org.flowable.dmn.engine.impl.persistence.entity.AbstractEntityManager.findById(AbstractEntityManager.java:36) ~[flowable-dmn-engine-6.2.0.jar:6.2.0]
	at org.flowable.dmn.engine.impl.persistence.deploy.DeploymentManager.resolveDecisionTable(DeploymentManager.java:144) ~[flowable-dmn-engine-6.2.0.jar:6.2.0]
```

**Comment by tijsrademakers** [comment]
The call to the DeploymentManager resolveDecisionTable is not valid, because it's executed without a transaction. If you use the DmnRepositoryService, or one of the other interfaces for the DMN engine, it will work just fine.
